### ISSUE TITLE
Speech recognition only works once

### ISSUE THREAD

**Issue by mploigt** [csdcorp/speech_to_text#10]
If you do a recognition, click on stop and try again immediately, no text will be recognised. Only if you wait for approx 30 seconds, recognition will work again.

**Comment by sowens-csd** [comment]
So sorry, for some reason I haven't been getting notified on these issues. Is this on both Android and iOS? I'm not seeing that behaviour in the sample app.

**Comment by sowens-csd** [comment]
Closing this, not seeing the behaviour described.
