### ISSUE TITLE
plan on releasing 2.3.0

### ISSUE THREAD

**Issue by hakandilek** [csdcorp/speech_to_text#104]
Hello there,

thanks for the great work. I've been playing around with the library at one of my personal projects, it is really doing a great job.

I've seen the new `SpeechToTextProvider` and the example you provided. Would be happy to refactor my code to use and test it. 

Do you have any time plans for releasing v2.3.0?

Regards,
Hakan

**Comment by sowens-csd** [comment]
Glad you’re liking the plugin, thanks for the feedback. I’m hoping to get issue #100 tested then I’ll do a release. Should be this week.

**Comment by ElZombieIsra** [comment]
Hi. Is there any update on this version release to Pub? I'm looking to implement the ´pauseFor´ prop in the listen method.

**Comment by sowens-csd** [comment]
2.3.0 just went live on pub.dev. Enjoy! And let me know if you spot any issues.
