### ISSUE TITLE
Auto stop on iOS

### ISSUE THREAD

**Issue by ElZombieIsra** [csdcorp/speech_to_text#105]
It seems like the recognizer takes forever to auto stop on iOS whether on Android it auto stops within 1 or 2 seconds after recognizing the speech. 
I already set the `listenFor` param to 10 secs but even if the speech takes 2 seconds to be said, the plugin still waits the entire 10 seconds to stop recognizing. 
Is there a way to make the iOS version to auto stop after recognizing the speech like the Android version works?

Thanks in advance.

**Comment by sowens-csd** [comment]
There's a new `pauseFor` parameter on the `listen` method in the repo now. I think it does what you want. I'm hoping to release the repo to pub.dev this week.

**Comment by ElZombieIsra** [comment]
Ok, let me check it out and I will be giving you feedback as soon as I implement it, thanks

**Comment by sowens-csd** [comment]
2.3.0 is out with this functionality. I'll close this issue tomorrow unless you have further questions?

**Comment by ElZombieIsra** [comment]
Ok thanks. Let me test it out and I'll let you know.

**Comment by sowens-csd** [comment]
I'm hoping that worked for you and closing this issue. Let me know if you have further questions.

**Comment by MherKarapetyan** [comment]
Is it work in 2.4.1 version?
I set those arguments, but it does not work for me.

 ```
await speech.listen(
        listenFor: Duration(seconds: 3),
        pauseFor: Duration(seconds: 1),
        onResult: (_result) {
            // _autoStopInIos();
            speechRecognitionResult.sink.add(_result.recognizedWords);
        },
        localeId: 'en_US',
        partialResults: true,
      );
```

**Comment by sowens-csd** [comment]
I just tried it and it seems to be doing what I expect. What behaviour are you seeing?
