### ISSUE TITLE
How to prevent auto stop on Android ?

### ISSUE THREAD

**Issue by aayu24** [csdcorp/speech_to_text#106]
Hello. I am using the 2.2.0 version, and I had a doubt. Is there any way to prevent automatic stopping of audio listening on Android? What I want is that the listening should stop only when the User either stops it manually or cancels it.

Currently I have set listenFor to 10 seconds.  

PS: When do you plan to release v2.3.0 ? I am excited to see the SpeechProvider functionality.

**Comment by sowens-csd** [comment]
Good morning. Unfortunately, I haven't yet found a way around the Android OS default behaviour of stopping quickly on a pause in speech. This feature is definitely interesting for a lot of users but I haven't yet found a solution that seems reliable. I am tracking this issue under #63. 

The next version should be released this week. I'm just waiting for test results on issue #100 then I'll get it out.

**Comment by sowens-csd** [comment]
I'm going to close this issue and track the stop behaviour with #63. Let me know if you have any questions.
