### ISSUE TITLE
Noticed a delay with the sound effects and the speech recognition functions

### ISSUE THREAD

**Issue by tedserdel** [csdcorp/speech_to_text#108]
Simulator: iOS - iPhone 11

I noticed a 2-second delay between the sound effects and their respective speech recognition functions.

When Start is tapped the sound effect plays and 2 seconds later the statusListener shows true, similarly when Stop is tapped the sound effect plays and 2 seconds later the statusListener shows false.

How can the timing be adjusted so that sounds effect and function runs at the same time?

**Comment by tedserdel** [comment]
My m4r sound effect files are about 2 seconds, could that be the cause?

If so, can the speech recognition function start **asynchronously** with the sounds? Function seem to wait for the sound effect to finish before the startListening and stopListening functions.

**Comment by tedserdel** [comment]
SOLUTION:
1. Open m4r files in QuickTime Player
2. Trim - ⌘T (Edit/ Trim)
3. Trim to be less than 1 second - since the function waits for sound to end before starting or stopping
4. Export audio file (File/ Export As/ Audio Only...)
5. Convert m4a to m4r (used this [converter](https://www.zamzar.com/convert/m4a-to-m4r/))
6. Rename files accordingly
  - speech_to_text_listening.m4r
  - speech_to_text_stop.m4r
  - speech_to_text_cancel.m4r

**Comment by tamoyal** [comment]
@sowens-csd I've actually done quite a bit of playing around with this today and when compared to iOS dictation, it's much slower even with no sound. Any chance the delay is specific to something in this library? If so, we may want to open this issue
