### ISSUE TITLE
Does library just recognize English?

### ISSUE THREAD

**Issue by tuannguyen90** [csdcorp/speech_to_text#113]
I tested on iOS device, everything with English language is ok. But when I tried with Vietnamese(vi-VN), there was no result.I tried to change localeID to 'vi', but it was not working.
Thanks.

**Comment by sowens-csd** [comment]
It should handle anything the device itself can handle. You can use the `locales` property to get the list of locales supported by the device. If you don't see the language you want in that list then check if that locale is installed on the device.

**Comment by sowens-csd** [comment]
Unless you have further questions I'll close this?
