### ISSUE TITLE
Continuously running recognition form startup.

### ISSUE THREAD

**Issue by Joe02** [csdcorp/speech_to_text#116]
Does stt has any viable ways to run the recognition from startup?
Lets say I'm opening a new screen on my Mobile app, and I want it to listen to every word my user speaks, from the moment I build the screen to the very moment I exit it, without clicking at any given widget. 

Is this possible?

Or does the only workable method of using the recognition is to call it from a onPressed, onTap, etc?

**Comment by sowens-csd** [comment]
You can definitely start the recognizer in the background, it needn't be started from a user interaction. The bigger issue is that on both iOS and Android there is a maximum time it will listen for speech. If the user is spending much time on that screen then they would likely exceed that maximum. On Android there's an ~5 second timeout and a maximum of only 30 seconds or so of speech. On iOS these values are higher but there are still limits.

**Comment by sowens-csd** [comment]
If you're still having problems let me know, I'm going to close this issue.
