### ISSUE TITLE
[+29603 ms] > Task :speech_to_text:compileDebugKotlin

### ISSUE THREAD

**Issue by imeDevelopers** [csdcorp/speech_to_text#117]
[   +9 ms] w:
E:\Android\flutter\.pub-cache\hosted\pub.dartlang.org\speech_to_text-2.3.0\android\src\main\kotlin\com\csdcorp\speech_to_text\SpeechToTextPlugin.kt: (215, 13): Variable 'localContext' is    
never used
[  +12 ms] w:
E:\Android\flutter\.pub-cache\hosted\pub.dartlang.org\speech_to_text-2.3.0\android\src\main\kotlin\com\csdcorp\speech_to_text\SpeechToTextPlugin.kt: (301, 13): Condition 'null ==
detailsIntent' is always 'false'
[  +17 ms] w:
E:\Android\flutter\.pub-cache\hosted\pub.dartlang.org\speech_to_text-2.3.0\android\src\main\kotlin\com\csdcorp\speech_to_text\SpeechToTextPlugin.kt: (331, 42): Unnecessary safe call on a    
non-null receiver of type Bundle?

**Comment by sowens-csd** [comment]
Thanks for letting me know. I think these are all fixed in an update I just posted. Not yet ready for prime time but should clear these up at least.

**Comment by sowens-csd** [comment]
With the release of 2.4.0 this should be resolved. If not, let me know.
