### ISSUE TITLE
Stopping and Starting new recordings error iOS

### ISSUE THREAD

**Issue by jordanhart** [csdcorp/speech_to_text#118]
Hi!

I am trying to parse a single word command at a time for an arbitrary amount of commands. My current approach is to just start listening and stop recording after each word, with hopes of having 60 seconds per command. I copied the code from https://github.com/csdcorp/speech_to_text, 'Using Section' and get the error below when calling stop.

2020-07-28 22:29:18.549895-0700 Runner[4701:2427108] [Utility] +[AFAggregator logDictationFailedWithError:] Error Domain=kAFAssistantErrorDomain Code=203 "Corrupt" UserInfo={NSLocalizedDescription=Corrupt, NSUnderlyingError=0x283bd6100 {Error Domain=SiriSpeechErrorDomain Code=102 "(null)"}}
2020-07-28 22:29:18.550105-0700 Runner[4701:2425568] [plugin] FinishSuccessfully with error: Optional(Error Domain=kAFAssistantErrorDomain Code=203 "Corrupt" UserInfo={NSLocalizedDescription=Corrupt, NSUnderlyingError=0x283bd6100 {Error Domain=SiriSpeechErrorDomain Code=102 "(null)"}})

I get a similar issue using cancel, but after a couple speech.stops, then speech.listens. 

Would there be any advice for getting around this issue? Also, is my approach sane for determining one word at a time and will it allow 60 seconds per word instead of 60 seconds for all words?

Thank you!

**Comment by jordanhart** [comment]
Turns out this issue disappeared when canceling on a timer https://stackoverflow.com/questions/52569602/flutter-run-function-every-x-amount-of-seconds

**Comment by jordanhart** [comment]
Any idea on why it breaks without scheduling with a timer?

**Comment by sowens-csd** [comment]
No, doesn't make sense. The timer calls `stop` so it should be the same behaviour. I'm wondering if It could be timing related, i.e. calling `listen` too soon after stop and maybe the stop hasn't had completed yet, but that's a complete guess. I'll see if I can reproduce it. 

Is the problem reproducible in the sample app? Does it happen every time you call `stop` or just sometimes? Is it on a simulator or a real device? Which iOS version?

**Comment by sowens-csd** [comment]
From your description it sounds like maybe you are calling `stop` from the `onResult` callback every time you get a word in the callback, is that right? When do you call `start`?

**Comment by sowens-csd** [comment]
Any more information on this issue? If not I'll close it.
