### ISSUE TITLE
Not working in Android 10 version

### ISSUE THREAD

**Issue by sathishmscict** [csdcorp/speech_to_text#119]
Davey! duration=2933ms; Flags=1, IntendedVsync=78260512397810, Vsync=78263179064370, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=78263200072681, AnimationStart=78263200147421, PerformTraversalsStart=78263201368671, DrawStart=78263436029140, SyncQueued=78263437236640, SyncStart=78263437800806, IssueDrawCommandsStart=78263438023411, SwapBuffers=78263443465025, FrameCompleted=78263446256067, DequeueBufferDuration=4031000, QueueBufferDuration=1843000, 
E/flutter (13319): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(multipleRequests, Only one initialize at a time, null)
E/flutter (13319): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (13319): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (13319): <asynchronous suspension>
E/flutter (13319): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (13319): #3      SpeechToText.initialize (package:speech_to_text/speech_to_text.dart:190:10)
E/flutter (13319): #4      _MyAppState.initSpeechState (package:speech_to_text_example/main.dart:34:35)
E/flutter (13319): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
E/flutter (13319): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
E/flutter (13319): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (13319): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
E/flutter (13319): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
E/flutter (13319): #10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)
E/flutter (13319): #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
E/flutter (13319): #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter (13319): #13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter (13319): #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (13319): #15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter (13319): #16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter (13319): #17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (13319): #18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (13319): #19     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (13319): #20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (13319): #21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (13319): #22     _rootRunUnary (dart:async/zone.dart:1196:13)
E/flutter (13319): #23     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (13319): #24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter (13319): #25     _invoke1 (dart:ui/hooks.dart:275:10)
E/flutter (13319): #26     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)
E/flutter (13319): 

Version : 2.3.0
Android OS version : 10 (Pie)
Device : Nokia 6.1 plus &  Mi A2 devices

**Comment by sowens-csd** [comment]
Looks like it's trying to call initialize more than once. Is this from the example app or from your code?

**Comment by sowens-csd** [comment]
Any more information on this issue? If not, I'll close it.
