### ISSUE TITLE
Please bro, I dun understand while this happen @@

### ISSUE THREAD

**Issue by dinhan1192** [csdcorp/speech_to_text#120]
![image](https://user-images.githubusercontent.com/42635147/89404444-35e26980-d744-11ea-8398-8e1f970820a1.png)

**Comment by dinhan1192** [comment]
I already have the void resultlisterner

**Comment by dinhan1192** [comment]
![image](https://user-images.githubusercontent.com/42635147/89407162-7e038b00-d748-11ea-89ea-6198e0e417ac.png)
sorrry, but it does not work at all !!!!

**Comment by sowens-csd** [comment]
My first thought would be that your local cache is incorrect. First thing to try is a `flutter clean` then a full rebuild. If that doesn't work then try deleting all entries for speech_to_text from your .pub-cache then redo the `flutter pub get` on the project. You might have to close and reopen the IDE to get it to recognize the cache updates. Let me know if any of that helps.

**Comment by dinhan1192** [comment]
My problem is that the whole example run well, but when it comes to the
parts of it, it doesn’t run as expected...
