### ISSUE TITLE
I dun understand while it does not jump into the resultListener function

### ISSUE THREAD

**Issue by dinhan1192** [csdcorp/speech_to_text#122]
![image](https://user-images.githubusercontent.com/42635147/89627659-643b8280-d8c5-11ea-88bf-979bbb85215e.png)
![image](https://user-images.githubusercontent.com/42635147/89627681-6e5d8100-d8c5-11ea-8a51-fa649bcd631c.png)

I also repaired cache!

**Comment by sowens-csd** [comment]
Glad the cache repair worked. I'm afraid I don't understand your question. Could you provide more details?
