### ISSUE TITLE
Language Support?

### ISSUE THREAD

**Issue by arashhesni** [csdcorp/speech_to_text#123]
is there any language support? like Persian or just it's English? if so can you say how?

**Comment by sowens-csd** [comment]
Definitely, it should support any language installed on the device. There's a `locales` property on the `SpeechToText` instance that provides the list of locales installed on the device as `LocaleName` instances. Then the `listen` method takes an optional `localeId` named param which would be the `localeId` property of any of the values returned in `locales`. Let me know if any of that is unclear.

**Comment by sowens-csd** [comment]
I'll close this issue as answered. Let me know if you have further questions.
