### ISSUE TITLE
Android error speech recognition not working

### ISSUE THREAD

**Issue by whispers16** [csdcorp/speech_to_text#126]
When I start the recording this error is printed in console `Error 3 after start at 1188 1000.0 / -100.0`, and does not output any text recognized.

I tried on Android 10.

Do you know why is it possibly not working?

Thank you
```
D/SpeechToTextPlugin(19739): Start initialize
D/SpeechToTextPlugin(19739): Checked permission
D/SpeechToTextPlugin(19739): has permission, completing
D/SpeechToTextPlugin(19739): completeInitialize
D/SpeechToTextPlugin(19739): Testing recognition availability
D/SpeechToTextPlugin(19739): Creating recognizer
D/SpeechToTextPlugin(19739): Setting listener
D/SpeechToTextPlugin(19739): before setup intent
D/SpeechToTextPlugin(19739): setupRecognizerIntent
D/SpeechToTextPlugin(19739): after setup intent
D/SpeechToTextPlugin(19739): sending result
D/SpeechToTextPlugin(19739): leaving complete
D/SpeechToTextPlugin(19739): leaving initializeIfPermitted
D/SpeechToTextPlugin(19739): Start listening
D/SpeechToTextPlugin(19739): setupRecognizerIntent
D/SpeechToTextPlugin(19739): Notify listening
D/SpeechToTextPlugin(19739): Notify listening done
D/SpeechToTextPlugin(19739): Start listening done
D/SpeechToTextPlugin(19739): Error 3 after start at 1188 1000.0 / -100.0
D/SpeechToTextPlugin(19739): Cancel listening
D/SpeechToTextPlugin(19739): Notify listening
D/SpeechToTextPlugin(19739): Notify listening done
D/SpeechToTextPlugin(19739): Cancel listening done
```

**Comment by sowens-csd** [comment]
Have a read through https://github.com/csdcorp/speech_to_text#not-working-on-a-particular-android-device. The most likely cause is that speech recognition isn't enabled on the device you're using. There are tips in that README link for resolving it.

**Comment by whispers16** [comment]
Yeah, before creating this issue I tested what the README says, the microphone is allowed and working in the google app, I also granted permissions to my flutter app and I just double checked but the same is happening, in iOS is working fine though.

**Comment by whispers16** [comment]
I think I found the problem, while I'm using this library i'm also recording the voice to reproduce it later, it seems that both libraries clashes when using the voice recording at the same time, in iOS works perfect though.
Do you know a work around for this? I mean being able to use the speech recognizer while recording your voice at the same time?

**Comment by sowens-csd** [comment]
Ah, that's interesting. I haven't run into this on Android before though the iOS version did have this problem originally. I changed the record mode and got it to work. I don't currently have a work around for Android but I'll do some research.

**Comment by sowens-csd** [comment]
I've found no solution to this, looks like I'll have to document this problem as a known issue in the readme. Here's the references I've found so far. Once I've added the docs I'll close this. 
https://developer.android.com/guide/topics/media/sharing-audio-input
https://stackoverflow.com/questions/39765018/android-record-audio-while-doing-speech-recognition

**Comment by whispers16** [comment]
:( it's sad android didn't think of this from the very beginning, thank you for trying to find a solution

**Comment by shreyj357** [comment]
Hi, I just want add something in this conversation. I am also doing something like @whispers16 , where I am recording audio and also want speech to text feature, and It is not working in my latest Mobile i.e. **android version 10**  but I am able to record and convert speech to text in **android version 7**.

**Comment by whispers16** [comment]
Thanks @shreyj357  i'll try with that version, it's weird though android doesn't support new versions

**Comment by sowens-csd** [comment]
This is now documented in the 3.0.0 README, closing as can't fix.

**Comment by suryakj** [comment]
Set the targetsdk version to 29 and rerun the app on Android 10. It will definitely work.

**Comment by theflutterguy** [comment]
Trying to test it @suryakj, But no success!
