### ISSUE TITLE
SpeechToTextProvider set language

### ISSUE THREAD

**Issue by RedAvenge** [csdcorp/speech_to_text#128]
Hey there, I'm using your new way of interacting with the speech plugin with the `SpeechToTextProvider` but I cant find the place where I can set the language.

With the "old" way there is the `localeId` field on the `SpeechToText.listen()` method as mentioned in #123 but with the `Provider.of<SpeechToTextProvider>(context).listen()` there is not. I also looked in your [provider_example.dart](https://github.com/csdcorp/speech_to_text/blob/main/example/lib/provider_example.dart) but there you only read the `_currentLocaleId` from the ui fields but never use it in the `.listen()` method either.

So how can I set the language with the `SpeechToTextProvider`-Pattern?

**Comment by sowens-csd** [comment]
Thanks for using the provider, I'm hoping to move more usage to that pattern over time. Well that's an embarrassing oversight on my part! I'll have to add it to the `listen` method. Look for it soon, that's a must have.

**Comment by RedAvenge** [comment]
I tried it and it works as indented. Many thanks for the quick response and quick implementation of it!

**Comment by sowens-csd** [comment]
2.5.0 with this change is released.
