### ISSUE TITLE
Offline recognition

### ISSUE THREAD

**Issue by EskAere** [csdcorp/speech_to_text#134]
Hi, 

First, thank you for this project ! 

I was wondering, do you plan to support offline/realtime recognition ? 

Thank you, enjoy your day :)

**Comment by sowens-csd** [comment]
Offline is currently supported as well as the local device support allows. If you set the `onDevice` flag on the `listen` method to true, it will force the device to use local capabilities. This can fail if the device doesn't support it. Even without that flag the listener initialization that I've used prefers local recognition when available. 

Let me know if you're looking for other support.

**Comment by EskAere** [comment]
Ok thanks i'll try it. I missed it because i'm using SpeechToTextProvider. It doesn't expose the `onDevice` flag. Out of curiosity, is there any reason for that ? 

Thank you again !

**Comment by sowens-csd** [comment]
Not a good reason, no. I tried to keep SpeechToTextProvider simpler and so put in only the options that felt required. Not sure that's really helpful so I've been adding options back to the provider in each release.

**Comment by EskAere** [comment]
I can't make it work. I always have `error_network`. My device probably doesn't support it. Is there any way to know that ?

**Comment by sowens-csd** [comment]
So it looks like, embarrassingly, I did not do the Android implementation for this feature. I'm adding it now and will release an update shortly. 
There doesn't seem to be a way that I've found yet to detect whether offline is supported on Android. Currently you'd have to try it, catch the exception, then provide feedback to the user. 
Also, it seems from some articles that I've read, that at least on some devices you have to explicitly install an offline language pack before offline mode will work. See here for example https://stackoverflow.com/questions/17616994/offline-speech-recognition-in-android-jellybean

**Comment by sowens-csd** [comment]
The implementation is now live as 2.6.0.
