### ISSUE TITLE
Speech to text only run language English(United States),English(United Kingdom), English(Viet Nam) in IOS version 13

### ISSUE THREAD

**Issue by sonvp** [csdcorp/speech_to_text#135]
Hi all. Can you help me for this issuse. As I mentioned in the above title, I tested Speech to text. It only run language English(United States),English(United Kingdom), English(Viet Nam). Can't run in another language like English(Singapore) ,Spain(Spain), Polish(Poland). And i tested it in IOS 12. It work well

**Comment by sowens-csd** [comment]
Are the other languages installed on the phone? It should expose and support any languages that are installed on the phone. What does the `locales` property show on the two phones?

**Comment by sonvp** [comment]
Hi @sowens-csd . Today, I tested it with Iphone7 (ios 13.6.1) and Iphone 6(ios 12.4.8) with languages below. It only can run in Iphone 6(ios 12.4.8) and not working Iphone7 (ios 13.6.1).

English(New Zealand) locales en-NZ
English(Singapore) locales en-SG
Polish(poland) locales pl-PL
Ukrainian(Ukraine) locales uk-UA
Thai(Thailand) locales th-TH
Malay(Malaysia) locales ms-MY
Danish (Denmark) locales da-DK
VietNameses (Vietnam) locales vi-VN

**Comment by sowens-csd** [comment]
Sounds like the language issue is resolved then since you can see that list of languages? What happens on the iPhone 7?

**Comment by sonvp** [comment]
Hi @sowens-csd. On the iphone 7, when i press text "initalize", then i select language in drop, then i select button 'Start', then i don't see anything happen, text "Not listening" don't change to "I'm listening"

**Comment by sowens-csd** [comment]
Can you try it with `debugLogging` set to true on the `initialize` call and check the output? There's no reason the iPhone7 shouldn't work that I know of.

**Comment by sowens-csd** [comment]
Without more information I can't troubleshoot this issue. Closing.
