### ISSUE TITLE
Is it possible to record the input speech to devices as .wav file while recognizing the same piece of speech?

### ISSUE THREAD

**Issue by tommycyf** [csdcorp/speech_to_text#136]
Hi, everyone.

During the recognition, can I somehow save the input speech and save/play it on my local device? 

I tried starting flutter_audio_recorder together with speech_to_text, then flutter_audio_recorder was working but speech_to_text was not, and returning "error_speech_timeout" error.
Is this something concerned with audio channel conflicts?

Thanks for sharing this nice speech_to_text package, it really helped me a lot!

**Comment by sowens-csd** [comment]
No, the package doesn't yet have this capability. Interesting sounding feature though. Was the conflict on Android or iOS? I think it should work on iOS but I haven't found any way to share the input channel on Android yet.

**Comment by tommycyf** [comment]
The conflict happens on Android. It works perfectly with flutter_audio_recorder on iOS.

[https://github.com/felixjunghans/google_speech](url)
When I use this package, recognizing and recording can be done at the same time both on iOS and Android.

**Comment by jtkeyva** [comment]
Recording sound works on iOS 12 with flutter_sound package

https://github.com/dooboolab/flutter_sound/issues/210

**Comment by sowens-csd** [comment]
> The conflict happens on Android. It works perfectly with flutter_audio_recorder on iOS.
> 
> [https://github.com/felixjunghans/google_speech](url)
> When I use this package, recognizing and recording can be done at the same time both on iOS and Android.

Sorry, I missed this post. Yes, this works because it's using the Google Speech Api which is a cloud service, not local to the device.

**Comment by sowens-csd** [comment]
Currently the answer to this question is no, it is not possible on Android.
