### ISSUE TITLE
 Recognise  only  the voice of the device owner?

### ISSUE THREAD

**Issue by Liliana99** [csdcorp/speech_to_text#137]
Hi,

I would like to know if this package could be possible to  recognizer only  the voice of the device owner??

**Comment by sowens-csd** [comment]
No, it does not. That would be an interesting feature though. It would take some support at the OS level to enable it and I don't think I've seen any such features exposed in either iOS or Android. I know that Siri and probably Google do take advantage of recognizing individual voices but I don't think that the APIs have exposed any of that yet.

**Comment by sowens-csd** [comment]
I'm going to close this as won't fix,  but let me know if you have more questions.
