### ISSUE TITLE
On device recognition is not supported on IOS 14

### ISSUE THREAD

**Issue by korolkir** [csdcorp/speech_to_text#138]
Hi. Have the latest version of the plugin 2.5.0. I tried IOS 14 beta version (IOS 14 will be available tomorrow). Unfortunately I'm receiving "on device recognition is not supported on this device" error when trying to launch in onDevice = true mode. Isn't it supported for IOS 14? Thanks in advance.

**Comment by sowens-csd** [comment]
That's a great question, not sure. Which device are you trying it on?

**Comment by korolkir** [comment]
Iphone 11 Pro Max. Currently have fresh iOS 14 (not beta). Have the same issue. On iOS 13 onDevice recognition was working fine.

**Comment by sowens-csd** [comment]
Thanks. That device should definitely support it. I'll try it on iOS 14 and see what's up.

**Comment by sowens-csd** [comment]
Apparently the property I'm using to determine if on device recognition is supported is flaky? Still following up but here's the reference. 
https://twitter.com/Valzevul/status/1177241666593415168

Evil if true.

**Comment by sowens-csd** [comment]
I just pushed an attempted fix for this. It's fairly simple but seems to improve the behaviour on my test device. At `initialize` time it asks for the on device support value, which in my case was false on this first ask. Then when `listen` is called it asks again, the second ask returned a reliable result. If you have time to try it out please do. It will be in the 3.0.0 release.

**Comment by sowens-csd** [comment]
This is released in 3.0.0
