### ISSUE TITLE
Plugin not working anymore after update to 2.7

### ISSUE THREAD

**Issue by cold80** [csdcorp/speech_to_text#140]
Today i updated a project of my using speech_to_text, it was 2.3 before, now with 2.7 it's not working anymore. I get

error_speech_timeout
and
error_client

as soon as I try to listen to speech recognition. The app was working perfectly before, I've tried with 3 different devices and the output is the same. Can you suggest something to try?

**Comment by sowens-csd** [comment]
Well that's worrisome. Thanks for reporting. Is it the same behaviour on both iOS and Android? If you have a chance can you try the 2.6 version and see if it has the same behaviour? I'm looking at it now.

**Comment by cold80** [comment]
Just tried with version 2.6, not working, same errors. The version 2.5 is working, so I revert to this version now. Please let me know if I can do some tests for you.

**Comment by sowens-csd** [comment]
Is the failure on Android or iOS? Which version of the OS? 

I've just tried both the example app and one of my apps that uses the plugin and it worked properly on both Android 10 and iOS 14 with 2.7. Can you give me some more details about the `listen` call you're using? Also, if you could `initialize` with `debugLogging=true` and send me the logs that might help.

**Comment by cold80** [comment]
I'm testing it with some Zebra Android devices, Android version 8.1.0. 

The listen is like that

await _engine.listen(
          onResult: _resultListener,
          listenFor: Duration(seconds: 10),
          localeId: "it_IT",
          onSoundLevelChange: _soundLevelListener,
          cancelOnError: false,
          partialResults: false,
          onDevice: true,
          listenMode: ListenMode.deviceDefault);

Let me have a device with me and I will send you the log

**Comment by sowens-csd** [comment]
Could you try it with `onDevice=false`? I really should have put it more clearly in the release notes. Prior to 2.6 the Android version ignored the `onDevice` flag completely. As of 2.6 it now respects it so if the device doesn't handle it then you'll get the failure you're seeing. Many devices can do it but require manual configuration of the local speech recognition capability to enable it.

**Comment by cold80** [comment]
You're right, with onDevice=false now it's working. You can close the issue, but I will stress it in the release notes.

Thank you again for your help

Sebastiano
