### ISSUE TITLE
D/SpeechToTextPlugin(12555): Error 9 after start at 35 1000.0 / -100.0

### ISSUE THREAD

**Issue by kiwicmc** [csdcorp/speech_to_text#144]
Hi, I was getting this error on an Android simulator - sdk gphone x86 (Pixel 3a API 30) launched from IntelliJ on a Mac. When running sample app, Initialize works, but Start failed.

AUDIO_RECORD perms were in Manifest, also manually set Mic perms in Android Settings, but only resolved it by Opening Google, clicking Mic icon and granting it perms, then everything on the App works...

D/SpeechToTextPlugin(12555): put partial
D/SpeechToTextPlugin(12555): put languageTag
D/SpeechToTextPlugin(12555): Error 9 after start at 35 1000.0 / -100.0
D/SpeechToTextPlugin(12555): Cancel listening

Just thought I leave this note here for others

**Comment by sowens-csd** [comment]
Thanks for posting, I've added some of these notes to the README troubleshooting section as well.
