### ISSUE TITLE
pauseFor didn't work on Android 10

### ISSUE THREAD

**Issue by nachtday** [csdcorp/speech_to_text#151]
So I've tried pauseFor parameter to make the recording doesn't stop if i took a breath (around 5s) but it always stopped immediately. Is there any way to make the recording doesn't stop that quick? My current code (using demo):

```
speech.listen(
        onResult: resultListener,
        listenFor: Duration(hours: 2),
        pauseFor: Duration(minutes: 5),
        localeId: _currentLocaleId,
        onSoundLevelChange: soundLevelListener,
        cancelOnError: false,
        listenMode: ListenMode.confirmation);
```

**Comment by sowens-csd** [comment]
Unfotunately no, not on Android. Android controls the pause time, none of the work arounds I've attempted have made any difference to it. Five seconds is the expected timeout for Android. `pauseFor` is useful on iOS which only stops after a minute or so.

**Comment by nachtday** [comment]
Ahh, i see, so what should we do if we want to have like around 30s break?

**Comment by sowens-csd** [comment]
Unfortunately that's not possible on Android right now. I do continue to look for a way to work around this and will add it if I find one.
