### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by MosheElisha** [csdcorp/speech_to_text#155]
Hi,

First, thank you for the plugin. It works well and nicely documented.

Can you please add a license to the project? I would like to know if I can use it in an app I'm developing.

Thanks!

**Comment by sowens-csd** [comment]
Thanks for the positive feedback, I appreciate it. I've recently refactored the project and as a result the license moved. I'll have to check the Flutter plugins and see where they put their license in multi-platform plugins. Until then, you can find the license here: https://github.com/csdcorp/speech_to_text/tree/main/speech_to_text/LICENSE

It's a very open BSD style license, should be fine for just about any use I'd think.

**Comment by MosheElisha** [comment]
Great! Thank you.
