### ISSUE TITLE
MissingPluginException 

### ISSUE THREAD

**Issue by hortigado** [csdcorp/speech_to_text#156]
When i initialize, i get the error MissingPluginException (MissingPluginException(No implementation found for method initialize on channel plugin.csdcorp.com/speech_to_text))

**Comment by sowens-csd** [comment]
Thanks for reporting. What version of the plugin are you using? Is this in the example app or your own code?

**Comment by hortigado** [comment]
> Thanks for reporting. What version of the plugin are you using? Is this in the example app or your own code?

Hi, 3.0.1 yes in my own code. I do not understand why I get that I have tried other speech recognition libraries and it works well

**Comment by bdlukaa** [comment]
Make sure you run `flutter clean` and run it again

**Comment by sowens-csd** [comment]
@bdlukaa's advice is good, a `flutter clean` is definitely worth trying. If that doesn't work could you try version 2.7.0 for me?

**Comment by hortigado** [comment]
> Make sure you run `flutter clean` and run it again

Yes i tried flutter clean but it not changed nothing. Now i try the versio 2.7.0 and it work good 👍

**Comment by sowens-csd** [comment]
Thanks a lot. I'll have a look at 3.0.1. It is a major refactoring to use a new style of Platform independent interface creation. The example app works but it has a different dependency structure.

**Comment by hortigado** [comment]
> Muchas gracias. Echaré un vistazo a 3.0.1. Es una refactorización importante utilizar un nuevo estilo de creación de interfaz independiente de la plataforma. La aplicación de ejemplo funciona pero tiene una estructura de dependencia diferente.

Great. Regards

**Comment by yanncarlier** [comment]
I have the same issue building on Ubuntu 22:

speech recognition failed: MissingPluginException(No implementation found for method initialize on channel plugin.csdcorp.com/speech_to_text

the code:
https://pub.dev/packages/speech_to_text/example

pubspec.yaml

name: namer_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  speech_to_text: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

**Comment by bdlukaa** [comment]
@yanncarlier as it may seem, Linux is not a supported platform

**Comment by hansvdam** [comment]
@yanncarlier I have the same. running web-version from android studio gives no problem, but when deploying a web build to Firebase I get this error (in the chrome console)

**Comment by hazaimeh1991** [comment]
MissingPluginException(No implementation found for method availableCameras on channel plugins.flutter.io/camera)
