### ISSUE TITLE
Flutter speech_to_text package stops when I'm quiet

### ISSUE THREAD

**Issue by mehmetext** [csdcorp/speech_to_text#160]
I record my voice and I want to text what I say. So I use a record package. When I click the stop button, the recorder stops but STT package stops when I'm quiet. I want to stop two of them with a button. So my question is this: Can I disable automatic stop of STT package?

**Comment by sowens-csd** [comment]
The short answer is no. The pause shut-off time is controlled but the OS not the plugin. Android is particularly aggressive at stopping recognition on short pauses, usually about five seconds. I continue to look for reasonable ways around this limitation but haven't found any yet.

**Comment by sowens-csd** [comment]
I'll close this if you have no more questions about it?

**Comment by mehmetext** [comment]
I have no more questions. I hope you'll find a way for this.

**Comment by subins829** [comment]
Is there any solutions available for this ?
