### ISSUE TITLE
error_speech_timeout 

### ISSUE THREAD

**Issue by mehmetext** [csdcorp/speech_to_text#161]
I want to use the example code in https://pub.dev/packages/speech_to_text/example. When I click the start button, it throws the error "error_speech_timeout". It never starts recognizing the voice. I debug it on a real device (Galaxy Note FE, Android 9).

**Logs:**

> D/SpeechToTextPlugin(30352): Start initialize
D/SpeechToTextPlugin(30352): Checked permission
D/SpeechToTextPlugin(30352): has permission, completing
D/SpeechToTextPlugin(30352): completeInitialize
D/SpeechToTextPlugin(30352): Testing recognition availability
D/SpeechToTextPlugin(30352): sending result
D/SpeechToTextPlugin(30352): leaving complete
D/SpeechToTextPlugin(30352): leaving initializeIfPermitted
D/SpeechToTextPlugin(30352): Received extra language broadcast
D/SpeechToTextPlugin(30352): Extra supported languages
D/SpeechToTextPlugin(30352): Start listening
D/SpeechToTextPlugin(30352): setupRecognizerIntent
D/SpeechToTextPlugin(30352): Notify listening
D/SpeechToTextPlugin(30352): Notify listening done
D/SpeechToTextPlugin(30352): Start listening done
D/SpeechToTextPlugin(30352): Error 7 after start at 43 1000.0 / -100.0
I/flutter (30352): Received error status: SpeechRecognitionError msg: error_speech_timeout, permanent: true, listening: true
D/SpeechToTextPlugin(30352): Cancel listening
D/SpeechToTextPlugin(30352): Notify listening
D/SpeechToTextPlugin(30352): Notify listening done
D/SpeechToTextPlugin(30352): Cancel listening done

**Comment by sowens-csd** [comment]
Can you check the notes in the readme in the troubleshooting section on enabling speech recognition on Android devices? Speech recognition is not always installed or enabled by default on all devices.

**Comment by cosmosdesigner** [comment]
Hi @sowens-csd i have same error and i have STT enabled

**Comment by sowens-csd** [comment]
Do you have any other code in the project that might be using the microphone? Which Android OS and Device are you using?

**Comment by cosmosdesigner** [comment]
Hi @sowens-csd nop, just SST, android 9 and samsung 8

**Comment by sowens-csd** [comment]
Does the voice assistant work properly on these devices?

**Comment by sowens-csd** [comment]
I'm going to close this as I don't have enough information to troubleshoot.
