### ISSUE TITLE
Having an issue with with speech_to_text initialise

### ISSUE THREAD

**Issue by Bluebub** [csdcorp/speech_to_text#162]
this = {SpeechToText} 
 _initWorked = true
 _recognized = false
 _listening = false
 _cancelOnError = false
 _partialResults = false
 _notifiedFinal = false
 _listenStartedAt = 0
 _lastSpeechEventAt = 0
 _pauseFor = null
 _listenFor = null
 _userEnded = false
 _lastRecognized = ""
 _lastStatus = ""
 _lastSoundLevel = 0.0
 _listenTimer = null
 _systemLocale = null
 _lastError = null
 _lastSpeechResult = null
 _resultListener = {_Closure} Closure: (SpeechRecognitionResult) => void from Function 'resultListener':.
 errorListener = {_Closure} Closure: (SpeechRecognitionError) => void from Function 'errorListener':.
 statusListener = {_Closure} Closure: (String) => void from Function 'statusListener':.
 _soundLevelChange = {_Closure} Closure: (double) => void from Function 'soundLevelListener':.
 channel = {MethodChannel} 
cancelOnError = false
onResult = {_Closure} Closure: (SpeechRecognitionResult) => void from Function 'resultListener':.
onSoundLevelChange = {_Closure} Closure: (double) => void from Function 'soundLevelListener':.
partialResults = false
pauseFor = {Duration} 0:00:02.000000
 _duration = 2000000
onDevice = false
listenMode = {ListenMode} ListenMode.confirmation
 index = 3
 _name = "ListenMode.confirmation"
sampleRate = 0
localeId = "ta_IN"
listenFor = {Duration} 0:05:00.000000
 _duration = 300000000
listenParams = {_InternalLinkedHashMap} size = 5
 0 = {map entry} "partialResults" -> true
 1 = {map entry} "onDevice" -> false
 2 = {map entry} "listenMode" -> 3
 3 = {map entry} "sampleRate" -> 0
 4 = {map entry} "localeId" -> "ta_IN"
e = {PlatformException} PlatformException(noRecognizerError, Failed to create speech recognizer, null, null)
 code = "noRecognizerError"
 message = "Failed to create speech recognizer"
 details = null
 stacktrace = null

**Comment by Bluebub** [comment]
listenMethod = <not initialized>
 textRecognitionMethod = <not initialized>
 notifyErrorMethod = <not initialized>
 notifyStatusMethod = <not initialized>
 soundLevelChangeMethod = <not initialized>
 notListeningStatus = <not initialized>
 listeningStatus = <not initialized>
 speechChannel = <not initialized>
 _instance = {SpeechToText} 
this = {SpeechToText} 
 _initWorked = true
 _recognized = false
 _listening = false
 _cancelOnError = false
 _partialResults = false
 _notifiedFinal = false
 _listenStartedAt = 0
 _lastSpeechEventAt = 0
 _pauseFor = null
 _listenFor = null
 _userEnded = false
 _lastRecognized = ""
 _lastStatus = ""
 _lastSoundLevel = 0.0
 _listenTimer = null
 _systemLocale = null
 _lastError = null
 _lastSpeechResult = null
 _resultListener = {_Closure} Closure: (SpeechRecognitionResult) => void from Function 'resultListener':.
 errorListener = {_Closure} Closure: (SpeechRecognitionError) => void from Function 'errorListener':.
 statusListener = {_Closure} Closure: (String) => void from Function 'statusListener':.
 _soundLevelChange = {_Closure} Closure: (double) => void from Function 'soundLevelListener':.
 channel = {MethodChannel} 
cancelOnError = false
onResult = {_Closure} Closure: (SpeechRecognitionResult) => void from Function 'resultListener':.
onSoundLevelChange = {_Closure} Closure: (double) => void from Function 'soundLevelListener':.
partialResults = false
pauseFor = {Duration} 0:00:02.000000
 _duration = 2000000
onDevice = false
listenMode = {ListenMode} ListenMode.confirmation
 index = 3
 _name = "ListenMode.confirmation"
sampleRate = 0
localeId = "ta_IN"
listenFor = {Duration} 0:05:00.000000
 _duration = 300000000
listenParams = {_InternalLinkedHashMap} size = 5
 0 = {map entry} "partialResults" -> true
 1 = {map entry} "onDevice" -> false
 2 = {map entry} "listenMode" -> 3
 3 = {map entry} "sampleRate" -> 0
 4 = {map entry} "localeId" -> "ta_IN"
e = {PlatformException} PlatformException(noRecognizerError, Failed to create speech recognizer, null, null)
 code = "noRecognizerError"
 message = "Failed to create speech recognizer"
 details = null
 stacktrace = null

**Comment by sowens-csd** [comment]
Usually this means that whatever device you're trying to initialize on doesn't support speech recognition. If you're using Android please check the troubleshooting section of the readme, it has a section on ensuring that speech recognition is setup on your device. You could also try running with `debugLogging: true` in the `initialize` method. It will show more detail about the failure.

**Comment by Bluebub** [comment]
In physical device recognition working fine, On changing localID its showing the same like this  PlatformException(noRecognizerError, Failed to create speech recognizer, null, null)

**Comment by Bluebub** [comment]
Android is working fine

> Usually this means that whatever device you're trying to initialize on doesn't support speech recognition. If you're using Android please check the troubleshooting section of the readme, it has a section on ensuring that speech recognition is setup on your device. You could also try running with `debugLogging: true` in the `initialize` method. It will show more detail about the failure.

In Android device is working fine, its happening only in iOS device

exception = {ListenFailedException} 
this = {SpeechToText} 
cancelOnError = false
onResult = {_Closure} Closure: (SpeechRecognitionResult) => void from Function 'resultListener':.
onSoundLevelChange = {_Closure} Closure: (double) => void from Function 'soundLevelListener':.
partialResults = true
pauseFor = null
onDevice = false
listenMode = {ListenMode} ListenMode.confirmation
sampleRate = 0
localeId = "ta_IN"
listenFor = null
listenParams = {_InternalLinkedHashMap} size = 5
 0 = {map entry} "partialResults" -> true
 1 = {map entry} "onDevice" -> false
 2 = {map entry} "listenMode" -> 3
 3 = {map entry} "sampleRate" -> 0
 4 = {map entry} "localeId" -> "ta_IN"
e = {PlatformException} PlatformException(noRecognizerError, Failed to create speech recognizer, null, null)

**Comment by sowens-csd** [comment]
Which device and iOS version is it?

**Comment by sowens-csd** [comment]
> In physical device recognition working fine, On changing localID its showing the same like this PlatformException(noRecognizerError, Failed to create speech recognizer, null, null)
> 
> 0 = {map entry} "partialResults" -> true
> 1 = {map entry} "onDevice" -> false
> 2 = {map entry} "listenMode" -> 3
> 3 = {map entry} "sampleRate" -> 0
> 4 = {map entry} "localeId" -> "ta_IN"
> 
> "ta_IN" is supported?

The device should show you what the supported language locales are. If 'ta_IN' is one of the values returned by the `locales` property then yes, it should be fine.

**Comment by Bluebub** [comment]
> Which device and iOS version is it?

i have checked with iPhone 6 and 7 version 12.4.8

**Comment by Bluebub** [comment]
I Understand that iOS not supported for some local languages on Voice recognition.

**Comment by Bluebub** [comment]
How can I stop the listener sound in both devices. Is there any supported code available in this?

**Comment by sowens-csd** [comment]
I think your answer from yesterday means that the iPhone didn't support those language codes? Is that correct? 

iOS does not have a listener sound by default, if you don't place sound files in your assets list with the names expected by STT no sounds will play. Android does not allow the user to disable the speech start / stop sounds.

**Comment by Bluebub** [comment]
> I think your answer from yesterday means that the iPhone didn't support those language codes? Is that correct?
> 
> iOS does not have a listener sound by default, if you don't place sound files in your assets list with the names expected by STT no sounds will play. Android does not allow the user to disable the speech start / stop sounds.

1. Absolutely Yes,
2. Actually I used Framework Named Volume, To control the Profile mode(normal, silent).
fixed the issues.
Thanks for your support.

**Comment by sachin2151** [comment]
Hi, I am trying to enforce locale_id (for eg : ta_IN, or_IN,etc) , its working in Android even if the List of Locales given by package doesn't consist it but in IOS its not working throwing exception.

I tried Adding Language to device by going to settings,Later 
var systemLocale = await speech.systemLocale();
this is giving the default language i have set to device but while using microphone its throwing error given below,

SpeechToText.listen (package:speech_to_text/speech_to_text.dart:465:7)

These is the message i am getting from log : "Failed to create speech recognizer"
