### ISSUE TITLE
help me pls i have problem to use

### ISSUE THREAD

**Issue by fluk053** [csdcorp/speech_to_text#163]
i newbie to use lib this help me to teach me pls.
1. I am a problem with sound recording because text does not match the sound it speaks like it would intercept a specific word like dinotech, but get the word dinosaur.
2. I want to set the voice action only when I speak closely. For example, Ok google and enable.
3. How to adjust the reception distance and the sound reception level?

thank sure.

**Comment by fluk053** [comment]
this code
![image](https://user-images.githubusercontent.com/51117956/104117294-bee47900-5352-11eb-9c51-e805b30ca65d.png)

**Comment by sowens-csd** [comment]
Thanks for your interest in the plugin. The questions you've asked are unfortunately issues with the native Android or iOS speech recognition services that the plugin uses.  Recognition quality and sensitivity is determined by the OS and cannot be tuned through the plugin. This plugin is not a good choice to use for ongoing recognition like you would with Siri or Google Assistant. Each platform has its own way to support adding custom capability for those assistants but the plugin does not currently support that.
