### ISSUE TITLE
Support null safety

### ISSUE THREAD

**Issue by al8n** [csdcorp/speech_to_text#164]
Thanks for your amazing package. Is there a plan to support the null-safety version?

**Comment by sowens-csd** [comment]
Thanks for the positive feedback, I appreciate it! 

Yes, I'll definitely be updating it for null-safety. I don't have a schedule for that work yet but it will begin soon.

**Comment by kaladron** [comment]
I started on this for fun this morning - How are the .g. files generated?

**Comment by sowens-csd** [comment]
First of all, you have a strange definition of fun, but thank you! I'll have a look at your PRs but probably won't merge until after I've done the first release with web support. I really appreciate the help.

The .g files are built using the `flutter pub run build_runner build` command. Sometimes it needs the delete conflicts option to force it through.

**Comment by kaladron** [comment]
This isn't the weirdest open source task I've taken on =)

I've been planning to do one PR per repository if that's OK, that way the review can be done in smaller chunks.

It seems like it's traditional to do a major release bump for null-safety and people use that as a chance to clean up the API, so it makes sense to hold it off.  It might be worth merging to a branch if you have other interface changes you'd like to do.

Whatever way you'd like this, please let me know!

**Comment by sowens-csd** [comment]
Yes, one per repo would be great. It will be a major release and I think we should do it on a branch. That way I won't have to delay merging your PRs. I've just created a null-safety branch from main. Let me know if that works for you.

**Comment by kaladron** [comment]
That's perfect.  I'm still learning GitHub (I've used it for solo projects, but not much for collaboration) - if I need to send the PRs in a different way to target the branch, please let me know.  I'll make sure I rebase my changes to the branch.  Thanks!

**Comment by kaladron** [comment]
I've rebased my changes onto the branch now and targeted the PR at the branch.  Thanks!

**Comment by kaladron** [comment]
Hi - sorry for the newb question: How do you tell the code to use the library in the sibling directory instead of in the dart pub system?  When I'm building the speech_to_text, I don't know how to tell it to use my platform_interface instead of yours.

Thanks!

**Comment by sowens-csd** [comment]
You can use a path reference. It looks like this:

```dart
dependencies:
  speech_to_text_platform_interface:
    path: ../speech_to_text_platform_interface/
```

Sorry I've been absent on this issue, been AFK for a bit. I'm back now and I'll have a look at your PR.

**Comment by kaladron** [comment]
Thanks, I'll try to get to the other one this evening, but might be
tomorrow.

**Comment by sowens-csd** [comment]
Question for you, in the `MethodChannelSpeechToText` class you've used this syntax to match null safety requirements:

```dart
    var result = await _channel.invokeMethod<bool>('has_permission');

    return result!;
```

I don't love the intermediate variable although you're right that appears to be the only clean way to make the syntax work. There's an alternative form, which is this:

```dart
    return await _channel.invokeMethod<bool>('has_permission') ?? false;
``` 

Do you have a preference between the two forms? You may have already thought this through in choosing the syntax you did so let me know.

**Comment by kaladron** [comment]
I don't have a preference.  I wasn't confident that the await would chain
right to the ?? operator.  (I still have trouble reasoning futures
sometimes).  If it works, ?? Is better than a test because the variable is
never in there intermediate null state.

**Comment by kaladron** [comment]
Oh, I also filed an issue about how I don't think this can ever be null.  I
realized yesterday that I filled it under web instead off on the api.

https://github.com/flutter/website/issues/5297

**Comment by sowens-csd** [comment]
I tried a unit test for the null behaviour and I think the ?? version works. I've committed the first test, I'll build out the others now.

**Comment by sowens-csd** [comment]
I've committed those changes to switch to ?? along with unit tests for them.

**Comment by kaladron** [comment]
Thanks.  Took a longer than that should've, and I'm now setup and working
on https://github.com/kaladron/speech_to_text/tree/null-safety

I'll send a PR when I'm closer.

**Comment by kaladron** [comment]
While generated the files, I'm having a problem I don't understand:

```
Cannot populate the required constructor argument: _alternates. It is assigned to a private field.
package:speech_to_text/speech_recognition_result.dart:64:3
   ╷
64 │   SpeechRecognitionResult(this._alternates, this.finalResult);
   │   ^```

Renaming the field to be public [like so](https://github.com/kaladron/speech_to_text/commit/bd4f6cec9b9b86f1bbfd53d75ba98c6a7bbe9d56) allows it to succeed.

This doesn't seem related to null safety.  Could you please try regenerating the file with the new Flutter stable and see if it's something in my tree?

**Comment by Zeswen** [comment]
Waiting for this to update our application to Flutter 2.0!

It would be awesome to have it ASAP. Thank you for your great work :)

**Comment by Zeswen** [comment]
Waiting for this to update our application to Flutter 2.0!

It would be awesome to have it ASAP. Thank you for your great work :)

**Comment by kaladron** [comment]
Hi Zeswen (and others!), this shouldn't block your adoption of Flutter 2.  You need to temporarily disable sound null safety, however.  Take a look at my project here:

Add this line:

https://github.com/kaladron/uscis_test/blob/main/lib/main.dart#L15

and then next to your imports:

https://github.com/kaladron/uscis_test/blob/main/lib/learnscreen.dart#L24

And after that it will work.  That still allows you to have null safety for the rest of your app while you wait for this one to be updated.

Tks,
Jeff Bailey

**Comment by sowens-csd** [comment]
> While generated the files, I'm having a problem I don't understand:
> 
> ```
> Cannot populate the required constructor argument: _alternates. It is assigned to a private field.
> package:speech_to_text/speech_recognition_result.dart:64:3
>    ╷
> 64 │   SpeechRecognitionResult(this._alternates, this.finalResult);
>    │   ^```
> 
> Renaming the field to be public [like so](https://github.com/kaladron/speech_to_text/commit/bd4f6cec9b9b86f1bbfd53d75ba98c6a7bbe9d56) allows it to succeed.
> 
> This doesn't seem related to null safety.  Could you please try regenerating the file with the new Flutter stable and see if it's something in my tree?
> ```

Not your tree, I think that's a real error. Let's change it to a public so that you're not blocked. I'll revisit the design of that class in an upcoming release.

**Comment by kaladron** [comment]
Perfect, thanks.

Tests now compile and run on my branch.  A few to fix up:
00:08 +87 -22: Some tests failed.

Looks like mostly the same error, so perhaps I'm close.

**Comment by kaladron** [comment]
Sent the PR. =)  All tests are passing on it.

**Comment by kaladron** [comment]
It's not really related to this issue, but something I was wondering: Why is the interface library separate from the main one?  I couldn't see another library that depended on it.

I was thinking about it because since this is an API break, it seemed like something like a good time to change things.

**Comment by sowens-csd** [comment]
You mean the speech_to_text_platform_interface? Separating it is good practice according to the Flutter team. It allows other implementers not associated with the main project to depend on it and reimplement the plugin for a new platform. 

I'd agree this is a good time to change it as well.

**Comment by kaladron** [comment]
Is that likely?  Or would something just send you patches for, say, Windows
support here?

Having them be separate meant that there was a dep that I couldn't easily
roll because they both had to go at once.  (Can't remember which one off
hand, sorry, it's in the commit message and I'm on my phone).  Also, that I
usually like to do one final test run before I send, but the tied changes
meant that I just had to trust that I got it right.

Thanks!

**Comment by sowens-csd** [comment]
I agree that it seems unlikely but it is how the Flutter team has spec'd it. Given that the reality is that no one else is dependent on that, and certainly not on the updated version it's likely safe. 

The process, I think, should be to publish the update to the interface lib to pub.dev, then change the dependency to it and test, then if that goes well, publish the primary lib. If you let me know when the interface lib is changed I'll publish it so you can try it out. I found it a bit awkward when I was doing the initial split (as you'll see from the changelog) so I had to keep pushing updates. It's a bit messy out in the open like that, but, it works.

**Comment by kaladron** [comment]
Eh, I took some time to read the flutter/dart stuff and have been thinking
about it all day.  I can see their point: Dart is going to support ever
more platforms, and that way someone can just add module support to each
one following the interface.  So folks can rally around one interface and
then you don't have to come up with Mac/Windows/Linux/Fuchsia/whatever else
comes along.

The hassle comes with things like the PR that I'm about to send you to roll
the plugin_platform_interface where each plugin then needs to roll forward,
and also whether or not the interface is clear enough or if each platform
winds up needing to evolve it.

Ah well, I learned something more about Flutter design today. =)

**Comment by kaladron** [comment]
I think everything is set for null safety now.  Since this will be a new major version roll, it's a good time for any breaking changes.  Do you have anything you want to do?  If not, I can send a PR to CP the 1 patch on main that isn't there, and then roll the version (or you can do those if you wish)  pub.dev seems to allow uploading a newer version beside things for early access and testing if you want, since you mentioned you had another feature you wanted to get out the door first.

Let me know how I can help!

**Comment by sowens-csd** [comment]
The changes are looking really good, thanks for all the work. I don't think there's anything important enough to delay these changes. Go ahead with the final PR, then I can run some tests and do a release.

**Comment by nurassylive** [comment]
Can't wait for the null safety upgrade of package. Thanks for you job @kaladron!

**Comment by sowens-csd** [comment]
I've merged your latest PR @kaladron, is it ready for a final test / upload now?

**Comment by kaladron** [comment]
Please!  I ran the example application as part of the update, tested that
it transcribed the words.  Please do whatever your usual release testing
would be and should be good! =)

**Comment by sowens-csd** [comment]
4.0.0-nullsafety is on pub.dev now. Many thanks for taking that on @kaladron. 

I'd appreciate if anyone following this could try building your null-safe application against this new version and let me know if you have any problems.

**Comment by kaladron** [comment]
Working on my app, thank you for being so responsive with the patches!

https://github.com/kaladron/uscis_test/commit/0db372948e43e2701ee6d8960653bddcfc4642ae

This was my last barrier to sound null safety.

**Comment by sowens-csd** [comment]
@kaladron do you want to do the honours of closing this rather lengthy issue?

**Comment by kaladron** [comment]
Happily, except I don't think I have the rights to. =)

**Comment by kaladron** [comment]
And a good time was had by all.  Thanks!
