### ISSUE TITLE
Error "D/SpeechToTextPlugin( 8888): Error 9 after start at 21 1000.0 / -100.0"

### ISSUE THREAD

**Issue by hivesey** [csdcorp/speech_to_text#166]
Hi,

I am trying to use the plugin, I have written a simple example with 1 button to start listening.

Initialization of the plugin is done during initState()
void initState() {
    super.initState();
    _initSpeechState();
  }

But I am getting an error and can't figure out why listening is not working. Can you please advice?
D/SpeechToTextPlugin( 8888): Start listening
D/SpeechToTextPlugin( 8888): setupRecognizerIntent
D/SpeechToTextPlugin( 8888): Notify listening
D/SpeechToTextPlugin( 8888): Notify listening done
D/SpeechToTextPlugin( 8888): Start listening done
**D/SpeechToTextPlugin( 8888): Error 9 after start at 21 1000.0 / -100.0**
D/SpeechToTextPlugin( 8888): Stop listening
D/SpeechToTextPlugin( 8888): Notify listening
D/SpeechToTextPlugin( 8888): Notify listening done
D/SpeechToTextPlugin( 8888): Stop listening done
**D/SpeechToTextPlugin( 8888): Error 5 after start at 5052 1000.0 / -100.0**

Thanks
Arathi

**Comment by sowens-csd** [comment]
Error 9 is a permissions error. Did you follow the directions in the readme about requesting the necessary permissions in your manifest?

**Comment by hivesey** [comment]
yes, I did. I did get the popup to grant permission for the app but after
that, I am getting Error 9.

[image: image.png]

**Comment by sowens-csd** [comment]
Is this on a simulator or a real device? Have you checked the notes in the troubleshooting section on ensuring that speech is properly enabled on the device?

**Comment by hivesey** [comment]
Hi,

Sorry about the incomplete information, it's on an emulator, it's working
on the device. Let me check the troubleshooting section again and get back
to you.

Thanks for getting back to me. Regards
Arathi
