### ISSUE TITLE
Offline Support

### ISSUE THREAD

**Issue by javierpozzi** [csdcorp/speech_to_text#167]
Hi, first of all thanks for this complete and awesome package! Amazing work!

Is it possible to use the puglin with no connection? I'm testing it with no internet connection and I get an error message 'error_network'. I used to work with another plugin for Flutter that allowed it. If not, are you planning to add the functionality? Thanks.

**Comment by sowens-csd** [comment]
Thanks for the feedback, I appreciate it. Yes, if the device supports offline the plugin should. There is an `onDevice` flag in the `listen` method that requests that mode of the device. I don't think that is as well supported in Android. In Android it uses it to prefer on device but I don't think it makes it a hard requirement. In iOS when set it will only work if the device can support offline processing.

**Comment by javierpozzi** [comment]
After some testing, I found that if I remove the `localeId` argument on the `listen` method, offline speech recognition started working again, despite the use of `onDevice` flag.
