### ISSUE TITLE
Documentation for how voice data is handled? Voice recognition throttling?

### ISSUE THREAD

**Issue by awarmfastbear** [csdcorp/speech_to_text#168]
Hello,

I have 2 main questions that revolve around privacy for the voice input received, and throttling for the voice recognition work.

1 - Can you confirm what privacy policies and data usage policy applies to voice input received by this plugin on Android and iOS? When used on Android devices I believe the voice input falls somewhere within Google's privacy realm. Is it safe to assume that Google will likely keep the voice input for its own use? What about for iOS?

2 - If launching an app with this voice recognition plugin, what are the chances that many concurrent users will run cause voice recognition to fail from throttling on Android and iOS? Is most of the recognition done offline where throttling can be avoided?

2.1 - If throttling and failures occur, what can be done to mitigate throttling, would I need to fall back to a paid voice recognition service from Google Cloud for example? 

I think having more documentation for this would be great :)

**Comment by sowens-csd** [comment]
The plugin doesn't change the privacy or data usage policies for the device. In all cases it is using the speech recognition services provided by the underlying OS and is therefore subject to whatever usage or privacy limitations those services have. The plugin uses hints to try use offline processing and there is a flag on the `listen` method, `onDevice` that can be used to further shift it towards on device processing. 

If throttling is an issue then yes, you'd have to switch to a paid recognition service. I haven't personally seen much indication that either iOS or Android throttle very actively but they certainly do reserve the right to do so. 

Thanks for the suggestion on documentation. I'll add some notes to the README in a future release.
