### ISSUE TITLE
not satisfy the required version

### ISSUE THREAD

**Issue by niypoo** [csdcorp/speech_to_text#17]
I'm trying no to upgrade my flutter to 1.12 and facing this issue any idea
`FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
The following dependencies do not satisfy the required version:
project ':speech_to_text' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.0`

**Comment by sowens-csd** [comment]
So you're trying to continue to use Flutter 1.9.x? I haven't tested the 0.7.0 version of the plugin with previous versions of Flutter so I don't know if it will work. 

The error looks like I need to upgrade Kotlin to a newer version in the 0.7.x version of the plugin. Do you get that error from a `Flutter build apk` command? Have you upgraded other plugins? If you're staying on an older Flutter version you might want to also leave your plugins at their previous versions.

**Comment by niypoo** [comment]
yes I must work with` kotlin_version 1.3.5` and` build:gradle:3.3.5` and your package work with me only with kotlin_version 1.3.0 & 1.3.10
so I downgrade  tools.build:gradle to `com.android.tools.build:gradle:3.3.1`  to work  with ext.kotlin_version = '1.3.10'  for speech_to_text,

**Comment by sowens-csd** [comment]
Ah! I see now. I just tried to create a brand new project and I see that Flutter has moved the kotlin version to 1.3.5. Thanks for pointing this out. I'll upgrade the project and release a minor point upgrade.

**Comment by sowens-csd** [comment]
0.7.1 is now uploaded with a fix for this issue.
