### ISSUE TITLE
Google Listener window is not opening

### ISSUE THREAD

**Issue by khansultan1** [csdcorp/speech_to_text#172]
trying to open the google listener window but it's not available can anyone please help outreaching with this solution.
![WhatsApp Image 2021-02-17 at 4 13 33 PM](https://user-images.githubusercontent.com/6906715/108209469-66677f00-713b-11eb-9585-4a8c3f446c41.jpeg)

**Comment by sowens-csd** [comment]
I'm not sure based on what you posted that your question is related to this plugin. If it is can you provide more details? If not I'll close this issue.

**Comment by khansultan1** [comment]
based on other plugins example IONIC speech to text is using google dialog same I need in this plugin is their any way where we can show the dialog like this.

**Comment by sowens-csd** [comment]
No, the plugin has no UI and doesn't trigger any of the native Android UI other than the permission dialogs.
