### ISSUE TITLE
After phone call onResult is not getting call in android

### ISSUE THREAD

**Issue by khansultan1** [csdcorp/speech_to_text#173]
Dears,

I'm trying to start the service after a phone call the speech.listen is called but it will not go to the onResult,

Step to reproduce:

Start speech to text on any phone android (app wherever you are using this plugin),
close the app (your app where this plugin is used)
dial any phone call from your phone and talk, 
Start again the app where this plugin is installed
See the result.

**Comment by sowens-csd** [comment]
By 'close the app' do you mean put it into the background or actually close it?

**Comment by Tanelo** [comment]
Is the plugin working on android ? Because, it seems not...

**Comment by sowens-csd** [comment]
@Tanelo are you having the same problem that @khansultan1 reported or something else?

**Comment by Tanelo** [comment]
Hi @sowens-csd, i don't think so...

**Comment by sowens-csd** [comment]
I'm working with @Tanelo on a separate issue. @khansultan1 unless you have more information I'll close this.
