### ISSUE TITLE
How to use this plugin to record voice

### ISSUE THREAD

**Issue by hsiami** [csdcorp/speech_to_text#174]
I'm using this plugin for speech to text. I also want to record the voice. when I use other plugin to record voice the below message appears : 
"Google is currently recording audio. Your app not be able to record right now."
How can I record voice with your plugin or with other plugins?

**Comment by sowens-csd** [comment]
I have not found a way to share the microphone while speech recognition is active on Android. As far as I have been able to tell this is not supported.

**Comment by hsiami** [comment]
thank you
