### ISSUE TITLE
I don't get the same answers on android and ios

### ISSUE THREAD

**Issue by Ossyyrr** [csdcorp/speech_to_text#176]
Visual example:

Android:
![image](https://user-images.githubusercontent.com/52755910/109774238-6b7b0280-7c00-11eb-9120-94ec0871f2f3.png)

IOS:
![image](https://user-images.githubusercontent.com/52755910/109774267-7170e380-7c00-11eb-8143-3df716b6d9c3.png)

Is there a way to get the same responses on android and ios or more responses on ios?

Thank you!

**Comment by sowens-csd** [comment]
No. The underlying speech recognizers on the two platforms are completely different. You should not count on getting the same answers.
