### ISSUE TITLE
pauseFor not working in android and ios

### ISSUE THREAD

**Issue by srkakadiya** [csdcorp/speech_to_text#177]
I m trying to achieve when user start recognition but he is not speak anything within 5 second, speechRecognition should be stop.
I had set pausedFor duration 5 second but isn't working.

[Please check my code via this url](https://dpaste.org/20CX)

**Comment by sowens-csd** [comment]
I'm sorry, I don't have time to review external code. I did follow your link but the code is gone. Can you try it in the example app? I just tried to reproduce a problem in the example and couldn't find anything wrong. Here's the change I made to the `listen` call in the example: 

```dart
   speech.listen(
        onResult: resultListener,
        listenFor: Duration(seconds: 30),
        pauseFor: Duration(seconds: 2),
        partialResults: true,
        localeId: _currentLocaleId,
        onSoundLevelChange: soundLevelListener,
        cancelOnError: true,
        listenMode: ListenMode.confirmation);
```

**Comment by sowens-csd** [comment]
I'll leave this open for the next couple of days then close it. Please let me know if you have more details.

**Comment by srkakadiya** [comment]
Thank you for your reply, can you check my code via this latest URL :- https://dpaste.org/wVtY

I'm trying to achieve when user click on start recognition but if user wouldn't speak for 5 second recognition turn off automatically i tried your pausedFor method, but it's not work

**Comment by sowens-csd** [comment]
You have both `listenFor` and `pauseFor` set to 5 seconds, with those settings you won't be able to tell if it is working or not. Try a `listenFor` of 60 with a `pauseFor` of 2. That should be a clearer demonstration of how it works. The difference is that `listenFor` is the total time for the `listen` method regardless of whether the speaker is still talking or not, while `pauseFor` sets a maximum time it will wait with no speech.

**Comment by srkakadiya** [comment]
Thank you! It's works!!
