### ISSUE TITLE
Upgrade plugin_platform_interface

### ISSUE THREAD

**Issue by AhmedNourJamalElDin** [csdcorp/speech_to_text#179]
Hello,

I have firebase messaging 7 and this package installed.
Now I have upgraded my project to Flutter v2 and firebase messaging **9** which is a requirement for our app because firebase messaging 9 shouldn't have any use of IDFA so I can submit my kids app to Apple. but I got this issue:

> Because speech_to_text >=3.1.0 depends on speech_to_text_platform_interface ^1.4.2 and no versions of speech_to_text_platform_interface match >1.4.2 <2.0.0, speech_to_text >=3.1.0 requires speech_to_text_platform_interface 1.4.2.
And because speech_to_text_platform_interface 1.4.2 depends on plugin_platform_interface ^1.0.1, speech_to_text >=3.1.0 requires plugin_platform_interface ^1.0.1.
And because firebase_messaging >=9.0.0 depends on firebase_messaging_platform_interface ^2.0.0 which depends on plugin_platform_interface ^2.0.0, speech_to_text >=3.1.0 is incompatible with firebase_messaging >=9.0.0.

Apparently it's to upgrade plugin_platform_interface to v2.

**Comment by ycv005** [comment]
Waiting for same.

**Comment by jslattery26** [comment]
Same here.

**Comment by ZaherAirout** [comment]
Me too

**Comment by sowens-csd** [comment]
This is done now in the 4.0.0-nullsafety release on pub.dev. Please try it out and let me know if you're still having problems.
