### ISSUE TITLE
Is it possible to access the recorded mp3 file?

### ISSUE THREAD

**Issue by bietkul** [csdcorp/speech_to_text#183]
I want to use thrid party speech-to-text library but they need the mp3 recording. Does this package record the voice into a mp3 file?

**Comment by bietkul** [comment]
@sowens-csd Thanks for the response. I can understand that the voice recording happens by OS components but do you know if we can access the recorded file?

**Comment by sowens-csd** [comment]
No, if there is a file it is not available through any interface I've seen.

**Comment by bietkul** [comment]
Ok, thanks
