### ISSUE TITLE
pauseFor and listenFor are inaccurate after the first check

### ISSUE THREAD

**Issue by sowens-csd** [csdcorp/speech_to_text#191]
pauseFor and listenFor don't wait the correct time since the previous speech event when they are recalculated. The issue is that they don't take into account the duration that has already passed when recalculating to they are always longer than they should be.

**Comment by ab36245** [comment]
I've pulled the latest version and the timing certainly looks better:

```
flutter: 2021-03-24T12:52:47.144475 resultListener: final false
flutter: 2021-03-24T12:52:47.245307 resultListener: final false
flutter: 2021-03-24T12:52:51.472170 statusListener: Received listener status: notListening, listening: false
flutter: 2021-03-24T12:52:51.484843 statusListener: Received listener status: notListening, listening: false
flutter: 2021-03-24T12:52:51.629415 resultListener: final false
flutter: 2021-03-24T12:52:51.667471 resultListener: final true
flutter:   no. alternates 1
flutter:   - Can you hear me now there's a lot of traffic today (0.919)
flutter: 2021-03-24T12:52:51.668871 statusListener: Received listener status: notListening, listening: false
```

This actually shows a pause of about 4.2 seconds between the last partial notification and the first change to listening status. This was randomly between 6.5 and 8 before the pull.

My pauseFor is set to 5, so it looks about right. Actually I'm a little surprised it's _under_ 5s but I also have no idea what the sequence of processing is and when the timer gets set.

**Comment by sowens-csd** [comment]
I'm also surprised it's under 5. I'll have a look, in my experiments it was always a little bit over, which seemed right to me. I'm not so sure how it gets to be under.

**Comment by sowens-csd** [comment]
4.1.1-nullsafety is now out with these improvements. Next I'll have a look at why it is apparently less than 5s.

**Comment by ab36245** [comment]
Great, thanks

**Comment by sowens-csd** [comment]
I think this might be resolved now in the latest repo version. There was a separate delay that wasn't accounted for in the pauseFor and since that's resolved now it should also make this more accurate. In my timings it was 5 seconds. Let me know if you see anything different.
