### ISSUE TITLE
Interfaces and best practice

### ISSUE THREAD

**Issue by ab36245** [csdcorp/speech_to_text#192]
In writing a comment on #169 I realised that it's not completely clear to me whether the average user (and I consider myself very average 😄 ) should be using the older (and to my mind better documented) callback-style interface or the newer stream-based SpeechToTextProvider interface?

I currently use the older style and it's fine for me but I'm wondering if there's any plan to deprecate it now that SpeechToTextProvider exists or is the intent that they happily co-exist? The SpeechToTextProvider information is a bit difficult to find (I had to trawl the changelog to find the reference I knew was somewhere to the SpeechToTextProvider example).

Not looking to criticise, really looking for guidance to best practice and what an active user should be doing from here.

**Comment by sowens-csd** [comment]
My plan is to continue to make it easier to use `SpeechToTextProvider`. A better example and some more documentation on it will help with that. I think it will, eventually, make it simpler to use the plugin as it doesn't have quite so many up-front requirements to get value out of it. The design goal is to try to address some of the sharp edges that people were bumping into with `SpeechToText`. 

The `SpeechToText` interface remains important and will continue to get development and improvement. I think of it as the more flexible tool for people that like having complete control.

**Comment by ab36245** [comment]
That's very clear - thanks.
