### ISSUE TITLE
Android is giving error_speech_timeout when trying to initialized

### ISSUE THREAD

**Issue by fabangeloni** [csdcorp/speech_to_text#193]
I'm getting error_speech_timeout when trying to initialize the listen function,

I have the following code to initialized the lisener:
`
Future<void> initSpeechState() async {
    bool hasSpeech = await speech.initialize(
      onError: (e) {
        print("initSpeechState error " + e.toString());
      },
      onStatus: statusListener,
    );

    if (hasSpeech) {
      localeNames = await speech.locales();
      _currentLocaleId = "es-ES";
    }

    if (!mounted) return;
  }

void startListeningAndroid(BuildContext context) async {
    try {
      speech.listen(
        onResult: (SpeechRecognitionResult result) {
          processWords(result, context);
        },
        listenFor: Duration(seconds: 10),
        localeId: _currentLocaleId,
        onSoundLevelChange: soundLevelListener,
        cancelOnError: false,
        partialResults: true,
        onDevice: true,
        listenMode: ListenMode.dictation,
        pauseFor: Duration(seconds: 9),
      );
    } catch (e) {
      print(e.toString());
    }
    setState(() {});
  }

  void startListeningiOS(BuildContext context) async {
    try {
      speech.listen(
        onResult: (SpeechRecognitionResult result) {
          processWords(result, context);
        },
        localeId: _currentLocaleId,
        onSoundLevelChange: soundLevelListener,
        cancelOnError: false,
        partialResults: true,
        onDevice: true,
        listenMode: ListenMode.dictation,
      );
    } catch (e) {
      print(e.toString());
    }
    setState(() {});
  }

void statusListener(String status) {
    currentStatusSpeech = status;
    print(
        "Received listener status: $status, listening: ${speech.isListening}");
  }
`

And this is the error log I got:
`I/flutter (28578): Received listener status: listening, listening: true
I/flutter (28578): initSpeechState error SpeechRecognitionError msg: error_speech_timeout, permanent: true
I/flutter (28578): Received listener status: notListening, listening: false
I/flutter (28578): initSpeechState error SpeechRecognitionError msg: error_client, permanent: true
I/flutter (28578): Received listener status: listening, listening: true
I/flutter (28578): initSpeechState error SpeechRecognitionError msg: error_speech_timeout, permanent: true`

So as you can see, the error is happening in the initializatoin process..

This si my pubspect

`dependencies:
  flutter:
    sdk: flutter
  fluro: ^1.6.1
  google_maps_flutter: ^1.2.0
  rxdart: ^0.24.1
  auto_size_text: ^2.1.0
  location: ^3.0.2
  device_info: ^0.4.2+4
  speech_to_text: ^3.2.0
  data_connection_checker: ^0.3.4
  connectivity: ^0.4.9
  vector_math: ^2.0.8
  sqflite: ^1.3.1
  path_provider: ^1.6.11
  flutter_ringtone_player: ^2.0.0
  http: ^0.12.2
  shared_preferences: ^0.5.6
  assets_audio_player: ^2.0.9+2
  screen: ^0.0.5`

Testing on different android devices but with Android 9.

**Comment by ab36245** [comment]
I have found that it is always useful to timestamp any messages you printout. This really helps diagnosing the problem.

It is possible that the underlying Android speech recognizer is actually timing out. I have seen it timeout as soon as 1 second after starting, despite setting pauseFor.

**Comment by fabangeloni** [comment]
This is the log with the timestamp

`I/flutter ( 7815): 2021-03-25 13:41:05.711238 - Received listener status: notListening, listening: false
I/flutter ( 7815): 2021-03-25 13:41:05.723443 - initSpeechState error SpeechRecognitionError msg: error_client, permanent: true
I/flutter ( 7815): 2021-03-25 13:41:07.639092 - Received listener status: listening, listening: true
I/flutter ( 7815): 2021-03-25 13:41:07.786242 - initSpeechState error SpeechRecognitionError msg: error_speech_timeout, permanent: true
I/flutter ( 7815): 2021-03-25 13:41:16.720318 - Received listener status: notListening, listening: false
I/flutter ( 7815): 2021-03-25 13:41:16.728152 - initSpeechState error SpeechRecognitionError msg: error_client, permanent: true
I/flutter ( 7815): 2021-03-25 13:41:18.618380 - Received listener status: listening, listening: true
I/flutter ( 7815): 2021-03-25 13:41:18.710692 - initSpeechState error SpeechRecognitionError msg: error_speech_timeout, permanent: true`

So why could be the reason why android speech recognition is timing out?

**Comment by sowens-csd** [comment]
Could you try running it with the `debugLogging` set to true on the `initialize` call. It seems likely to me that based on the `error_client` that shows in the log that the device you're trying to use doesn't have speech recognition properly enabled on it. Did you have a look at the Android troubleshooting section in the README?

**Comment by dnsprado** [comment]
Hi guys. I have exact same problem when I set "onDevice" to true. I am using localeId = 'pt_BR' (Brasil). Any clues on what may be causing this?
