### ISSUE TITLE
Disable automatic stop()

### ISSUE THREAD

**Issue by shivampednekar-baxture** [csdcorp/speech_to_text#201]
is there any way to disable automatic stop() method. Because speech take long time to stop in IOS, works fine in android.
currently i am invoking stop() method with respect to sound level changes.

**Comment by Rashid-Khabeer** [comment]
Hello Shivam, I am facing an issue where as soon as you stop speaking the speech to text status changes to notListening and does not recognize words anymore. In the newer version they have added a timeout parameter but that too does not seem to be working to me, I gave a duration of 15 minutes still it stopped as soon as I stopped talking. I want to know how you have done this on your end. It would be great if you share a code snippet.

Thanks

**Comment by sowens-csd** [comment]
Can you describe what your goal is? What stop do you want to disable? There are two types of stop that could be considered automatic. The first is from the OS itself when it times out or detects a pause. The second is if you are using either the `pauseFor` or `listenFor` parameters on the `listen` method to set a defined duration. 

If speech is taking too long to stop on iOS you can use the `pauseFor` method to stop it after a pause in hearing new words being spoken. But that doesn't sound like what you want if you want to disable the automatic stop.

**Comment by shivampednekar-baxture** [comment]
I think stop() method gives the finalResult of the recognized words. In ios it takes long time to stop more than 30sec which is intimidating. I want to stop it as soon as I stop speaking. I am able to achieve it by invoking stop() inside soundlevelChange with respect to changes in sound level but sometimes it stops automatically (may be it is that automatic stop which is invoked automatically and takes long time to stop in IOS) which causes problem in getting final result. I have not tried pauseFor will it work in this scenario to stop it just like it stops in android without any problem??


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by shivampednekar-baxture** [comment]
Did you use listenFor??


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by sowens-csd** [comment]
So it is taking more than 30 seconds after you call the `stop` method to get the final results? That should not happen. The expected wait is less than a second. If it is behaving like that it is a surprise to me. If you use the example app do you see the same behaviour? 

Which version of the speech_to_text plugin are you using? What is the iOS version and on which device?

**Comment by shivampednekar-baxture** [comment]
No It is not taking more than 30 sec to get final result after the stop() which I m invoking with respect to sound level changes  but after 30 or n seconds stop() which was supposed to invoke automatically gets invoked which gives me final result multiple times. However the pauseFor has worked for me in IOS.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by sowens-csd** [comment]
I just released a new 4.1.1-nullsafety version that has significant improvements to both `pauseFor` and `listenFor`. If you have time please give it a try and let me know if it addresses the issue.

**Comment by happyUser28** [comment]
> Can you describe what your goal is? What stop do you want to disable? There are two types of stop that could be considered automatic. The first is from the OS itself when it times out or detects a pause. The second is if you are using either the `pauseFor` or `listenFor` parameters on the `listen` method to set a defined duration.
> 
> If speech is taking too long to stop on iOS you can use the `pauseFor` method to stop it after a pause in hearing new words being spoken. But that doesn't sound like what you want if you want to disable the automatic stop.

Hi!
I have exactly same problem as Rashid-Khabeer. In android, I want my speech recognition continue until stop() called even if I don't speak. But It stops in 2 seconds after I stop talking. I tried FinalTimeOut and changed default 2 second time to 5 second but nothing changed.

**Comment by sowens-csd** [comment]
Timeout for speech on Android differs by device and by Android version. It is often very short and I haven't yet seen a device where it is longer than 5 seconds. Unfortunately there appears to be no way to change that behaviour. 

I'm going to close this thread because I think the issues raised here have either been addressed now or would be better in a separate issue. If you're still having problems with something raised in this issue please create a new issue with a description of the problem.

**Comment by R4dix** [comment]
Has anyone solved this for Android? The pauseFor is not working on Android.
