### ISSUE TITLE
Is there any way or trick to make this package works like vosk/kaldi

### ISSUE THREAD

**Issue by danielseow-simplify** [csdcorp/speech_to_text#204]
I tried to implement vosk api with pretrained kaldi model on Android and it works on Android, but a small model is not available in the language I need.
However, this flutter speech to text package works perfectly in the language I want, but the con is that it can't listen continuously in the background like vosk/kaldi. Is there a way to do that like vosk/kaldi?

**Comment by dangoran** [comment]
I'm a rookie so this may not be a correct answer to your question, but I would like the same thing. I am currently using the background_stt package for continous listening. It works pretty good, but has it's drawbacks. Android only being the biggest one. Also, you can't choose the language but it seems to listen to the languages you have set up in your google app, english always included even if you have set up your own language. Listening to more languages at once makes it less accurate.

It would be great if you could get this package to listen to contiuous commands. Even if it was in short bursts (like listen for 20 seconds again after a completed listen result). I have tried to get this package to restart listening to recieve voice commands. Seemed to almost get it to work for my purpose, but after i while I just get a timeout error message. The readme section does mention "speech recognition limits".

**Comment by sowens-csd** [comment]
That vosk/kaldi speech engine looks interesting. Unlike that engine the speech_to_text plugin uses the speech recognition system built into Android or iOS and that limits the flexibility to what is supported by the OS. Currently neither Android nor iOS are designed for continuous recognition. I do plan on improving the ability to keep the recognizer alive but it will never be a continuous system because the OS limits the duration of a single speech event.

**Comment by sowens-csd** [comment]
I'm going to close this issue since I'm tracking the continuous listening under another issue and I think I've answered this one.

**Comment by roablep** [comment]
Which issue is this discussed under? Could you link to it? Is it https://github.com/csdcorp/speech_to_text/issues/253?
