### ISSUE TITLE
Disabling on and off sounds

### ISSUE THREAD

**Issue by nurassylive** [csdcorp/speech_to_text#206]
How can I disable on-sound and off-sound in ios if phone is in vibrate mode?

**Comment by sowens-csd** [comment]
Currently you can't, you can either have the sounds or not. Sounds like a good feature though.

**Comment by sowens-csd** [comment]
Looked at doing this automatically based on detection of the phone state but doesn't look like that's a good route. Trying to avoid adding a new option to the platform interface.

**Comment by tohosys** [comment]
whenever listener timeout after about 5 seconds, i restart speech.listen() again and again to detect voice forever. 
how can i mute the beep sounds for timeout error-beep and speech.listen-beep?

**Comment by mikron123** [comment]
> Currently you can't, you can either have the sounds or not. Sounds like a good feature though.

How can you disable the sounds completely from the start?

**Comment by sowens-csd** [comment]
For iOS there is no sound unless you put correctly named assets into your app. On Android you can't disable the sound.
