### ISSUE TITLE
delay while initializing listen in IOS

### ISSUE THREAD

**Issue by shivampednekar-baxture** [csdcorp/speech_to_text#207]
there is a delay of split seconds in IOS when we start listening how can that be handled and sometimes pauseFor doesnt work properly in IOS

**Comment by sowens-csd** [comment]
Can you try `pauseFor` in the latest version and see if it has resolved the issue? Are you playing an initialization sound on iOS? That can cause a delay.

**Comment by sowens-csd** [comment]
I've just committed a change that significantly speeds up iOS listen start. It may cause a problem if the input device changes during use. For example if you went from the internal mike to a headset. This requires further testing. If you have a chance to try it please let me know.

**Comment by sowens-csd** [comment]
This change is now available in 4.2.0
