### ISSUE TITLE
Simultaneous Audio Recording and Speech to Text conversion

### ISSUE THREAD

**Issue by Darshan-Dhanke** [csdcorp/speech_to_text#208]
Is it possible to pass an audio stream or audio file to speech_to_text to output.

I have been using speech_to_text conversion and audio recorder package https://pub.dev/packages/flutter_sound

Is it anyhow possible to get the speech_to_text to listen to a stream which will listen the mic input ?
It will help to record and stt convert simultaneously, I'm trying this on Android device and so far have manage to either record or stt separately.
We could use a stream provider packages similar to https://pub.dev/packages/sound_stream .
Open for suggestions if anyone knows a better way.
Thank you.

**Comment by sowens-csd** [comment]
Unfortunately no. The short answer is that it may be possible on iOS but doesn't seem to be on Android. This has been a fairly frequent question and there's another active thread on it here #205. Probably best to add to move this discussion over to that issue.
