### ISSUE TITLE
Error 7 before listenFor duration ends

### ISSUE THREAD

**Issue by maddionatoplus** [csdcorp/speech_to_text#212]
Good morning,
I have implemented your library but when I use it I always receive the errors 7 before the end of the duration:

Implementation:

```
var hasSpeech = await speech.initialize(
      onError: errorListener,
      onStatus: statusListener,
      debugLogging: true,
      finalTimeout: Duration(milliseconds: 0),
    );
...
speech.listen(
          onResult: resultListener,
          listenFor: Duration(seconds: 5),
          pauseFor: Duration(seconds: 5),
          partialResults: true,
          localeId: _currentLocaleId,
          cancelOnError: false,
          listenMode: ListenMode.confirmation);
```

Errors:
```
D/SpeechToTextPlugin(32614): Error 7 after start at 2489 -2.0 / 7.24
I/flutter (32614): Received error status: SpeechRecognitionError msg: error_speech_timeout, permanent: true, listening: false
```

Thanks in advance if you can help me!

**Comment by sowens-csd** [comment]
Is this on an Android or iOS device, emulator of physical? Have you read the sections in the README about setting up speech on various Android devices?

**Comment by maddionatoplus** [comment]
Hello,
It's an Android phyisical device (Samsung Galaxy S20). 
I've read the section and I have not found relation with my problem. The service works but sometime it stops, showing that error, before the 5 seconds I've set in the listenFor.

**Comment by hitek-swych** [comment]
I got same problem.
Bellow is my logs.

I/flutter (20033): core onAudioFocusChanged
D/SpeechToTextPlugin(20033): Error 7 after start at 5139 -2.0 / -2.0
I/flutter (20033): Received error status: SpeechRecognitionError msg: error_speech_timeout, permanent: true, listening: false



I think "Error 7" is error code
This is post relative to this issue
https://stackoverflow.com/questions/31071650/speechrecognizer-throws-onerror-on-the-first-listening

I'm finding a solution
Now I guess SpeechRecognizer library have limited if user use it frequently

**Comment by maddionatoplus** [comment]
Thank you for the answer. Yes I knew that you can't use it for a long time. 
I need it with this cycle: 5 seconds active and then pause (which could have a duration between 1s and +inf).
I init a new speech at every cycle.

Have you found a solution that could make it stable?

**Comment by hitek-swych** [comment]
No, I haven't. 
I think we should review native source code first..

About iOS, are you get same problem?

**Comment by maddionatoplus** [comment]
I haven't tried on iOS. Let's keep in touch about progress!

**Comment by sowens-csd** [comment]
Error 7 is, according to the Android docs "No recognition result matched.". Have you tried testing it with a headset plugged into the device instead of using the device microphone? I've found that sometimes background noise is being heard by the device. If the recognizer decides that enough sound is not recognizable as words it effectively gives up with an error 7.

**Comment by maddionatoplus** [comment]
Thank you for your answer. Ok I'll try. But I'll need to use it without headset

**Comment by sowens-csd** [comment]
Any updates on this issue?
