### ISSUE TITLE
Partial results not working on Web platform

### ISSUE THREAD

**Issue by doctor-g** [csdcorp/speech_to_text#214]
Using either version 3.2.0 or 4.1.1-nullsafety, partial results do not work on the Web, or at least on the latest Chrome. When calling `listen` with `partialResults: true`, the result listener is never called.

**Comment by sowens-csd** [comment]
Thanks for the report. I'll try to reproduce and then hopefully fix, assuming Chrome can return partial results. If not I'll document it.

**Comment by sowens-csd** [comment]
I just tried this on my example app and it appears to be working. My chrome is Mac 90.0.4430.212 (Official Build) (x86_64). Can you try it with the repo version in case I've fixed something inadvertently in the current code.

**Comment by doctor-g** [comment]
Looking back at this since my original post, I'm afraid I cannot reproduce it either. It is not clear if something was wrong locally or if there was a Chrome update under the hood that changed something. Sorry for the trouble.
