### ISSUE TITLE
Disable audio sounds

### ISSUE THREAD

**Issue by FadiChaalab** [csdcorp/speech_to_text#215]
Am implement speech to text in background and i don't the user to keep listen for that sound. 
The question is how to disable them

**Comment by sowens-csd** [comment]
For Android it cannot currently be disabled, it is built into the OS. iOS has no sounds unless you provide them.

**Comment by FadiChaalab** [comment]
Can the sound volume reduce it at least?
What i mean is there way to reduce the volume of the sound without reducing it from the phone
