### ISSUE TITLE
I need to receive more responses on ios.

### ISSUE THREAD

**Issue by Ossyyrr** [csdcorp/speech_to_text#216]
Going back to this old problem:

https://github.com/csdcorp/speech_to_text/issues/139

in android I now get an array of 10 elements, which is fine.
In ios, very few items usually arrive and very usually only one arrives.
Could you change it so that at least 10 would arrive? 
Thanks.

**Comment by sowens-csd** [comment]
I think I'm returning all results that the OS produces. The plugin doesn't control the number of recognized results, that's up to the iOS or Android speech recognition subsystems. Why do you need a particular number of results?

**Comment by Ossyyrr** [comment]
We are developing a language learning app.
The user listens to a word and can then use this plugin to check if its pronunciation is correct.
In some cases, the word that the user tries to pronounce does not arrive.
for example: when trying to say "alright" I only receive "all right",  the application does not consider it valid.
If the array received alright, all right, etc. I look for the match and I consider it valid.
This system has worked fine for me on android, but on ios I have this problem.

**Comment by sowens-csd** [comment]
That's an interesting sounding app, I like the idea. Have you tried the various `ListenMode` options on the `listen` method? I'm wondering if some of the other modes might return more results.

**Comment by Ossyyrr** [comment]
Yes, I have tried everything.

**Comment by Ossyyrr** [comment]
Good morning, is there any progress?
I have kept doing tests and have looked at the package code in IOS but have not found any results at the moment.
the arrays that it returns are sometimes long and sometimes very short and it depends on the device where you perform the test, being always the same in the same device.
I am waiting for a possible solution. 
Thanks you.

**Comment by sowens-csd** [comment]
I don't think there's anything that the plugin can do to help with this issue. The OS level speech recognition provides different results for reasons that we don't seem to have any control over.
