### ISSUE TITLE
How can I mute beep sounds

### ISSUE THREAD

**Issue by tohosys** [csdcorp/speech_to_text#219]
Whenever timeout of speech-listener about 5 seconds after starting, I restart speech.listen() again and again to detect voice forever without button touch.
Working well but the timeout error-beep sound and speech.listen-beep sound are very annoying.
Could you please give me how can I mute these beep sounds?
Thanks.

**Comment by sowens-csd** [comment]
Your probably already know this but on iOS the beep sound are optional as they only happen if you put the sound files in your assets folder. On Android they are controlled by the OS and I have not found a reliable way to disable them yet.
