### ISSUE TITLE
Support for Indian Languages

### ISSUE THREAD

**Issue by infiniteoverflow** [csdcorp/speech_to_text#220]
I was currently using this package in one of my projects and i came across a situation where i was not able to use this package for local Indian languages.
Is there any way the package can extend its supported locales to certain specific Indian languages. To name a few Kannada, Marathi, Malayalam.

**Comment by sowens-csd** [comment]
The plugin should support any language that is supported by the underlying OS. Some languages do require separate setup steps on the device. If any of those languages are supported on Android or iOS and not in the plugin let me know. 

Unfortunately if they're not supported by the OS then you'll have to wait for either iOS or Android to provide support.

**Comment by infiniteoverflow** [comment]
Yes , the Indian languages Kannada, Marathi, Malayalam are supported by the OS, but unfortunately, it's not a part of the plugin. Can we do anything about that?

**Comment by sowens-csd** [comment]
If they're supported by the OS then all you should need is the language code and to pass it to the `listen` method in the `localeId` parameter. Are you saying that you've tried that and it doesn't work?

**Comment by infiniteoverflow** [comment]
sorry for the late reply.
Yes, i tried passing the Language code (kn-IN and mr-IN). The package returned an exception for the same.

**Comment by infiniteoverflow** [comment]
No , they dont.

**Comment by sowens-csd** [comment]
If those languages are not in the `locales` property then they are not supported for speech recognition on that device. You'll have to look at iOS instructions on how to install new languages for speech recognition.
