### ISSUE TITLE
ResultListener not called only on specific device

### ISSUE THREAD

**Issue by maddionatoplus** [csdcorp/speech_to_text#222]
I've tried 4 different devices and I am able to get speech recognition.
When I try on Samsung Galaxy A20e (2019) (SM a2020f - Android 10) it starts speech recognition correctly but it never calls my resultListener function, even if I can see this log:
```
D/SpeechToTextPlugin(16903): rmsDB -2.0 / -2.0
D/SpeechToTextPlugin(16903): rmsDB -2.0 / 3.7599998
D/SpeechToTextPlugin(16903): rmsDB -2.0 / 10.0
D/SpeechToTextPlugin(16903): rmsDB -2.0 / 10.0
D/SpeechToTextPlugin(16903): rmsDB -2.0 / 10.0
D/SpeechToTextPlugin(16903): rmsDB -2.0 / 10.0
D/SpeechToTextPlugin(16903): rmsDB -2.0 / 10.0
D/SpeechToTextPlugin(16903): rmsDB -2.0 / 10.0
D/SpeechToTextPlugin(16903): rmsDB -2.0 / 10.0
D/SpeechToTextPlugin(16903): rmsDB -2.0 / 10.0
D/SpeechToTextPlugin(16903): rmsDB -2.0 / 10.0
D/SpeechToTextPlugin(16903): rmsDB -2.0 / 10.0
D/SpeechToTextPlugin(16903): rmsDB -2.0 / 10.0
D/SpeechToTextPlugin(16903): Calling results callback
D/SpeechToTextPlugin(16903): Calling results callback
D/SpeechToTextPlugin(16903): Stop listening
D/SpeechToTextPlugin(16903): Notify listening
D/SpeechToTextPlugin(16903): Notify listening done
D/SpeechToTextPlugin(16903): Stop listening done
```

resultListener() is never called and I don't have any errors on the errorListener 

this is how I activate speech:

```
speech.listen(
          onResult: resultListener,
          listenFor: Duration(seconds: 2),
          pauseFor: Duration(seconds: 2),
          partialResults: false,
          localeId: _currentLocaleId,
          onSoundLevelChange: soundLevelListener,
          cancelOnError: true,
          listenMode: ListenMode.confirmation);
```
If I try with partialResults at true it works with partial results but not with the final results (that I need).

**Comment by maddionatoplus** [comment]
I have problem on iOS too, in this case it doesn't work at all:

```
[Utility] +[AFAggregator logDictationFailedWithError:] Error Domain=EARErrorDomain Code=3 "Recognition was unsucessful" UserInfo={NSLocalizedDescription=Recognition was unsucessful}
[plugin] FinishedReadingAudio with error: Optional(Error Domain=EARErrorDomain Code=3 "Recognition was unsucessful" UserInfo={NSLocalizedDescription=Recognition was unsucessful})
[plugin] Finished reading audio
[plugin] invokeFlutter notifyStatus
[plugin] FinishSuccessfully with error: Optional(Error Domain=EARErrorDomain Code=3 "Recognition was unsucessful" UserInfo={NSLocalizedDescription=Recognition was unsucessful})
[plugin] FinishSuccessfully
[plugin] invokeFlutter notifyStatus
flutter: Received listener status: notListening, listening: false
flutter: Received listener status: notListening, listening: false
flutter: Received listener status: notListening, listening: false
```

**Comment by sowens-csd** [comment]
Thanks for the report. Which version of the plugin are you using? 

My first thought is that those are odd `listenFor` and `pauseFor` settings. On Android, which already has a very short pause settings those values are less useful. You can keep the 2 seconds if you want a short pause, but change the `listenFor` to more like 10 or even 30 seconds. 

It's very odd that you are getting partial results but not final. What's your `initialize` statement look like? I'm wondering if you have the `finalTimeout` disabled intentionally. If not that should give you a final result even if the OS doesn't generate one. However, I added that for iOS, I've never seen Android not give a final result.

**Comment by maddionatoplus** [comment]
Thank you for your answer I use listenFor 2 seconds because I need a short command.

Here is my init:

`await speech.initialize(
      onError: errorListener,
      onStatus: statusListener,
      debugLogging: true,
      finalTimeout: Duration(milliseconds: 0),
    );`

what I should put as finalTimeout?

**Comment by maddionatoplus** [comment]
on iOS I receive this after results:

AVAudioSession_iOS.mm:1149  Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.

**Comment by sowens-csd** [comment]
Try a duration of 500 ms to start with. It should work, but really shouldn't be necessary on Android. 

Thanks for the iOS report. Which version of the plugin are you using?

**Comment by maddionatoplus** [comment]
speech_to_text: ^3.2.0
I've found what creates the problem on iOS: the problem is when I play an audio before (I need it for Android)

 ```
AssetsAudioPlayer.newPlayer().open(
      Audio(Constants.START_LISTENING_FILENAME),
      autoStart: true,
      showNotification: false,
    );
``` 

when I comment this I don't have the bug on iOS

**Comment by sowens-csd** [comment]
Is there a close operation you can perform on the player? I'm thinking that player is leaving the audio device open causing the issue with speech recognition.

**Comment by maddionatoplus** [comment]
ok if I await the audio player it works. In Android it is not necessary and so the app works faster.

Thank you for your collaboration!
