### ISSUE TITLE
Does pauseFor work for Android?

### ISSUE THREAD

**Issue by TunsAdrian** [csdcorp/speech_to_text#227]
Hello there.
I wanted to ask if pauseFor does work for Android or no workaround was yet found, regarding the platform limitations. And if it does, is there any such example? (I tried the multi-platform example on two physical devices and one emulator, but it ended after about 2 seconds, although I had it set to 10).  Also, I was using speech_to_text v3.2.0.

**Comment by sowens-csd** [comment]
pauseFor does not override Android's timeout. I still have not found a reliable way to do that.

**Comment by TunsAdrian** [comment]
Ok, thank you. I will also close the issue
