### ISSUE TITLE
Not working in second screen

### ISSUE THREAD

**Issue by HamadBangash353** [csdcorp/speech_to_text#228]
I have initialized it on first screen where it work good but in second screen it is not working. onstaus method is not called why.

**Comment by sowens-csd** [comment]
The `initialize` method is meant to be called once per application. You can't currently reset the `onStatus` method. Maybe you're trying to re-initialize on the second screen? You might want to look at the `SpeechToTextProvider` which supports the `Provider` method of sharing instances and notifying of changes.
