### ISSUE TITLE
Problems with Homophones (words pronounced the same way but spelled differently)

### ISSUE THREAD

**Issue by sylvainjack** [csdcorp/speech_to_text#234]
I am using your package for a language app and am facing a problem with "homophones', meaning words that are pronounced the same way but spelled differently. For example in French : the words "seau" and "sot" are pronounced exactly the same way. In English, we could give "flour" & "flower". Is it possible to get the list of "homophones" instead of just "one of them". It's for example impossible de get the word "seau" in French no matter how many times you repeat it.

**Comment by sowens-csd** [comment]
Unfortunately I can't control the results from the recognizer. The actual recognition is being done by the platform specific speech recognizers which are made by the platform producers. So on iOS that would be the underlying iOS speech recognition subsystem, etc. If the speech recognition is not sufficiently accurate from the platform then there's nothing I can do. 

However, I'm surprised that you aren't getting a list of homophones with an accuracy estimate in the results. Are you speaking single words or phrases? Which OS and device is this on? I'd like to try to reproduce your results to see if I can coax the recognizer to give up a list. In cases like this I think it should.

**Comment by sylvainjack** [comment]
Thanks for your answer :) 
I am using a samsung A21S to create the app. Do not have a mac so can't test yet on IOS devices. 
I managed to get the "un seau" to be recognised by adding the article "un". If there is no article, it understands "so". But couldn't get "un sot" which sounds the same. Similarly, I can't get "flour", I always get "flower". 

Here is the code I use : 
void startListening2() {
    lastWords = '';
    lastError = '';
    speech.listen(
        onResult: resultListener2,
        listenFor: Duration(seconds: 5),
        pauseFor: Duration(seconds: 5),
        partialResults: true,
        localeId: _currentLocaleId,
        onSoundLevelChange: soundLevelListener,
        cancelOnError: true,
        listenMode: ListenMode.confirmation);
    notifyListeners();
  }

void resultListener2(SpeechRecognitionResult result) {
    lastWords = '${result.recognizedWords}';
    double confidence = result.confidence * 100;
    print(lastWords);
    print('Voici la qualité de la prononciation en pourcentage : $confidence%');
    setSearchList(lastWords.toLowerCase());
    notifyListeners();
  }

**Comment by sylvainjack** [comment]
Just encountered the same problem with "la mer" (the sea) and "la mère" (the mother) which sound alike.

**Comment by sylvainjack** [comment]
Could this be solved using the result.alternates ?

**Comment by sylvainjack** [comment]
I managed to solve this problem using the result.alternates. Sorry to have bothered you :)

**Comment by sowens-csd** [comment]
Oh, that's great news, thanks for posting to help others.
