### ISSUE TITLE
speech to text no working on Android 10 (Redmi Note 7-Emulators) with LongPressUp gesture.

### ISSUE THREAD

**Issue by juanp88** [csdcorp/speech_to_text#238]
Hi, I've been working with the plugin for a while and so far it has worked great on the emulator but when I tried my  app in my Redmi Note 7 the voice doesn't get recognize. 
 device: Redmi Note 7
OS: MIUI 12.0.1
Android: 10 

I have already checked:

- both the app and Google app have microphone permissions.
- Manifest file has this permissions: 
```
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.RECORD_AUDIO"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>

    <queries>
        <intent>
         <action android:name="android.speech.RecognitionService" />
        </intent>
    </queries>
```
-  the microphone of the phone works with any other app.
-  the speech recognition works fine when tested in the emulator.
-  I don't get any error only this:

> I/flutter (15535): listening
> I/flutter (15535): notListening
> W/ActivityThread(15535): SCHED: com.example.flutter_integration.host/.MainActivity [83, r=6653ms, a=1349ms, w=82474ms]
> W/RenderInspector(15535): DequeueBuffer time out on com.example.flutter_integration.host/com.example.flutter_integration.host.MainActivity, count=3, avg=22 ms, max=31 ms.
> W/RenderInspector(15535): QueueBuffer time out on com.example.flutter_integration.host/com.example.flutter_integration.host.MainActivity, count=2, avg=22 ms, max=22 ms.
> W/ActivityThread(15535): SCHED: com.example.flutter_integration.host/.MainActivity [68, r=157ms, a=72ms, w=1858ms]
> W/RenderInspector(15535): DequeueBuffer time out on com.example.flutter_integration.host/com.example.flutter_integration.host.MainActivity, count=4, avg=21 ms, max=51 ms.

**Comment by sowens-csd** [comment]
Could you try it with `debugLogging: true` on the `initialize` call? It might give some more details. 

Also, some Android devices don't use the default speech recognition activity. I added an option `SpeechConfigOption` to allow the first recognizer to be used where the default doesn't work. You can try that out by adding the `androidIntentLookup` to the `options` list given in the `initialize` call.

**Comment by juanp88** [comment]
Hi, I tried with androidIntentLookup option like this, but it doesn't seem to work. Also tried with a different emulator a pixel 4 with android 10 with the same result.

```
 Future<void> initSpeechState() async {
    bool hasSpeech = await stt.initialize(
        onError: errorListener,
        onStatus: statusListener,
        debugLogging: true,
        options: [SpeechToText.androidIntentLookup]);
    if (hasSpeech) {
      _localeNames = await stt.locales();

      var systemLocale = await stt.systemLocale();
      _currentLocaleId = systemLocale.localeId;
    }
    if (!mounted) return;
    setState(() {
      _hasSpeech = hasSpeech;
    });
  }
```


![image](https://user-images.githubusercontent.com/23729744/124611673-46f59800-de37-11eb-9387-ad5700e38602.png)

**Comment by juanp88** [comment]
-------  Update ------------
```
The behaviour intended is to start listening on longPress and stop listening on longPressUp, the code below works with android 11 but not in 10
onLongPress: !_hasSpeech || stt.isListening
                                      ? null
                                      : () {
                                          setState(() {
                                            startListening();
                                            widgetDinamico = 'ondas';
                                            _animateGreeting();

                                            inverseOpacity = 1.0;
                                            micButtonColor = Colors.amber[400];
                                          });
                                        },
                                  onLongPressUp: stt.isListening
                                      ? () {
                                          stopListening();
                                          setState(() {
                                            inverseOpacity = 0.0;
                                            micButtonColor = Colors.white;
                                          });
                                          setState(() {});
                                        }
```
I started trying things and realize that if I delete the stopListening line from the onLongPressUp it would work in both OS. It's very odd and I don't know if it has something to do with the plugin or the way Android manages those gestures.

```
onLongPress: !_hasSpeech || stt.isListening
                                      ? null
                                      : () {
                                          setState(() {
                                            startListening();
                                            widgetDinamico = 'ondas';
                                            _animateGreeting();

                                            inverseOpacity = 1.0;
                                            micButtonColor = Colors.amber[400];
                                          });
                                        },
                                  onLongPressUp: stt.isListening
                                      ? () {                                         
                                          setState(() {
                                            inverseOpacity = 0.0;
                                            micButtonColor = Colors.white;
                                          });
                                          setState(() {});
                                        }
```

**Comment by sowens-csd** [comment]
Thanks for the follow-up. I'd agree that this likely isn't related to the plugin.
