### ISSUE TITLE
Black screen on open mic dialouge

### ISSUE THREAD

**Issue by srkakadiya** [csdcorp/speech_to_text#240]
I opened a mic dialogue for speech to text.

There is too slow to set recognizer after I give permission of microphone and my mic dialogue appears after 1 or 2 minutes(There is no timer).
And then when I am trying to speak, the main screen goes away and a black screen appears behind my mic dialogue.

Please response to my issue as soon as possible.

Here's a link of screenshot
[https://ibb.co/KNypNyf](url)

**Comment by sowens-csd** [comment]
Sorry, there's not enough detail here for me to help you. From what you've described above it sounds more like a Flutter issue than an issue with the plugin. Have you tried the example app that comes with the plugin? If that's working then the issues are more likely with your use of the plugin. 

If you are having issues with the plugin a code sample, device type and a complete description of how to reproduce the issue would be useful.

**Comment by sowens-csd** [comment]
Is there more detail on this? If not I'll close it.
