### ISSUE TITLE
Can this plugin do offline voice recognition? 

### ISSUE THREAD

**Issue by kudah99** [csdcorp/speech_to_text#243]

**Comment by sowens-csd** [comment]
Sort of, but limited by the capability of the particular OS / device. There is an `onDevice` parameter on the `listen` method that can be used to indicate that recognition should be done locally. On iOS I believe that it will work when offline if the device is capable. You'd have to look at particular iOS devices to see which support it. I am less certain on Android. There it is used to indicate a preference for local recognition. I'm betting that it is up to the particular device how they implement that.

**Comment by sowens-csd** [comment]
Closing this issue as I think it is answered.
