### ISSUE TITLE
how to add my preferred language to device, even though it's not supported by underlying OS

### ISSUE THREAD

**Issue by macavity-zero** [csdcorp/speech_to_text#244]
hey! first things first i have to say, this is very good and well-maintained package, thanks.

my application is supposed to function via non-English language instructions, since most of devices only support English for speech recognition, i must make sure that my application is working fine on all devices. my question is:
is there any way to add/install my preferred language model to target device via your plugin or flutter itself?

**Comment by sowens-csd** [comment]
Thanks for the positive feedback. 

Unfortunately no, you can select any of the installed languages in the plugin, but you can't install one. My thought would be to test for the language you want using the `locales` property, if it's not available then you'll need to provide instructions to your users on how to install new language packs on their device. Usually people will already have their preferred language installed on their device but of course not always. New language installation isn't available as far as I can tell even at the OS level via Swift or Android so it can't be done from the plugin or from Flutter.

**Comment by macavity-zero** [comment]
okay then, i will tell users to configure it manually.
thanks for your fast response.
