### ISSUE TITLE
Getting "Speech recognition unavailable"

### ISSUE THREAD

**Issue by kpamansoor** [csdcorp/speech_to_text#25]
Phone mi note 4
OS : Android 7
Other app can able to use speech to text and voice typing

**Comment by sowens-csd** [comment]
That OS version should be supported. Is this from the example app in the plugin or somewhere else?

**Comment by kpamansoor** [comment]
This is from the sample code provided by the plugin. OS supporting this feature(already did an android native app using this feature and working)

**Comment by sowens-csd** [comment]
Before I get into more complicated troubleshooting could you check the permissions for me? It would be under settings | apps | speech_to_text_example, or maybe security | app permissions | microphone? It depends on the Android version. The speech_to_text_example app must have the microphone permission granted to it. 

If that is granted then I'll have to create a build that gives more detailed information on initialization failures.

**Comment by sowens-csd** [comment]
I just tested on an Android 6 device and it worked so I'm pretty confident I haven't accidentally introduced a major version incompatibility. I'm hoping that it's just a permission issue.

**Comment by sowens-csd** [comment]
Any update on this? I'm hoping that my suggestion about the permission issue has resolved it. If I don't hear back tomorrow I'll close this.
