### ISSUE TITLE
error_speech_timeout

### ISSUE THREAD

**Issue by SEZARD** [csdcorp/speech_to_text#251]
Hi
I have a problem with this error appearing error_speech_timeout
Also sometimes when you start recording this error does not appear but it does not record anything

**Comment by sowens-csd** [comment]
Have you read through the troubleshooting section of the README? Usually timeout issues and lack of recognition have more to do with the particular device than it does with the plugin. Can you reproduce the issue with the sample app? Have you tried using a different device or possibly using a plugged in headset instead the on-device microphone?
