### ISSUE TITLE
Having problem building the speach_to_text_example using Android Studio Arctic Fox | 2020.3.1

### ISSUE THREAD

**Issue by allendrew** [csdcorp/speech_to_text#254]
I am getting the below error (in double quotes below) during a flutter app run using Android Studio Arctic Fox | 2020.3.1

I have the 'speech_to_text' in the program main.dart import as import 'package:speech_to_text/speech_to_text.dart' as stt;
and it is listed in the pubspec.yaml as "speech_to_text: ^5.0.0"

I have done a flutter pub get speech_to_text to make sure the yaml file was updated.

Please help! 

"Xcode's output:
↳
/Users/ethanberry/dev/flutter_voice/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'speech_to_text' not found @import speech_to_text;"

The full error message is below in brackets [].

[Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running pod install...
Running Xcode build...
Xcode build done. 12.2s
Failed to build iOS app
Error output from Xcode build:
↳
objc[7295]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1f9f83ad8) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1166082b8). One of the two will be used. Which one is undefined.
objc[7295]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x1f9f83b28) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x116608308). One of the two will be used. Which one is undefined.
** BUILD FAILED **

Xcode's output:
↳
/Users/ethanberry/dev/flutter_voice/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'speech_to_text' not found @import speech_to_text;
~~~~~~~^~~~~~~~~~~~~~
1 error generated.
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Analyzing workspace
note: Constructing build description
note: Build preparation complete
/Users/ethanberry/dev/flutter_voice/ios/Runner.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99. (in target 'Runner' from project 'Runner')
warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the Runner editor. (in target 'Runner' from project 'Runner')
/Users/ethanberry/dev/flutter_voice/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99. (in target 'Pods-Runner' from project 'Pods')

Could not build the application for the simulator.
Error launching application on iPhone 12 Pro Max.]

**Comment by sowens-csd** [comment]
Is this with a new project or an existing project? What version of Flutter are you using? I just created a brand new project using Flutter 2.2.3 on the stable channel, added the speech_to_text dependency then built it and ran it from VSCode and there were no problems with the build. 

My first thought would be to do a 'flutter clean' in the project directory, then delete the `ios/Podfile` and `iOS/Podfile.lock` and let flutter recreate them for you. Then try a rebuild. If that doesn't work then make sure that cocoapods is up to date on the machine. An extreme option is to create a brand new project and add your code back to that if it is an older project that has drifted away from compatibility.

**Comment by sowens-csd** [comment]
any updates on this?

**Comment by allendrew** [comment]
Hello @sowens-csd 

My apology for replying late.  I was not feeling well for the past few weeks.

I have tried all of your suggestions, flutter clean, delete the ios/Podfile and iOS/Podfile.lock and made sure cocoapods is up to date.

I'm simply trying to run this github code example: https://github.com/JohannesMilke/speech_to_text_example
I'm running Android studio arctic fox 2020.3.1 patch 1 on a Macbook Pro 13" M1

I'm using Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (2 months ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods.rb

Any help you can provide is appreciated.
