### ISSUE TITLE
Return recorded audio source file.

### ISSUE THREAD

**Issue by hsangtini** [csdcorp/speech_to_text#256]
Thank you for plugin.

For some reason, sometime we need recorded audio source file. So can you give this feature?

I found a listener on Android - onBufferReceived. On iOS i don't know very well :(

Regard

**Comment by sowens-csd** [comment]
This is a feature that has been requested but so far I haven't been able to find any Android support for it, though I could probably do it on iOS. Could you give me a link to some documentation on that onBufferReceived function and I'll have a look. Thanks!

**Comment by maxkrieger** [comment]
@sowens-csd I would love this feature too but it looks like that callback isn't intended for recording https://stackoverflow.com/a/16340756

Is there a way to have a recording listener run at the same time as as the recognizer? Or is the microphone thread locked?

**Comment by sowens-csd** [comment]
All the research I've done on this so far has indicated that the speech recognizer is the only thing that can access the microphone / sound stream while active.
