### ISSUE TITLE
Lost Connnection to Device (iOS Simulator)

### ISSUE THREAD

**Issue by AhmedNourJamalElDin** [csdcorp/speech_to_text#258]
Hello,

Speech to text doesn't work in my project on a real physical devices, so I test it on iOS Simulator but it does not work too.
so I made a new testing project with only speech to text.

I get error: "Lost Connection to Device" on simulator but I didn't test this testing project on a real physical device.

When running on XCode, it throws this exception:

```
Details

Could not launch “Runner”
Domain: IDEDebugSessionErrorDomain
Code: 3
Failure Reason: internal error
--
```

As you know, when I open the app, it prompts for Speech to Text permission, if I allow it, the app crashes (Lost Connection to device) but if I rejected the permission, the app does not crash. Then if I go to the settings, and enable the permission manually, immediately`flutter run` crashes stating "Lost Connection to Device" in the terminal.

Any idea how to fix this?

**Comment by sowens-csd** [comment]
Usually that happens when you haven't added the required privacy keys to the Info.plist file. Check the README for the list. Let me know if that doesn't resolve it.

**Comment by AhmedNourJamalElDin** [comment]
Thanks for your response

Do you mean the permissions? if so, I have already added them and have made sure they are there.

![image](https://user-images.githubusercontent.com/18269514/132801240-18019591-49ab-4a15-855d-c71299322fee.png)

**Comment by sowens-csd** [comment]
Yes, it was those permissions I was thinking of. Have you tried the example app on the same device? What version of Flutter and the plugin are you using?

**Comment by AhmedNourJamalElDin** [comment]
Hi @sowens-csd 

> Have you tried the example app on the same device?

No, I can not deploy the testing project on a real physical device because I need to create new app in app store.

But I have tested the examples in this plugin on the Simulator, but literally same issue.

> What version of Flutter and the plugin are you using?

Flutter version: 2.0.0
Plugin: `speech_to_text: ^5.0.0`

**Comment by sowens-csd** [comment]
I have had a problem in the past with corrupted simulators. Might be worth trying to create a new simulator and see if that changes the behaviour.
