### ISSUE TITLE
Don't work without an internet

### ISSUE THREAD

**Issue by alpha-21** [csdcorp/speech_to_text#264]
Hello evryone,
The plugin don't work without an internet in my simulator and in my phone what can i do for change this.
Thank you very much for your help

**Comment by sowens-csd** [comment]
Both iOS and Android voice recognition typically require an Internet connection. There is an `onDevice` flag you can use on on the `listen` method that tries to force recognition to occur on the device and not use a connection. If I remember correctly that flag is strict on iOS and only some newer devices support it, on Android it asks to use local processing but doesn't force it.

**Comment by sowens-csd** [comment]
Coincidentally I see that API 31 (Android 12) has added support both for detecting whether a device supports on device recognition and for requesting an on device recognizer. I'll add support for that in a future version of the plugin. 
https://developer.android.com/reference/android/speech/SpeechRecognizer#createOnDeviceSpeechRecognizer(android.content.Context)
https://developer.android.com/reference/android/speech/SpeechRecognizer#isOnDeviceRecognitionAvailable(android.content.Context)

**Comment by cselti** [comment]
If you set detection language `en_US` it will work offline. On Android the offline speech recognition language files can be downloadable in the Google application (Profile -> Settings -> Voice -> Offline speech recognition). Only a few languages supported offline at the moment.

**Comment by sowens-csd** [comment]
I've added support for the onDevice flag for Android 31 or greater. Unfortunately I don't yet have an Android 32 device. If anyone could test out the version from the repo that would be great. You should just have to set the `onDevice: true` option in the `listen` method and as long as the device supports it it should work. Please let me know if you have a chance to try it.

**Comment by sowens-csd** [comment]
This is in the repo version only so far.

**Comment by sowens-csd** [comment]
This is now released in 5.6.0 if anyone has a chance to try it that would be helpful.
