### ISSUE TITLE
Execution failed for task ':speech_to_text:compileDebugKotlin'

### ISSUE THREAD

**Issue by tamoyal** [csdcorp/speech_to_text#267]
This might be related to fixing #265. I'm attempting to test that now but can't get the app to run due to the compilation error below:

```
Launching lib/main.dart on Pixel 4 in debug mode...
e: /Users/tamoyal/flutter/.pub-cache/hosted/pub.dartlang.org/speech_to_text-5.2.0/android/src/main/kotlin/com/csdcorp/speech_to_text/SpeechToTextPlugin.kt: (594, 30): Unresolved reference: ERROR_LANGUAGE_NOT_SUPPORTED
e: /Users/tamoyal/flutter/.pub-cache/hosted/pub.dartlang.org/speech_to_text-5.2.0/android/src/main/kotlin/com/csdcorp/speech_to_text/SpeechToTextPlugin.kt: (595, 30): Unresolved reference: ERROR_LANGUAGE_UNAVAILABLE
e: /Users/tamoyal/flutter/.pub-cache/hosted/pub.dartlang.org/speech_to_text-5.2.0/android/src/main/kotlin/com/csdcorp/speech_to_text/SpeechToTextPlugin.kt: (596, 30): Unresolved reference: ERROR_SERVER_DISCONNECTED
e: /Users/tamoyal/flutter/.pub-cache/hosted/pub.dartlang.org/speech_to_text-5.2.0/android/src/main/kotlin/com/csdcorp/speech_to_text/SpeechToTextPlugin.kt: (597, 30): Unresolved reference: ERROR_TOO_MANY_REQUESTS

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':speech_to_text:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
Running Gradle task 'assembleDevelopmentDebug'...                  23.8s
Exception: Gradle task assembleDevelopmentDebug failed with exit code 1
```

**Comment by tamoyal** [comment]
Ah sorry, just saw this note: `Requires compileSdkVersion 31` ...that works!

**Comment by cmedamine** [comment]
should i set targetSdkVersion to 31???

**Comment by Reeganantony** [comment]
I updated compiledskVersion 31. but still i am facing the error.

**Comment by sowens-csd** [comment]
This is a closed issue, if you're having a problem it's better to post a new issue as it's more visible. When you do could you include the output from the compilation so we can see if there are any differences and include a reference to this issue saying you tried these steps.

**Comment by bhavya-merufintech** [comment]
> This is a closed issue, if you're having a problem it's better to post a new issue as it's more visible. When you do could you include the output from the compilation so we can see if there are any differences and include a reference to this issue saying you tried these steps.

e: file:///C:/Users/Admin/AppData/Local/Pub/Cache/hosted/pub.dev/speech_to_text-6.6.0/android/src/main/kotlin/com/csdcorp/speech_to_text/SpeechToTextPlugin.kt:37:48 Unresolved reference: Registrar
e: file:///C:/Users/Admin/AppData/Local/Pub/Cache/hosted/pub.dev/speech_to_text-6.6.0/android/src/main/kotlin/com/csdcorp/speech_to_text/SpeechToTextPlugin.kt:139:37 Unresolved reference: Registrar

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':speech_to_text:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
