### ISSUE TITLE
E/SpeechToTextPlugin(14745): Speech recognition not available on this device

### ISSUE THREAD

**Issue by CAMKULKARNI** [csdcorp/speech_to_text#268]
I am running an app that requires me to convert speech to text using the speech_to_text module in flutter.
When  I am running it I am getting the error as shown above. I am using a Pixel 4 for testing the app

**Comment by sowens-csd** [comment]
Does the example app work on the device? 

Usually either speech recognition services are not installed on the device yet or you haven't put all the required entries into the manifest. Check the readme file or the example for the required manifest entries. On a Pixel 4 it is unlikely that speech services aren't installed. Usually as long as Google assistant is working properly speech services are there.

**Comment by sowens-csd** [comment]
Any update on this?

**Comment by davidgalarza** [comment]
Same issue here on android devices with android 5.1

**Comment by CAMKULKARNI** [comment]
Sorry, sir
Actually, the mail went to the spam folder and  I don't know-how.
I have actually created a new emulator Pixel 3a and the app works in that.
I wonder why it wasn't working in Pixel 4.

**Comment by CAMKULKARNI** [comment]
I'm using the latest version.

**Comment by sowens-csd** [comment]
No further information provided, closing.
