### ISSUE TITLE
Improvement required in partial results

### ISSUE THREAD

**Issue by nilotpalkapri** [csdcorp/speech_to_text#271]
When partialResults is true, expecting it to give result word by word immediately but it is not happening. An example is given below for clarification-

Speech: Hello I am Nilotpal
Expected Result: Hello + I + am + Nilotpal
Actual Result: Hello + Hello I + Hello I am + Hello I am Nilotpal

is there any way to handle this issue?

**Comment by nilotpalkapri** [comment]
One thing I can do from my side is recording previous words in a variable and replacing it in the next result by "". And resting the var on 'done'.

I am looking for a better way to do this.

**Comment by sowens-csd** [comment]
This is working as expected. `partialResult` means that it provides the words as it understands them as it is processing. I don't think that providing a word by word version would work because the speech recognizer frequently changes its understanding of previous words based on the context provided in subsequent words.

**Comment by nilotpalkapri** [comment]
Yaah, I can understand that sentence may changes when processing based on the confidence score but if we can't get word by word result then what is the use of partialResult?

**Comment by sowens-csd** [comment]
It provides results as soon as any are available so it providers a faster feedback loop. Those results could be used to provide feedback in the UX on the current understanding. For command or confirmation processing it's the partial results are often good enough. If you're just looking for a yes/no confirmation for example getting the result as quickly as possible is a good thing. That being said it isn't always required so it is optional.

**Comment by nilotpalkapri** [comment]
ok got it, you can still think of word by word implementation if possible, it will be really helpful. Anyway thanks for the quick explanation.
