### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Reeganantony** [csdcorp/speech_to_text#274]
e: C:\Users\tonya\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\speech_to_text-5.2.0\android\src\main\kotlin\com\csdcorp\speech_to_text\SpeechToTextPlugin.kt: (594, 30): Unresolved reference: ERROR_LANGUAGE_NOT_SUPPORTED
e: C:\Users\tonya\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\speech_to_text-5.2.0\android\src\main\kotlin\com\csdcorp\speech_to_text\SpeechToTextPlugin.kt: (595, 30): Unresolved reference: ERROR_LANGUAGE_UNAVAILABLE
e: C:\Users\tonya\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\speech_to_text-5.2.0\android\src\main\kotlin\com\csdcorp\speech_to_text\SpeechToTextPlugin.kt: (596, 30): Unresolved reference: ERROR_SERVER_DISCONNECTED
e: C:\Users\tonya\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\speech_to_text-5.2.0\android\src\main\kotlin\com\csdcorp\speech_to_text\SpeechToTextPlugin.kt: (597, 30): Unresolved reference: ERROR_TOO_MANY_REQUESTS

**Comment by sowens-csd** [comment]
From 5.2.0 onwards the plugin requires `compileSdkVersion 31`
