### ISSUE TITLE
not work on flutter web ios device

### ISSUE THREAD

**Issue by hieupro1106** [csdcorp/speech_to_text#275]
flutter web run in android and window work well but can not start in ios device

**Comment by hieupro1106** [comment]
here is my code, seam like stt can not initialize on ios device browser, everything work fine on other 
`class SpeakWidget extends StatelessWidget {
  const SpeakWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final Controller c = Get.put(Controller());
    SpeechToText stt = SpeechToText();

    Future initSpeech() async {
      c.speechEnabled = RxBool(await stt.initialize());
      c.update();
    }
    void onSpeechResult(SpeechRecognitionResult result) {
      if (result.alternates[result.alternates.length - 1].recognizedWords != c.listenString.string){
        c.listenString = RxString(result.alternates[result.alternates.length - 1].recognizedWords);
        c.update();
      }
    }
    Future startListening() async {
      await stt.listen(
        onResult: onSpeechResult,
        localeId: c.locale.string
      );
    }
    void stopListening() async {
      await stt.stop();
    }

    Widget localeWidget() {
      return Row(
        children: [
          const SizedBox(
            height: 40,
            child: VerticalDivider(
              width: 20,
              thickness: 1,
              indent: 5,
              endIndent: 5,
              color: Colors.black26,
            ),
          ),
          Expanded(
            flex:2,
            child: GetBuilder<Controller>(
              builder: (_) => DropdownButton<String>(
                value: c.locale.string,
                icon: const Icon(
                  Icons.arrow_drop_down,
                  color: Color.fromRGBO(3, 64, 24, 1),
                ),
                borderRadius: const BorderRadius.all(Radius.circular(15)),
                iconSize: 20,
                isDense: true,
                isExpanded: true,
                style: const TextStyle(
                  color: textColor,
                  fontSize: 20,
                  overflow: TextOverflow.ellipsis,
                ),
                underline: const SizedBox(),
                onChanged: (String? newValue) {
                  c.locale = RxString(newValue!);
                  c.update();
                },
                items: <String>['en-US', 'en-GB']
                    .map<DropdownMenuItem<String>>((String value) {
                  return DropdownMenuItem<String>(
                    value: value,
                    child: Text(value),
                  );
                }).toList(),
              ),),
          ),
          const SizedBox(
            height: 40,
            child: VerticalDivider(
              width: 20,
              thickness: 1,
              indent: 5,
              endIndent: 5,
              color: Colors.black26,
            ),
          ),
        ],
      );
    }

    Widget speedSpeakWidget() {
      return Row(
        children: [
          const SizedBox(width:20),
          Text(
            c.drawerSpeech.string.toLowerCase(),
            textAlign: TextAlign.center,
            style: const TextStyle(
              fontSize: 16,
              color: textColor,
            ),
            overflow: TextOverflow.ellipsis,
          ),
          Expanded(
            child: GetBuilder<Controller>(
              builder: (_) => Slider(
                value: c.speakSpeed.value,
                min: 0.1,
                max: 1,
                divisions: 9,
                activeColor: backgroundColor,
                inactiveColor: const Color.fromRGBO(240, 240, 240, 1),
                thumbColor: backgroundColor,
                label: double.parse((c.speakSpeed.value).toStringAsFixed(1)).toString(),
                onChanged: (double value) async {
                  c.speakSpeed = RxDouble(value);
                  c.update();
                },
              ),
            ),
          ),
        ]
      );
    }

    Widget pronunWidget() {
      return TextButton(
        style: ButtonStyle(
          backgroundColor: MaterialStateProperty.all<Color>(
              Colors.white
          ),
          foregroundColor: MaterialStateProperty.all<Color>(Colors.grey),
          padding: MaterialStateProperty.all<EdgeInsets>(
              const EdgeInsets.all(0)
          ),
          shape: MaterialStateProperty.all<OutlinedBorder?>(
              RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(30.0),
              )
          ),
          fixedSize: MaterialStateProperty.all<Size>(
              const Size.fromHeight(40)
          ),
        ),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.start,
          children: [
            const SizedBox(width: 3),
            const Icon(
              Icons.volume_up_outlined,
              size: 30,
              color: backgroundColor,
            ),
            GetBuilder<Controller>(
              builder: (_) => Text(
                c.pronun.string,
                style: GoogleFonts.voces(
                  fontSize: 20,
                  color: textColor,
                  textStyle: const TextStyle(
                    overflow: TextOverflow.ellipsis,
                  ),
                ),
              ),
            ),
            const SizedBox(width: 3),
          ],
        ),
        onPressed: () async {
          await _speak(c.word.string);
        },
      );
    }

    WidgetsBinding.instance?.addPostFrameCallback((_) async {
      await initSpeech();
    });

    return Container(
      color: Colors.white,
      child: Column(
        mainAxisAlignment: MainAxisAlignment.start,
        crossAxisAlignment: CrossAxisAlignment.center,
        children:<Widget> [
          const SizedBox(height:10),
          GetBuilder<Controller>(
            builder: (_) => Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  for (int index=0; index<(c.mean.length<c.imageShow.value?c.mean.length:c.imageShow.value); index++)
                    Container(
                        margin: const EdgeInsets.all(10),
                        decoration: BoxDecoration(
                          color: Colors.white,
                          borderRadius: const BorderRadius.all(
                              Radius.circular(8)
                          ),
                          boxShadow: [
                            BoxShadow(
                              color: Colors.black.withOpacity(0.6),
                              spreadRadius: 0,
                              blurRadius: 5,
                              offset: const Offset(5, 5), // changes position of shadow
                            ),
                          ],
                        ),
                        // alignment: Alignment.center,
                        width: MediaQuery.of(context).size.width > 420? 180: (MediaQuery.of(context).size.width-60)/2,
                        height: MediaQuery.of(context).size.width > 420? 180*0.7: (MediaQuery.of(context).size.width-60)*0.7/2,
                        child: Stack(
                            children:[
                              ClipRRect(
                                borderRadius: BorderRadius.circular(8),
                                child: ImageFiltered(
                                  imageFilter: ImageFilter.blur(sigmaX: 6, sigmaY: 6),
                                  child: Opacity(
                                    opacity: 0.8,
                                    child: Image(
                                      image: NetworkImage('https://bedict.com/' + c.imageURL[index].replaceAll('\\','')),
                                      fit: BoxFit.fill,
                                      width: MediaQuery.of(context).size.width > 420? 180: (MediaQuery.of(context).size.width-60)/2,
                                      height: MediaQuery.of(context).size.width > 420? 180*0.7: (MediaQuery.of(context).size.width-60)*0.7/2,
                                      errorBuilder: (BuildContext context, Object exception, StackTrace? stackTrace) {
                                        return const SizedBox();
                                      },
                                    ),
                                  ),
                                ),
                              ),
                              ClipRRect(
                                borderRadius: BorderRadius.circular(8),
                                child: Image(
                                  image: NetworkImage('https://bedict.com/' + c.imageURL[index].replaceAll('\\','')),
                                  fit: BoxFit.contain,
                                  width: MediaQuery.of(context).size.width > 420? 180: (MediaQuery.of(context).size.width-60)/2,
                                  height: MediaQuery.of(context).size.width > 420? 180*0.7: (MediaQuery.of(context).size.width-60)*0.7/2,
                                  errorBuilder: (BuildContext context, Object exception, StackTrace? stackTrace) {
                                    return const SizedBox();
                                  },
                                ),
                              ),
                            ]
                        )
                    )
                ]
            ),
          ),
          const SizedBox(height:5),
          MediaQuery.of(context).size.width<MediaQuery.of(context).size.height?
            Column(
              children: [
                speedSpeakWidget(),
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    const SizedBox(width:10),
                    Expanded(
                      flex: 3,
                      child: pronunWidget(),
                    ),
                    const SizedBox(width:10),
                    Expanded(
                      flex: 2,
                      child: localeWidget(),
                    ),
                    const SizedBox(width:10),
                  ],
                ),
              ]
            ):
            Column(
              children: [
                const SizedBox(height:10),
                Row(
                    children: [
                      const SizedBox(width: 140),
                      Expanded(
                        flex: 6,
                        child: speedSpeakWidget(),
                      ),
                      const SizedBox(width: 20),
                      Expanded(
                        flex: 4,
                        child: pronunWidget(),
                      ),
                      const SizedBox(width: 20),
                      Expanded(
                        flex: 2,
                        child: localeWidget(),
                      ),
                      const SizedBox(width: 140),
                    ]
                ),
              ]
            ),
          Expanded(
            flex: 3,
            child: Container(
              alignment: Alignment.center,
              child: SingleChildScrollView(
                child: GetBuilder<Controller>(
                  builder: (_) => Text(
                    c.listenString.string,
                    textAlign: TextAlign.center,
                    style: const TextStyle(
                      fontSize: 35,
                      color: textColor,
                      // overflow: TextOverflow.ellipsis,
                    ),
                  ),
                ),
              ),
            ),
          ),
          Expanded(
            flex: 5,
            child: Container(
              alignment: Alignment.center,
              child: GestureDetector(
                onTap: (){
                  stt.isNotListening ? startListening() : stopListening();
                },
                child: GetBuilder<Controller>(
                  builder: (_) => Icon(
                    c.speechEnabled.value ? Icons.mic : Icons.mic_off,
                    size:150,
                    color: backgroundColor,
                  ),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}`

**Comment by hieupro1106** [comment]
here is my code, seam like stt can not initialize on ios device browser, everything work fine on other
`class SpeakWidget extends StatelessWidget {
  const SpeakWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final Controller c = Get.put(Controller());
    SpeechToText stt = SpeechToText();

    Future initSpeech() async {
      c.speechEnabled = RxBool(await stt.initialize());
      c.update();
    }
    void onSpeechResult(SpeechRecognitionResult result) {
      if (result.alternates[result.alternates.length - 1].recognizedWords != c.listenString.string){
        c.listenString = RxString(result.alternates[result.alternates.length - 1].recognizedWords);
        c.update();
      }
    }
    Future startListening() async {
      await stt.listen(
        onResult: onSpeechResult,
        localeId: c.locale.string
      );
    }
    void stopListening() async {
      await stt.stop();
    }

    Widget localeWidget() {
      return Row(
        children: [
          const SizedBox(
            height: 40,
            child: VerticalDivider(
              width: 20,
              thickness: 1,
              indent: 5,
              endIndent: 5,
              color: Colors.black26,
            ),
          ),
          Expanded(
            flex:2,
            child: GetBuilder<Controller>(
              builder: (_) => DropdownButton<String>(
                value: c.locale.string,
                icon: const Icon(
                  Icons.arrow_drop_down,
                  color: Color.fromRGBO(3, 64, 24, 1),
                ),
                borderRadius: const BorderRadius.all(Radius.circular(15)),
                iconSize: 20,
                isDense: true,
                isExpanded: true,
                style: const TextStyle(
                  color: textColor,
                  fontSize: 20,
                  overflow: TextOverflow.ellipsis,
                ),
                underline: const SizedBox(),
                onChanged: (String? newValue) {
                  c.locale = RxString(newValue!);
                  c.update();
                },
                items: <String>['en-US', 'en-GB']
                    .map<DropdownMenuItem<String>>((String value) {
                  return DropdownMenuItem<String>(
                    value: value,
                    child: Text(value),
                  );
                }).toList(),
              ),),
          ),
          const SizedBox(
            height: 40,
            child: VerticalDivider(
              width: 20,
              thickness: 1,
              indent: 5,
              endIndent: 5,
              color: Colors.black26,
            ),
          ),
        ],
      );
    }

    Widget speedSpeakWidget() {
      return Row(
        children: [
          const SizedBox(width:20),
          Text(
            c.drawerSpeech.string.toLowerCase(),
            textAlign: TextAlign.center,
            style: const TextStyle(
              fontSize: 16,
              color: textColor,
            ),
            overflow: TextOverflow.ellipsis,
          ),
          Expanded(
            child: GetBuilder<Controller>(
              builder: (_) => Slider(
                value: c.speakSpeed.value,
                min: 0.1,
                max: 1,
                divisions: 9,
                activeColor: backgroundColor,
                inactiveColor: const Color.fromRGBO(240, 240, 240, 1),
                thumbColor: backgroundColor,
                label: double.parse((c.speakSpeed.value).toStringAsFixed(1)).toString(),
                onChanged: (double value) async {
                  c.speakSpeed = RxDouble(value);
                  c.update();
                },
              ),
            ),
          ),
        ]
      );
    }

    Widget pronunWidget() {
      return TextButton(
        style: ButtonStyle(
          backgroundColor: MaterialStateProperty.all<Color>(
              Colors.white
          ),
          foregroundColor: MaterialStateProperty.all<Color>(Colors.grey),
          padding: MaterialStateProperty.all<EdgeInsets>(
              const EdgeInsets.all(0)
          ),
          shape: MaterialStateProperty.all<OutlinedBorder?>(
              RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(30.0),
              )
          ),
          fixedSize: MaterialStateProperty.all<Size>(
              const Size.fromHeight(40)
          ),
        ),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.start,
          children: [
            const SizedBox(width: 3),
            const Icon(
              Icons.volume_up_outlined,
              size: 30,
              color: backgroundColor,
            ),
            GetBuilder<Controller>(
              builder: (_) => Text(
                c.pronun.string,
                style: GoogleFonts.voces(
                  fontSize: 20,
                  color: textColor,
                  textStyle: const TextStyle(
                    overflow: TextOverflow.ellipsis,
                  ),
                ),
              ),
            ),
            const SizedBox(width: 3),
          ],
        ),
        onPressed: () async {
          await _speak(c.word.string);
        },
      );
    }

    WidgetsBinding.instance?.addPostFrameCallback((_) async {
      await initSpeech();
    });

    return Container(
      color: Colors.white,
      child: Column(
        mainAxisAlignment: MainAxisAlignment.start,
        crossAxisAlignment: CrossAxisAlignment.center,
        children:<Widget> [
          const SizedBox(height:10),
          GetBuilder<Controller>(
            builder: (_) => Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  for (int index=0; index<(c.mean.length<c.imageShow.value?c.mean.length:c.imageShow.value); index++)
                    Container(
                        margin: const EdgeInsets.all(10),
                        decoration: BoxDecoration(
                          color: Colors.white,
                          borderRadius: const BorderRadius.all(
                              Radius.circular(8)
                          ),
                          boxShadow: [
                            BoxShadow(
                              color: Colors.black.withOpacity(0.6),
                              spreadRadius: 0,
                              blurRadius: 5,
                              offset: const Offset(5, 5), // changes position of shadow
                            ),
                          ],
                        ),
                        // alignment: Alignment.center,
                        width: MediaQuery.of(context).size.width > 420? 180: (MediaQuery.of(context).size.width-60)/2,
                        height: MediaQuery.of(context).size.width > 420? 180*0.7: (MediaQuery.of(context).size.width-60)*0.7/2,
                        child: Stack(
                            children:[
                              ClipRRect(
                                borderRadius: BorderRadius.circular(8),
                                child: ImageFiltered(
                                  imageFilter: ImageFilter.blur(sigmaX: 6, sigmaY: 6),
                                  child: Opacity(
                                    opacity: 0.8,
                                    child: Image(
                                      image: NetworkImage('https://bedict.com/' + c.imageURL[index].replaceAll('\\','')),
                                      fit: BoxFit.fill,
                                      width: MediaQuery.of(context).size.width > 420? 180: (MediaQuery.of(context).size.width-60)/2,
                                      height: MediaQuery.of(context).size.width > 420? 180*0.7: (MediaQuery.of(context).size.width-60)*0.7/2,
                                      errorBuilder: (BuildContext context, Object exception, StackTrace? stackTrace) {
                                        return const SizedBox();
                                      },
                                    ),
                                  ),
                                ),
                              ),
                              ClipRRect(
                                borderRadius: BorderRadius.circular(8),
                                child: Image(
                                  image: NetworkImage('https://bedict.com/' + c.imageURL[index].replaceAll('\\','')),
                                  fit: BoxFit.contain,
                                  width: MediaQuery.of(context).size.width > 420? 180: (MediaQuery.of(context).size.width-60)/2,
                                  height: MediaQuery.of(context).size.width > 420? 180*0.7: (MediaQuery.of(context).size.width-60)*0.7/2,
                                  errorBuilder: (BuildContext context, Object exception, StackTrace? stackTrace) {
                                    return const SizedBox();
                                  },
                                ),
                              ),
                            ]
                        )
                    )
                ]
            ),
          ),
          const SizedBox(height:5),
          MediaQuery.of(context).size.width<MediaQuery.of(context).size.height?
            Column(
              children: [
                speedSpeakWidget(),
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    const SizedBox(width:10),
                    Expanded(
                      flex: 3,
                      child: pronunWidget(),
                    ),
                    const SizedBox(width:10),
                    Expanded(
                      flex: 2,
                      child: localeWidget(),
                    ),
                    const SizedBox(width:10),
                  ],
                ),
              ]
            ):
            Column(
              children: [
                const SizedBox(height:10),
                Row(
                    children: [
                      const SizedBox(width: 140),
                      Expanded(
                        flex: 6,
                        child: speedSpeakWidget(),
                      ),
                      const SizedBox(width: 20),
                      Expanded(
                        flex: 4,
                        child: pronunWidget(),
                      ),
                      const SizedBox(width: 20),
                      Expanded(
                        flex: 2,
                        child: localeWidget(),
                      ),
                      const SizedBox(width: 140),
                    ]
                ),
              ]
            ),
          Expanded(
            flex: 3,
            child: Container(
              alignment: Alignment.center,
              child: SingleChildScrollView(
                child: GetBuilder<Controller>(
                  builder: (_) => Text(
                    c.listenString.string,
                    textAlign: TextAlign.center,
                    style: const TextStyle(
                      fontSize: 35,
                      color: textColor,
                      // overflow: TextOverflow.ellipsis,
                    ),
                  ),
                ),
              ),
            ),
          ),
          Expanded(
            flex: 5,
            child: Container(
              alignment: Alignment.center,
              child: GestureDetector(
                onTap: (){
                  stt.isNotListening ? startListening() : stopListening();
                },
                child: GetBuilder<Controller>(
                  builder: (_) => Icon(
                    c.speechEnabled.value ? Icons.mic : Icons.mic_off,
                    size:150,
                    color: backgroundColor,
                  ),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}`

**Comment by sowens-csd** [comment]
Does this reference help at all? https://bugs.webkit.org/show_bug.cgi?id=225298

**Comment by sowens-csd** [comment]
Closing until there is more information available.
