### ISSUE TITLE
I/flutter (11723): Error : SpeechRecognitionError msg: error_permission, permanent: true

### ISSUE THREAD

**Issue by valentynkuts** [csdcorp/speech_to_text#276]

**Comment by valentynkuts** [comment]
Added in AndroidManifest.xml


    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.RECORD_AUDIO"/>
    <queries>
        <intent>
            <action android:name="android.speech.RecognitionService" />
        </intent>
    </queries>

**Comment by samerkh** [comment]
same error android 11 emulator
