### ISSUE TITLE
How to mute the beep sound for SpeechRecognizer?

### ISSUE THREAD

**Issue by Bisharat62** [csdcorp/speech_to_text#278]
actually this is not an issue but it will be enhancement , when we press mic button for listening mic beeps (a sound generated) can we have a solution to mute that beep sound using this package?

**Comment by sowens-csd** [comment]
For Android it is built into the OS level speech recognition system and there is no API to disable it.

**Comment by Bisharat62** [comment]
thankyou soo much for your response,
