### ISSUE TITLE
Unhandled Exception: PlatformException(recognizerNotAvailable, Speech recognition not available on this device, , null)

### ISSUE THREAD

**Issue by thuchau** [csdcorp/speech_to_text#279]
Emulator: Pixel XL
API: 30
speech_to_text: ^5.3.0

code init:
bool ready = await _speechToText.initialize(onError: onError, onStatus: onStatus);

  void onStatus(String status) { }

  void onError(SpeechRecognitionError errorNotification) {}

Exception at this code in lib:
`    return await _channel.invokeMethod<bool>(
          'initialize',
          params,
        ) ??
        false;`

`E/SpeechToTextPlugin( 3342): Speech recognition not available on this device
E/flutter ( 3342): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(recognizerNotAvailable, Speech recognition not available on this device, , null)
E/flutter ( 3342): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter ( 3342): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter ( 3342): <asynchronous suspension>
E/flutter ( 3342): #2      MethodChannelSpeechToText.initialize (package:speech_to_text_platform_interface/method_channel_speech_to_text.dart:39:12)
E/flutter ( 3342): <asynchronous suspension>
E/flutter ( 3342): #3      SpeechToText.initialize (package:speech_to_text/speech_to_text.dart:238:19)
E/flutter ( 3342): <asynchronous suspension>

**Comment by thuchau** [comment]
speech_to_text: ^5.3.0

**Comment by dominiqueware34** [comment]
Have you tried on Pixel 4? Check this thread https://stackoverflow.com/questions/5916521/how-can-you-make-the-android-emulator-support-speech-recognition


I believe it has something to do with the emulator needing the google search feature ( i could be wrong)


![image](https://user-images.githubusercontent.com/11010084/146594205-4071436c-3ef3-45f3-9b43-ab29c5d8c6cf.png)

**Comment by sowens-csd** [comment]
Yes, that's right, you must make sure that the emulator has support. I think the README has some links on how to set that up.

**Comment by thuchau** [comment]
1. I think this exception occurs on emulators don't support google play. I wonder Speech_To_Text package can return an error, is it better than throw an exception? because I think many developers want to test other functions on these emulators.

2. "checks if a speech recognizer is available on the device before completing initialize"
I'm a newbie in flutter, I don't find how a way to check a speech recognizer is available on the device in programming, could you help me?

**Comment by sowens-csd** [comment]
1. You can catch the exception with a try, but yes, I probably will change this to a false response and an error at some point. 
2. I misremembered, I'd thought there was a separate test to see if speech recognition is available but I see that it is embedded as part of the initialize call. In fact it's that test that you're hitting to get the exception you're seeing. 
3. The documentation for the `SpeechErrorListener` type has the current list of errors. I see that it has gotten slightly out of date so I'll update in an upcoming release.

**Comment by thuchau** [comment]
> 1. You can catch the exception with a try, but yes, I probably will change this to a false response and an error at some point.
> 2. I misremembered, I'd thought there was a separate test to see if speech recognition is available but I see that it is embedded as part of the initialize call. In fact it's that test that you're hitting to get the exception you're seeing.
> 3. The documentation for the `SpeechErrorListener` type has the current list of errors. I see that it has gotten slightly out of date so I'll update in an upcoming release.

Thank you so much, I got it. Waiting for your updating about SpeechErrorListener document.
