### ISSUE TITLE
Workaround for Desktop Development

### ISSUE THREAD

**Issue by ProtoManGG** [csdcorp/speech_to_text#28]

**Comment by ProtoManGG** [comment]
Hi What if i want to make a desktop app how can i access the laptops microphone will the same code as for android work here i guess not could you enlighten me ?

**Comment by sowens-csd** [comment]
AFAIK the plugin will not work on the desktop. I don't think any of the APIs it uses are available. It might be possible to develop some of the functionality depending on the availability of the speech recognition APIs on the desktop.That's not currently on the roadmap.
