### ISSUE TITLE
can we mute mic beep sound when listner start & stop listening without effecting sysytem sound

### ISSUE THREAD

**Issue by Bisharat62** [csdcorp/speech_to_text#281]
i am working on contineous listening project after each interval mic beep sound comes i wants to mute mic beep sound any help Thankyou in advace

**Comment by sowens-csd** [comment]
This is a feature of the Android OS and there is no supported way to disable it. I've just updated the FAQ to document this as just about everyone asks about it.

**Comment by timmolter** [comment]
Do you think maybe a solution like this could be applied to this package: https://stackoverflow.com/a/48060783/1625820
? I don't know enough at this point be a good judge of the feasibility.
