### ISSUE TITLE
Need android.permission.BLUETOOTH_CONNECT Android 31

### ISSUE THREAD

**Issue by sowens-csd** [csdcorp/speech_to_text#282]
Somehow even after putting all new permissions above into AndroidManifest, I'm still getting:

E/AndroidRuntime(24941): Caused by: java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for android.content.AttributionSource@d04c5dd9: AdapterService getBondedDevices
on init.

This happens with SdkVersion 31 only.

As per https://issueexplorer.com/issue/stripe/stripe-terminal-android/171 and https://stackoverflow.com/questions/70245463/java-lang-securityexception-need-android-permission-bluetooth-connect-permissio/70245537, client should explicitly request BLUETOOTH_CONNECT permission, which seems doesn't happen...

**Comment by sowens-csd** [comment]
Yes, I hadn't realized there was a new permission required for Android 31. I've added that to the repo version, I don't have an Android 31 device to test with, let me know if you can test it.

**Comment by rayrapetyan** [comment]
It works! Note that app cache\storage should be cleared to trigger device to ask for a new permission, otherwise it continues to silently crash...

**Comment by sowens-csd** [comment]
Thanks for testing. This is uploaded as 5.4.2 now.
