### ISSUE TITLE
getting unresolved reference error from package for target and compile sdk versions less than 31

### ISSUE THREAD

**Issue by PrithiviRajG** [csdcorp/speech_to_text#283]
Getting the below error when I try to run flutter run command. Only the selected items below getting unresolved reference error like 
BLUETOOTH_CONNECT, ERROR_LANGUAGE_NOT_SUPPORTED, ERROR_LANGUAGE_UNAVAILABLE, ERROR_SERVER_DISCONNECTED, ERROR_TOO_MANY_REQUESTS

 C:\Users\91900\flutter_windows_2.8.1-stable\flutter\.pub-cache\hosted\pub.dartlang.org\speech_to_text-5.4.2\android\src\main\kotlin\com\csdcorp\speech_to_text\SpeechToTextPlugin.kt: (458, 87): Unresolved reference: BLUETOOTH_CONNECT
e: C:\Users\91900\flutter_windows_2.8.1-stable\flutter\.pub-cache\hosted\pub.dartlang.org\speech_to_text-5.4.2\android\src\main\kotlin\com\csdcorp\speech_to_text\SpeechToTextPlugin.kt: (651, 30): Unresolved reference: ERROR_LANGUAGE_NOT_SUPPORTED
e: C:\Users\91900\flutter_windows_2.8.1-stable\flutter\.pub-cache\hosted\pub.dartlang.org\speech_to_text-5.4.2\android\src\main\kotlin\com\csdcorp\speech_to_text\SpeechToTextPlugin.kt: (652, 30): Unresolved reference: ERROR_LANGUAGE_UNAVAILABLE
e: C:\Users\91900\flutter_windows_2.8.1-stable\flutter\.pub-cache\hosted\pub.dartlang.org\speech_to_text-5.4.2\android\src\main\kotlin\com\csdcorp\speech_to_text\SpeechToTextPlugin.kt: (653, 30): Unresolved reference: ERROR_SERVER_DISCONNECTED
e: C:\Users\91900\flutter_windows_2.8.1-stable\flutter\.pub-cache\hosted\pub.dartlang.org\speech_to_text-5.4.2\android\src\main\kotlin\com\csdcorp\speech_to_text\SpeechToTextPlugin.kt: (654, 30): Unresolved reference: ERROR_TOO_MANY_REQUESTS

On referring [android documentation](https://developer.android.com/reference/android/speech/SpeechRecognizer) some of them added only in API level 31. 

Error got resolved on updating target and compiled sdk versions to 31 in build.gradle file.

Is this expected? in the readme targetSDK is mentioned as 28

**Comment by sowens-csd** [comment]
I think that only `compileSDK` at 31 should be required. If you set it but leave target are you still seeing a problem?
