### ISSUE TITLE
Need BLUETOOTH permission causing failure

### ISSUE THREAD

**Issue by thandal** [csdcorp/speech_to_text#285]
After the most recent release (5.4.2), my app is suddenly failing with due to a lack of bluetooth permission.

I expect that I can fix this by requesting bluetooth permissions, but it broke things for me, and I figured other people might run into the same problem.

Ideally, recording from the built-in mic would still work *without* BLUETOOTH permission, rather than the whole thing completely failing.

E/SpeechToTextPlugin(10014): Unexpected exception
E/SpeechToTextPlugin(10014): java.lang.SecurityException: Need BLUETOOTH permission: Neither user 10180 nor current process has android.permission.BLUETOOTH.
E/SpeechToTextPlugin(10014): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
E/SpeechToTextPlugin(10014): 	at android.os.Parcel.createException(Parcel.java:2357)
E/SpeechToTextPlugin(10014): 	at android.os.Parcel.readException(Parcel.java:2340)
E/SpeechToTextPlugin(10014): 	at android.os.Parcel.readException(Parcel.java:2282)
E/SpeechToTextPlugin(10014): 	at android.bluetooth.IBluetoothManager$Stub$Proxy.registerStateChangeCallback(IBluetoothManager.java:509)
E/SpeechToTextPlugin(10014): 	at android.bluetooth.BluetoothHeadset.<init>(BluetoothHeadset.java:358)
E/SpeechToTextPlugin(10014): 	at android.bluetooth.BluetoothAdapter.getProfileProxy(BluetoothAdapter.java:2806)
E/SpeechToTextPlugin(10014): 	at com.csdcorp.speech_to_text.SpeechToTextPlugin.setupBluetooth(SpeechToTextPlugin.kt:523)
E/SpeechToTextPlugin(10014): 	at com.csdcorp.speech_to_text.SpeechToTextPlugin.completeInitialize(SpeechToTextPlugin.kt:484)
E/SpeechToTextPlugin(10014): 	at com.csdcorp.speech_to_text.SpeechToTextPlugin.initializeIfPermitted(SpeechToTextPlugin.kt:465)
E/SpeechToTextPlugin(10014): 	at com.csdcorp.speech_to_text.SpeechToTextPlugin.initialize(SpeechToTextPlugin.kt:253)
E/SpeechToTextPlugin(10014): 	at com.csdcorp.speech_to_text.SpeechToTextPlugin.onMethodCall(SpeechToTextPlugin.kt:191)
E/SpeechToTextPlugin(10014): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/SpeechToTextPlugin(10014): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:178)
E/SpeechToTextPlugin(10014): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:206)
E/SpeechToTextPlugin(10014): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/SpeechToTextPlugin(10014): 	at android.os.Handler.handleCallback(Handler.java:938)
E/SpeechToTextPlugin(10014): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/SpeechToTextPlugin(10014): 	at android.os.Looper.loop(Looper.java:223)
E/SpeechToTextPlugin(10014): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/SpeechToTextPlugin(10014): 	at java.lang.reflect.Method.invoke(Native Method)
E/SpeechToTextPlugin(10014): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/SpeechToTextPlugin(10014): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by sowens-csd** [comment]
You make a good point, the extra permissions are a breaking change. It feels like an odd thing to add an extra parameter for. I think it's unfortunate that the OS requires extra permission for something so basic. I'll think about adding parameters to the initialize and requestPermission calls that could disable the bluetooth permission.

**Comment by sowens-csd** [comment]
There's a new version in the repo that supports disabling bluetooth support and the required permissions through the initialization function. See #296 for a code example. Let me know if you have a chance to try it.
