### ISSUE TITLE
What sort of limitations exist?

### ISSUE THREAD

**Issue by CodyBontecou** [csdcorp/speech_to_text#287]
Coming from the web world, Speech-to-Text APIs tend to cost money.
Is there a usage limit that exists using the APIs integrated with this package?

**Comment by sowens-csd** [comment]
There are no costs. Both Android and iOS reserve the right to limit usage but provide no guidance on how much is too much. You should be prepared to handle usage limit errors but in practice I haven't seen them in my own usage. The web version also does not impose limits as far as I'm aware.

**Comment by CodyBontecou** [comment]
> There are no costs. Both Android and iOS reserve the right to limit usage but provide no guidance on how much is too much. You should be prepared to handle usage limit errors but in practice I haven't seen them in my own usage. The web version also does not impose limits as far as I'm aware.

Good to know, thank you.
