### ISSUE TITLE
"error_listen_failed" using iOS simulator and null safety versions

### ISSUE THREAD

**Issue by joseplazatb** [csdcorp/speech_to_text#290]
Hi,
The speech to text is not working at all for me using the iOS simulator since I updated to the latest version (tested all the null-safety versions from 4.2.0). Neither the sample code nor my code works. I'm using flutter version 2.8.1. I just receive the following error:

error_listen_failed, permanent: true, listening: false

If I build the .ipa and install it in a physical device it works. Tested in simulators with iOS version 15.0 and 15.2, in both Intel and M1 computers. Previously my app ran with 3.2.0 version (non null-safety) without issues.

Just to be sure, I created a new flutter project with null safety and pasted the example, using the latest version of the package, and the issue persists.

I found another related issue here https://github.com/csdcorp/speech_to_text/issues/284, but it was closed since the problem is only for simulator.

Can anyone help me? Thanks in advance!

**Comment by sowens-csd** [comment]
I'm exploring this now. The short answer is that yes, something has definitely changed with simulator support and I think it's on Apple's side but I'm not sure yet. Also not sure if I can work around it. I'll report back once I know more.

**Comment by sowens-csd** [comment]
I have more detail now but don't yet know if I can resolve it. Simulators are causing two separate problems, one is the dreaded format.sampleRate == hwFormat.sampleRate issue. There's an interesting approach suggested here that I tried and partially resolved it https://stackoverflow.com/questions/66971504/i-got-crash-when-record-required-condition-is-false-format-samplerate-hwf. The basic idea is to always convert from whatever the current sample rate is to a known sample rate using an audio converter. 

Unfortunately even with that fix I started getting 1107 which doesn't seem to have a clear description or a fix, discussions of it here https://developer.apple.com/forums/thread/73256 among other places. 

The other issue on simulators is a sensitivity to the simulator configuration. The only way I was able to get it partially working is to always set the simulator audio input and output to `System` not to a particular device.

**Comment by Iverson** [comment]
> @sowens-csd Just a heads-up that speech_to_text is apparently working again on iOS Simulators after updating to iOS 16.0 (installed as part of an XCode 14 update, which I didn't request, but just popped up yesterday).
> 
> On previous Simulators with iOS 15.x, speech_to_text.listen() would fail immediately for me.
> 
> After the XCode update I had to recreate my iOS iPhone Simulators from 15.6 (if I remember the version correctly), to 16.0 (the only available choice). After re-installing my app on the Simulator (which uses speech_to_text ^5.6.0 & Flutter: 2.10.5.), listening initialized OK and then correctly interpreted my voice commands. Huzzah!
> 
> This is running on OSX Monterey 12.5.1 on an Intel Mac Mini 2018 using an external microphone with Sound Input device set to "External Microphone/Microphone port". The Simulator's I/O Audio Input is set to System (External Microphone).

Unfortunately, it doesn't work for me. I keep receiving "error_listen_failed" on iOS 16.0 iPhone Simulator (Intel).

**Comment by alexobviously** [comment]
I'm also getting this error since updating to MacOS Ventura and getting the iPhone 14 in the simulator.

**Comment by nholmvio** [comment]
likewise for me today after Ventura update and Xcode 14. 

Any other new data points in last month..  What are folks doing now...

**Comment by ben-xx** [comment]
@alexobviously @nholmvio 
Did speech_to_text stop working after upgrading to Ventura OS, but was fine on Monterey?  Or was there a version change on Xcode, iOS or speech_to_text as well?

I'm wondering whether it was the Monterey → Ventura that broke package operation or perhaps it's something else.

I haven't upgraded my Mac to Ventura yet and I'm using Simulator with iOS 16.1, Xcode 14.1 and speech_to_text 5.6.0 and the package is working well (starts without error & mic voice recognition/interpretation is working).

**Comment by nholmvio** [comment]
I had my voice feature disabled for quite some time.  It was probably from Big Sur days and i had 5.1.0 in my pubspec(when it was last tested).
I came back this week to revisit on Monterey, and latest Flutter release, and the 6.1.1. and it wasn't working and saw forum posts. 

 Upgraded to Ventura and Xcode 14 per the thread earlier today to see if went away.

I can confirm it's running on device ok...

Thanks

**Comment by alexobviously** [comment]
> @alexobviously @nholmvio Did speech_to_text stop working after upgrading to Ventura OS, but was fine on Monterey? Or was there a version change on Xcode, iOS or speech_to_text as well?

I'm not sure which of these - my guess was ios. I fixed this by on my emulator forcing the sample rate to 44100 (in `SpeechToText.listen`), though many of our customers are still getting it in production and we can't quite figure out why

**Comment by EmmanuelQC** [comment]
Still facing the same error with IOS 16.4 emulator. 

Ran it with IOS 14.5 emulator and it works fine. speechToText won't initialize for some reason and glitches out. Basically can't run tests for IOS 16+ until it gets fixed.

**Comment by sowens-csd** [comment]
I found a resolution for using simulators. The README has an update explaining how to configure simulators for speech recognition.
