### ISSUE TITLE
Question: install languages programatically

### ISSUE THREAD

**Issue by quickratio** [csdcorp/speech_to_text#293]
Hello, 

Is there a way for the app to install the language on behalf of the user? (through permissions etc.); on iOS even after manually adding languages (pt-PT) i still get:

Error Domain=kAFAssistantErrorDomain Code=1103 "No models installed yet" UserInfo={NSLocalizedFailureReason=No models installed yet}

Apologies if this has been asked before, i searched/browsed through the history and couldn't find it

**Comment by sowens-csd** [comment]
No, as far as I know that has to be done by the user.

**Comment by quickratio** [comment]
thanks for you response
