### ISSUE TITLE
The listner stops after a very short silence period

### ISSUE THREAD

**Issue by FerasAlhammoud** [csdcorp/speech_to_text#294]
In my Android app user needs to say a long sentence, the problem is if he stops talking for a very short time just to take a breath, the listner stops.
In the documentation of "Android speech recognition" they mentioned how to increase the silence period:

https://developer.android.com/reference/android/speech/RecognizerIntent.html#EXTRA_SPEECH_INPUT_COMPLETE_SILENCE_LENGTH_MILLIS

Thanks in advance

**Comment by sowens-csd** [comment]
Things may have changed since I last tried these but all of the Android speech tuning parameters I've tried in the past have been completely ignored by the OS. Even the docs you linked to notes that:
> Note that it is extremely rare you'd want to specify this value in an intent. If you don't have a very good reason to change these, you should leave them as they are. Note also that certain values may cause undesired or unexpected results - use judiciously! Additionally, depending on the recognizer implementation, these values may have no effect.

I'll try again at some point to see if newer OS builds have changed the behaviour.

**Comment by piratejoe** [comment]
Flutter web: custom pauseFor and listenFor values not taking effect. The pauseFor duration is definitely something I would want to tweak. Otherwise works great!

**Comment by sowens-csd** [comment]
I'm surprised those don't work on FlutterWeb. I should probably extend the example app to allow those two parameters to be tuned so I can more easily check reports like these. I'll do that and then see what's up with them.

**Comment by sowens-csd** [comment]
I just committed a change to the example app to allow the `pauseFor` and `listenFor` options to be set in the UI. I tried those options in the example on the web and they seemed to be working. Could you give the example app a try and let me know if you see issues?

**Comment by dyardy** [comment]
This still seems to be an issue.  i.e. Android cuts off after very short period.  Modifying pausefor and listenfor really didn't change anything.

**Comment by sowens-csd** [comment]
Yes, this is covered in the README. Android does not provide any control over the no speech detected time out.
