### ISSUE TITLE
Android 12 - Bluetooth permission

### ISSUE THREAD

**Issue by emilien-io** [csdcorp/speech_to_text#296]
Hello guys, 

First of all, thanks for your work, it really helped a lot.

I saw that from a certain version of Android, I had to ask for Bluetooth permission.
Is there a possibility to use this library without asking bluetooth permission? My project does not allow the possibility of connecting your device to another.

Thanks in advance.

**Comment by emilien-io** [comment]
Would it be an option to downgrade to 5.3.0 ?
I tried and it seems the BLE permission is no longer asked but I'm kind of worried that the package won't work properly on Android 12

**Comment by sowens-csd** [comment]
I think 5.3.0 should be fine on 12. I had a look at the changes since and they are all related to Bluetooth support.

**Comment by emilien-io** [comment]
I think that'll do the work in the meantime!
Can't wait to update this package

Thanks again for you work.

**Comment by Zeswen** [comment]
Hi @sowens-csd, thank you for the feature! Would you mind making a release for it? `5.4.3` would be a great choice :)

**Comment by emilien-io** [comment]
Thanks for your work @sowens-csd!
A new release would be amazing 👍

**Comment by sowens-csd** [comment]
5.4.3 published to pub.dev now. Thanks for the feedback, I appreciate it.

**Comment by alfie-trbc** [comment]
It would be nice if this options is available too in the documentation read me in the pub.dev
