### ISSUE TITLE
On Install error due to missing flutter .h file

### ISSUE THREAD

**Issue by SwarmShepherd** [csdcorp/speech_to_text#297]
On my Windows 10 based system, all seems to have gone well with repo clone  (using IntelllIJ),  except on doing 'flutter get pub' my system yields following:

_C:\tools\flutter-sdk\flutter\bin\flutter.bat --no-color pub get
Running "flutter pub get" in audio_player_interaction...        
Cannot create link, path = 'C:\tools\flutter-sdk\flutter\.pub-cache\_temp\dircedb8dcd\ios\Classes\AudioplayersPlugin.h' (OS Error: A required privilege is not held by the client.
, errno = 1314)
pub get failed (66; , errno = 1314))
Process finished with exit code 66_

Note,  No file exists in this folder.

**Comment by SwarmShepherd** [comment]
I have been able to resolve after several hours of searching, and trying things.   Doing  Flutter 'cache repair' seems to have been the final fix.  This problem has been around for long while.

**Comment by sowens-csd** [comment]
Thanks for following up with what you found. Sounds like the problem wasn't related to the plugin in the end, is that correct?
