### ISSUE TITLE
Android 12 issue

### ISSUE THREAD

**Issue by FerasAlhammoud** [csdcorp/speech_to_text#301]
On android 12 it doesn't work although it asks for the mic permission.

**Comment by sowens-csd** [comment]
Are you testing on a real device or a simulator? Are you sure that the device has speech recognition properly installed? Usually if Google voice services are working the plugin should work. If you're still having trouble can you submit a log from the device taken with `debugLogging` true.

**Comment by sowens-csd** [comment]
Any updates on this issue?
