### ISSUE TITLE
Example doesn't compile "out of the box" (Android 10,11,12 devices)

### ISSUE THREAD

**Issue by 3SCadmin** [csdcorp/speech_to_text#302]
I know this sounds like a noob complaint, but this is a pet peeve of mine:  If I clone from git, the example should just work!

There are 1000s of flutter packages, some aren't maintained, some don't do what they claim.
When we explore a new package, we just want to see it run once.   We just want to see if it does what we are looking for.

We don't want to start with debugging, trouble shooting or reading the fine-print, we just want to see it run and then decide if it's worth exploring the nitty-gritty

**Comment by sowens-csd** [comment]
Doesn't sound like a noob complaint, rather like a not very detailed or helpful complaint. I do aim to have the sample just work, if they're not I'd like to fix them. Do you have an error that you encountered trying to get it to compile?

**Comment by asmith26** [comment]
In case it helps, to get the "multi_platform_example" to work, I had to:

1. Update https://github.com/csdcorp/speech_to_text/blob/fd50581c6e37b9f7b734965881eacdcd2eb915f9/multi_platform_example/android/build.gradle#L2 to `ext.kotlin_version = '1.6.10'`
2. Add `<uses-permission android:name="android.permission.BLUETOOTH"/>` to 
 https://github.com/csdcorp/speech_to_text/blob/fd50581c6e37b9f7b734965881eacdcd2eb915f9/multi_platform_example/android/app/src/main/AndroidManifest.xml#L3

Many thanks for this lib!

**Comment by sowens-csd** [comment]
Thanks for the details. The multi_platform_example is obsolete now, I used it while I was writing the web support because I couldn't figure out how to get the main example to add web support. That's been resolved now so the primary example supports all platforms. Let me know if there was something in the multi_platform_example that you were using in particular. My plan is to delete that from the repo so it doesn't confuse people.

**Comment by asmith26** [comment]
Thanks for the info @sowens-csd, I only used "multi_platform_example" as it is the one linked in the [README](https://github.com/csdcorp/speech_to_text#example-apps). So I'm happy for you to delete this thanks.

**Comment by sowens-csd** [comment]
And there's something else I should fix!

**Comment by sowens-csd** [comment]
I've updated the README and deleted the multi_platform_example. If there are other issues with building the example app please create a new issue. Thanks for the feedback.
