### ISSUE TITLE
Question: Code example to identify what languages speech recognition supports?

### ISSUE THREAD

**Issue by asmith26** [csdcorp/speech_to_text#305]
Hi there,

I was wondering if it is possible to have a code example to obtain the list of languages a device supports? I've had a look at a few issues (e.g. https://github.com/csdcorp/speech_to_text/issues/257 and https://github.com/csdcorp/speech_to_text/issues/154), but I can't quite work out what code is used.

Some things I've tried:

```dart
print(_speech.locales().toString());  // prints: Instance of 'Future<List<LocaleName>>'
print(await _speech.locales());  // prints nothing

List locales = await _speech.locales();
locales.map((e) => print(e));  // prints nothing
```

Thanks for any help, and for this fantastic lib! :)

**Comment by sowens-csd** [comment]
The main example uses the locales to populate the drop down so there's some example code there. If you just wanted to print them it would look something like this: 

```dart
var locales = await _speech.locales();
localeNames.forEach((locale) =>
        print("${locale.name} - ${locale.localeId}"));
```

**Comment by asmith26** [comment]
Thanks you!
