### ISSUE TITLE
RequestPermissionsResultListener Run time error

### ISSUE THREAD

**Issue by ChandrakantOmn** [csdcorp/speech_to_text#306]
pub-cache/hosted/pub.dartlang.org/speech_to_text-5.4.3/android/src/main/kotlin/com/csdcorp/speech_to_text/SpeechToTextPlugin.kt: (81, 8): Class 'SpeechToTextPlugin' is not abstract and does not implement abstract member public abstract fun onRequestPermissionsResult(p0: Int, p1: Array<(out) String!>, p2: IntArray): Boolean defined in io.flutter.plugin.common.PluginRegistry.RequestPermissionsResultListener 'onRequestPermissionsResult' overrides nothing

**Comment by sowens-csd** [comment]
The title says Run time error but this looks more like a compilation problem. Where do you see the error message? What version of Flutter and Android are you using?
