### ISSUE TITLE
Speech to Text English only?

### ISSUE THREAD

**Issue by itxmubi** [csdcorp/speech_to_text#308]
Hi Everyone
I tried this package and note that whatever language I speak, this package interprets into the English Language in text form. can I change my language to another, like I speak Italian, Urdu, etc, and the text I got will also in Italian Urdu, etc..

**Comment by sowens-csd** [comment]
The plugin works in whatever language you configure it for. Have you checked the README? There's an example of how to properly set the language code.

**Comment by itxmubi** [comment]
yeah got it, thanks.
