### ISSUE TITLE
Can we use a list of words as dictionary to improve words detection

### ISSUE THREAD

**Issue by Lyazz** [csdcorp/speech_to_text#310]
Hello there, is there a way to set in parameter a list of words or phrases to improve word detection accuracy as speech adaptation of the Google Speech-to-text API. Thanks

**Comment by sowens-csd** [comment]
No, as far as I know that's not a feature of the speech recognizers on any of the platforms the plugin supports. If you have a list of likely words you could run a search on the returned list of possible words and look for matches among lower probability suggestions from the recognizer.
