### ISSUE TITLE
Trigger Word like Amazons "Hey Alexa"

### ISSUE THREAD

**Issue by JosipDomazetDev** [csdcorp/speech_to_text#311]
Hey, I was wondering if there is the possibility of adding a trigger word to activiate the voice recognition. Since continuous voice recognition is not possible this would be a nice feature to have so the user does not have to press a button every time he wants to talk. This would be similiar to Amazons "Hey Alexa". Awesome library so far!

**Comment by sowens-csd** [comment]
The underlying voice recognition subsystems don't support that kind of background listening. To make things more complicated Android also doesn't support doing speech conversion on recorded files so recording the audio separately and then triggering recognition wouldn't be feasible. All that means the short answer is no, it's not a planned feature.
