### ISSUE TITLE
From Audio File ?

### ISSUE THREAD

**Issue by imeDevelopers** [csdcorp/speech_to_text#314]
Can we extract text from a recorded speech as audio file, a local or remote one ? why not ?

because you don't give ability to "record current audio, while user speaking" we have to use external plugin,
now we're using external plugin, can you extract the speech from this audio file ?!

**Comment by sowens-csd** [comment]
No, unfortunately the underlying speech engine on Android doesn't support converting recorded audio. 
I have been trying to find a good solution for recording the audio while the user is speaking and there's a separate issue that is tracking that work #295.
