### ISSUE TITLE
Compilation errors - Flutter 3.0

### ISSUE THREAD

**Issue by naamapps** [csdcorp/speech_to_text#315]
Hi, 
I'm using the latest beta of Flutter 2.13.0. and I can't build my app because of errors.

I know this is not ideal using the beta version of flutter and request support for it, but I would kindly ask you to publish a prerelease (dev) version of speech_to_text with fixes for this errors, as this will also happen when 2.13.0 hits stable.

Thanks
```
e: /opt/homebrew/Caskroom/flutter/2.10.4/flutter/.pub-cache/hosted/pub.dartlang.org/speech_to_text-5.4.3/android/src/main/kotlin/com/csdcorp/speech_to_text/SpeechToTextPlugin.kt: (81, 8): Class 'SpeechToTextPlugin' is not abstract and does not implement abstract member public abstract fun onRequestPermissionsResult(p0: Int, p1: Array<(out) String!>, p2: IntArray): Boolean defined in io.flutter.plugin.common.PluginRegistry.RequestPermissionsResultListener
e: /opt/homebrew/Caskroom/flutter/2.10.4/flutter/.pub-cache/hosted/pub.dartlang.org/speech_to_text-5.4.3/android/src/main/kotlin/com/csdcorp/speech_to_text/SpeechToTextPlugin.kt: (627, 5): 'onRequestPermissionsResult' overrides nothing
e: /opt/homebrew/Caskroom/flutter/2.10.4/flutter/.pub-cache/hosted/pub.dartlang.org/speech_to_text-5.4.3/android/src/main/kotlin/com/csdcorp/speech_to_text/SpeechToTextPlugin.kt: (771, 9): Class 'ChannelResultWrapper' is not abstract and does not implement abstract member public abstract fun error(p0: String, p1: String?, p2: Any?): Unit defined in io.flutter.plugin.common.MethodChannel.Result
e: /opt/homebrew/Caskroom/flutter/2.10.4/flutter/.pub-cache/hosted/pub.dartlang.org/speech_to_text-5.4.3/android/src/main/kotlin/com/csdcorp/speech_to_text/SpeechToTextPlugin.kt: (786, 5): 'error' overrides nothing
e: /opt/homebrew/Caskroom/flutter/2.10.4/flutter/.pub-cache/hosted/pub.dartlang.org/speech_to_text-5.4.3/android/src/main/kotlin/com/csdcorp/speech_to_text/SpeechToTextPlugin.kt: (789, 30): Type mismatch: inferred type is String? but String was expected

FAILURE: Build failed with an exception.
```

**Comment by sowens-csd** [comment]
Thanks for letting me know. I'll try building with the beta. 

In the meantime I assume you've tried doing a `flutter clean` and then rebuilding? I feel like I've seen something like that error in the past when there was some mismatch between cached files and the current build setup.

**Comment by naamapps** [comment]
Hey @sowens-csd,
I did try flutter clean, it didn't work unfortunately.

**Comment by sowens-csd** [comment]
Thanks, I figured you would have but wanted to make sure. I'll have a look.

**Comment by naamapps** [comment]
Hey @sowens-csd,
Did you get the chance to have a look at this?
This is currently the only package that blocks me from release.

Thanks :)

**Comment by Menelphor** [comment]
FYI: Also an Issue in Flutter 3.0.

Thank you :)

**Comment by Terranic** [comment]
Confimed, seeing this build error with flutter 3.0 (including previous flutter pub clean)

> Hi, I'm using the latest beta of Flutter 2.13.0. and I can't build my app because of errors.
> 
> I know this is not ideal using the beta version of flutter and request support for it, but I would kindly ask you to publish a prerelease (dev) version of speech_to_text with fixes for this errors, as this will also happen when 2.13.0 hits stable.
> 
> Thanks
> 
> ```
> e: /opt/homebrew/Caskroom/flutter/2.10.4/flutter/.pub-cache/hosted/pub.dartlang.org/speech_to_text-5.4.3/android/src/main/kotlin/com/csdcorp/speech_to_text/SpeechToTextPlugin.kt: (81, 8): Class 'SpeechToTextPlugin' is not abstract and does not implement abstract member public abstract fun onRequestPermissionsResult(p0: Int, p1: Array<(out) String!>, p2: IntArray): Boolean defined in io.flutter.plugin.common.PluginRegistry.RequestPermissionsResultListener
> e: /opt/homebrew/Caskroom/flutter/2.10.4/flutter/.pub-cache/hosted/pub.dartlang.org/speech_to_text-5.4.3/android/src/main/kotlin/com/csdcorp/speech_to_text/SpeechToTextPlugin.kt: (627, 5): 'onRequestPermissionsResult' overrides nothing
> e: /opt/homebrew/Caskroom/flutter/2.10.4/flutter/.pub-cache/hosted/pub.dartlang.org/speech_to_text-5.4.3/android/src/main/kotlin/com/csdcorp/speech_to_text/SpeechToTextPlugin.kt: (771, 9): Class 'ChannelResultWrapper' is not abstract and does not implement abstract member public abstract fun error(p0: String, p1: String?, p2: Any?): Unit defined in io.flutter.plugin.common.MethodChannel.Result
> e: /opt/homebrew/Caskroom/flutter/2.10.4/flutter/.pub-cache/hosted/pub.dartlang.org/speech_to_text-5.4.3/android/src/main/kotlin/com/csdcorp/speech_to_text/SpeechToTextPlugin.kt: (786, 5): 'error' overrides nothing
> e: /opt/homebrew/Caskroom/flutter/2.10.4/flutter/.pub-cache/hosted/pub.dartlang.org/speech_to_text-5.4.3/android/src/main/kotlin/com/csdcorp/speech_to_text/SpeechToTextPlugin.kt: (789, 30): Type mismatch: inferred type is String? but String was expected
> 
> FAILURE: Build failed with an exception.
> ```

**Comment by atrope** [comment]
While it is not Merged and published you can use like that:
```

  speech_to_text: 
    git:
      url: https://github.com/SuaMusica/speech_to_text.git
      path: speech_to_text
      ref: fix/flutter3
```
