### ISSUE TITLE
Nearby device permission disable

### ISSUE THREAD

**Issue by hisham-89** [csdcorp/speech_to_text#324]
In android 12, there is new permission: nearby_device is granted without the approval of the user,
Any way to not grant that permission automatically.
or can I use the device microphone instead of the Bluetooth microphone?

**Comment by sowens-csd** [comment]
What problem are you trying to solve? You can turn Bluetooth permissions off completely for the app using an option to the `initialize` method. That looks like this:
```dart
speechRecognition.initialize(onStatus, _status, options:[SpeechToText.androidNoBluetooth]);
```
