### ISSUE TITLE
PlatformException(recognizerNotAvailable, Speech recognition not available on this device, , null).

### ISSUE THREAD

**Issue by vineetpandit90** [csdcorp/speech_to_text#325]
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError
PlatformException(recognizerNotAvailable, Speech recognition not available on this device, , null). Error thrown null.
StandardMethodCodec.decodeEnvelope (message_codecs.dart:607)

MethodChannel._invokeMethod (platform_channel.dart:177)
MethodChannelSpeechToText.initialize (method_channel_speech_to_text.dart:39)
SpeechToText.initialize (speech_to_text.dart:288)

**Comment by taydinadnan** [comment]
I am having the same issue, I use Huawei p smart 2021.
