### ISSUE TITLE
Information privacy when converting message voice to text

### ISSUE THREAD

**Issue by AngelaDevDesign** [csdcorp/speech_to_text#326]
Hello!

I am interested about knowing how the information recorded flows to the server. Is the recorded information saved or shared outside my device? to which server does this info go? 

Thank you!

**Comment by sowens-csd** [comment]
It depends entirely on the platform of the app. On iOS and Android you can explicitly request that the content remain `onDevice` using the plugin and if the device is capable it will honour that request and if not it will fail. If you don't explicitly request it then content flows to the servers used by the underlying OS. For iOS this would be Apple servers, for Android it could vary depending on the device manufacturer. For Web it depends on the browser, Google servers for Chrome, I'm not certain for other implementations. 

The plugin doesn't save or share the information anywhere so to understand the information privacy considerations you'll have to look in detail at the platform promises that are made for each platform that you support.
