### ISSUE TITLE
Is there a limit on the number of ios offline speech recognition？

### ISSUE THREAD

**Issue by watermelonQAQ** [csdcorp/speech_to_text#328]
I know that iOS online speech recognition has a limited number of times, and offline recognition can be used when "onDevice = true "is set.Is there a limit on the number of ios offline speech recognition？

**Comment by sowens-csd** [comment]
I don't believe so, at least I haven't seen any limits in the docs. Some articles certainly suggest that it is unlimited like this https://developer.apple.com/forums/thread/131940

**Comment by watermelonQAQ** [comment]
Thanks.
