### ISSUE TITLE
Build Fail for IOS

### ISSUE THREAD

**Issue by sedobrengocce** [csdcorp/speech_to_text#33]
I have this error when i try to build for IOS

** BUILD FAILED **
Xcode's output:
↳
    /Users/user921647/development/flutter/.pub-cache/hosted/pub.dartlang.org/speech_to_text-0.8.0/ios/Classes/SwiftSpeechToTextPlugin.swift:185:51: error: 'AVAudioSession.Category' (aka 'NSString') is not implicitly convertible to 'String'; did you mean to use 'as' to explicitly convert?
                    try self.audioSession.setCategory(rememberedAudioCategory)
                                                      ^
                                                                              as String
    /Users/user921647/development/flutter/.pub-cache/hosted/pub.dartlang.org/speech_to_text-0.8.0/ios/Classes/SwiftSpeechToTextPlugin.swift:201:57: error: cannot assign value of type 'String' to type 'AVAudioSession.Category?' (aka 'Optional<NSString>')
                rememberedAudioCategory = self.audioSession.category
                                          ~~~~~~~~~~~~~~~~~~^~~~~~~~
                                                                     as AVAudioSession.Category
    /Users/user921647/development/flutter/.pub-cache/hosted/pub.dartlang.org/speech_to_text-0.8.0/ios/Classes/SwiftSpeechToTextPlugin.swift:202:71: error: type 'AVAudioSession.Category' (aka 'NSString') has no member 'playAndRecord'
                try self.audioSession.setCategory(AVAudioSession.Category.playAndRecord)
                                                  ~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~
    /Users/user921647/development/flutter/.pub-cache/hosted/pub.dartlang.org/speech_to_text-0.8.0/ios/Classes/SwiftSpeechToTextPlugin.swift:203:63: error: type 'AVAudioSession.Mode' (aka 'NSString') has no member 'measurement'
                try self.audioSession.setMode(AVAudioSession.Mode.measurement)
    note: Using new build system
    note: Planning build
    note: Constructing build description
    warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the Runner editor. (in target 'Runner' from project 'Runner')
Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.
Exited (sigterm)


All is fine for android

**Comment by sowens-csd** [comment]
This is likely a problem with the version of Swift being used in your project. I'm using Swift 5 for all new projects. You can find this in the build settings of the Runner target in the project in Xcode.

**Comment by amitkot** [comment]
@sowens-csd 
Just ran into this issue myself, as it seems Flutter does not use Swift5 by default.
I would suggest adding this as a note in the documentation.

Thanks!
