### ISSUE TITLE
Does this works with google chrome box?

### ISSUE THREAD

**Issue by rodrigobastosv** [csdcorp/speech_to_text#330]
Hi, i'm trying to use the speech_to_text on a chromebox of mine.

I'm having the "not supported on this device" error. 

Thats strange because i can use the "native" speech recognition from the chrome box.

Did anyone had some kind of success running this on a chromebox? Would love to hear some feedback.

**Comment by sowens-csd** [comment]
Are you running it in a browser on the Chromebox or trying to run it as an app directly? I don't think it would be supported natively but might work in a browser.

**Comment by rodrigobastosv** [comment]
Im trying to run as an android app, following this guide https://support.google.com/googleplay/answer/7021273?hl=en.

 I tried to run as webapp on chromebox and it works fine.

**Comment by sowens-csd** [comment]
I've never tried that and I don't know if speech is supported in that scenario. The only result I found from some searching suggests that it is not always available. I think this is perhaps a better question for the support team for your box. 

https://community.appinventor.mit.edu/t/speech-recognizer-on-chromebook/31537

**Comment by sowens-csd** [comment]
I think this is all the info I've got so I'm going to close this, Please reopen or ask a new question if you have more questions.
