### ISSUE TITLE
A better way to handle Bluetooth permissions

### ISSUE THREAD

**Issue by rayrapetyan** [csdcorp/speech_to_text#332]
Hello. Currently (v. 5.6.0) there are two ways to handle BT permissions:

1. Define required BT permissions in a manifest and call speech.initialize(...). Then user will see a message like below:

> Allow APP to find, connect to, and determine the relative position of nearby devices?

which looks pretty dangerous and unrelated to BT, so user will most probably say NO. App will crash here.

2. call speech.initialize() passing options: [SpeechToText.androidNoBluetooth]). In this case user will not see any messages and will not get BT support.

So there is no way to support both users willing to use BT and not to in one build.

Can we introduce a minor change here and when user answers NO in 1 - app simply skips all BT communications and proceeds working with internal mic and speaker?

**Comment by sowens-csd** [comment]
Thanks for reporting. V 5.6.0 was supposed to fix that issue, sounds like it isn't working as I thought it was. It is supposed to be doing exactly what you suggested. I'll have a look at it. Were you testing against iOS or Android?

**Comment by rayrapetyan** [comment]
Android, thanks.

**Comment by sowens-csd** [comment]
I just tried this with 5.6.0 and I can't reproduce the result. I am unfortunately using a simulator because I don't have a physical device with a version of Android that requires the Bluetooth permission. Can you confirm what version of Android you are using and that you were definitely testing against 5.6.0? Also, the behaviour you're seeing is that as soon as the user says no to the BT permission dialog the app crashes? It is not when you start the `listen` method? Can you reproduce the problem in the example app?

**Comment by rayrapetyan** [comment]
Sure, I've tested example from your project. When user clicks on "initialize", then responds "yes" for "Allow recording audio" and then "no" for BT permission requests - app crashes, attaching logs. Thanks.
[debug.log](https://github.com/csdcorp/speech_to_text/files/9275624/debug.log)

**Comment by sowens-csd** [comment]
Thanks for the log, that's really helpful.

**Comment by sowens-csd** [comment]
I just pushed an update to the repo. If you have a chance to give it a try could you let me know the result? Thanks.

**Comment by rayrapetyan** [comment]
Thanks, it works. But rather than putting complex expression:

> if (Build.VERSION.SDK_INT>=23 && context != null && context.checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT) != PackageManager.PERMISSION_GRANTED) 

into every function which require BT permissions I would do it once on init (e.g. in `onRequestPermissionsResult` and in `initializeIfPermitted`).

I've prepared a PR for that: https://github.com/csdcorp/speech_to_text/pull/333

**Comment by sowens-csd** [comment]
Thanks, I'll have a look at the PR. I've pushed 5.6.1 to pub.dev in the meantime.

**Comment by sowens-csd** [comment]
I accepted the PR, thanks, that's a good change. I made what I hope is a small change that just inverts the state for the BT variable so I could remove some ! tests to clarify the intent. If you have a chance to try the repo version I'll publish this.

**Comment by sowens-csd** [comment]
Tested on a Pixel 6a running Android 12.
