### ISSUE TITLE
How Can i detect the noise and undefiend voice ?

### ISSUE THREAD

**Issue by Hossamattia028** [csdcorp/speech_to_text#334]

**Comment by sowens-csd** [comment]
You can use the `onSoundLevelChange` callback from the `listen` method to listen for every level change coming from the device. If you are seeing values coming back but not getting results in the `onResults` callback then it is likely that the voice is not being recognized.

**Comment by sowens-csd** [comment]
I think this answers the question so I'm going to close this. Please reopen or open a new issue if you have more questions.

**Comment by Hossamattia028** [comment]
Okay Thanks
