### ISSUE TITLE
Web app won't return results in v5.4.0 if I set finalTimeout in initialize(), or if I *don't* set listenFor and pauseFor in listen()

### ISSUE THREAD

**Issue by thandal** [csdcorp/speech_to_text#335]
The web version of my app just won't call back with any results (though the Available and Listening indicators act as expected, status callbacks work, and it listens longer if I talk continuously)... unless I make the following changes:
* REMOVE any finalTimeout argument from the stt.initialize() function.
* ADD BOTH listenFor and pauseFor arguments to the stt.listen() function.

Environment:
* speech_to_text v5.4.0
* Chrome Version 104.0.5112.81 (Official Build) (64-bit)
* Windows 11 22000.856

I verified that this same issue affects the speech_to_text/example project.

**Comment by sowens-csd** [comment]
Thanks for the report. I'll try to reproduce this and see what's going on. Do you know if it was working for you in a previous release?

**Comment by thandal** [comment]
Yes, it was -- this was maybe 6-8 months ago (unfortunately I haven't been
working on the web app side since then).

**Comment by sowens-csd** [comment]
Odd, I just tried it on Chrome and I can't reproduce the issue. I added a `finalTimeout` to the initialize and took both `pauseFor` and `listenFor` parameters off the `listen` method and still received results. Can you think of anything else that might have been special about the environment?
