### ISSUE TITLE
Called "cancel" but still returning error no match

### ISSUE THREAD

**Issue by peterweb2005** [csdcorp/speech_to_text#34]
as title

log
```
I/flutter (15123): 2020-02-12 02:53:48.652658 FINE [Page] _speechInputCancel()
I/flutter (15123): 2020-02-12 02:53:48.653389 FINE [SpeechService] cancel()
I/flutter (15123): SpeechToText call: notifyStatus notListening
I/flutter (15123): 2020-02-12 02:53:48.655197 FINE [Page] _speechOnStatus()
I/flutter (15123): 2020-02-12 02:53:48.655383 FINEST [Page] available: true
I/flutter (15123): 2020-02-12 02:53:48.655480 FINEST [Page] listening: false
I/flutter (15123): 2020-02-12 02:53:48.656249 FINEST [Page] cancel: 
...

I/flutter (15123): SpeechToText call: notifyError {"errorMsg":"error_no_match","permanent":true}
I/flutter (15123): 2020-02-12 02:53:49.042349 FINE [Page] _speechOnError()
I/flutter (15123): 2020-02-12 02:53:49.042699 FINEST [Page] error: SpeechRecognitionError msg: error_no_match, permanent: true
```

as comment of cancel()
  /// Canceling means that there will be no final result returned from the
  /// recognizer. *Note* Cannot be used until a successful [initialize] call.

is it because the "error no match" is partial result?

could you please make the api client, SpeechToText, able to config whether partial result is needed
kotlin```
272        putExtra(RecognizerIntent.EXTRA_PARTIAL_RESULTS, true)
273        Log.d(logTag, "put partial")
```

thanks very much

**Comment by sowens-csd** [comment]
Thanks for the idea on making the partial results configurable, I'll add that in an upcoming build. 

As for the "error no match" result that you're seeing I did a bit of a dive on causes and there appear to be a variety of them. I don't think it's related to calling cancel, at least I didn't see that in any of the sources. The most common causes of the error that I saw were, problems with offline recognition, interference between the Google assistant and the recognizer, and the recognizer trying to match its own start beep as a word. 

https://stackoverflow.com/questions/47695367/speechrecognizer-gives-no-match-immediately-after-the-start
https://stackoverflow.com/questions/31071650/speechrecognizer-throws-onerror-on-the-first-listening

The Android docs themselves don't provide much help. I'm leaning towards just reporting the errors I get from Android and letting applications decide how to handle them. However dealing with spurious error messages in every application is painful so there's an argument to be made for trying to block it at the plugin level if it could be reliably detected. One option would be to set 'permanent' to false for this particular error so at least applications could use that to keep going in the presence of the failure. 

I'll consider the options for the next update, input is welcome.

**Comment by peterweb2005** [comment]
thanks

made "cancelled" flag for workaround, attached to lifecycles and handled like:

```
    // temp skip permanent
    if (_cancelled == null && error.errorMsg != 'error_no_match') {
      _errorListener(error);
    }
```

**Comment by sowens-csd** [comment]
New version committed with support for controlling partial results through a new partialResults parameter on the listen method. Please give it a try and let me know what you think.

**Comment by sowens-csd** [comment]
Just committed another change that blocks further error notifications automatically on stop or cancel. It will be in the 1.0.0 release and is in the repo now.

**Comment by sowens-csd** [comment]
1.0.0 is now on pub.dev with this fix.
