### ISSUE TITLE
Question: Does this library support using audio file as input?

### ISSUE THREAD

**Issue by dhombios** [csdcorp/speech_to_text#340]
iOS native interface supports using some audio files as input for its voice recognition capabilities (which allows using them for transcribing voice memos). However, the API that pub.dev shows for this library doesn't seem to support it.

Is it possible to use this library for transcribing audio files?

**Comment by sowens-csd** [comment]
No, it doesn't. There's no support on Android so I haven't built that capability for iOS.

**Comment by dhombios** [comment]
Oh, that explains why it was so hard to find a library with audio file support. Thanks!
