### ISSUE TITLE
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher. The following dependencies do not satisfy the required version: project ':speech_to_text' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

### ISSUE THREAD

**Issue by brent777** [csdcorp/speech_to_text#341]
Hi,

I just upgraded my entire stack for my Flutter project and now when I try to build, I get the following error in Android Studio build output:

`The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':speech_to_text' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50`

If seeing my pubspec.yaml or build.gradle files will help, let me know and I can add them. I am running speech_to_text latest (6.0.0) by the way.

Thanks.

**Comment by sowens-csd** [comment]
Thanks, yes, your build.gradle could be helpful.

**Comment by brent777** [comment]
@sowens-csd below is my android/build.gradle:

`buildscript {
    ext.kotlin_version = '1.7.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.14'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

and below is my app/build.gradle

`def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion 33

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        applicationId "com.beardedbear.hischosen"
        testApplicationId "com.beardedbear.hischosen.test"
        minSdkVersion 21
        targetSdkVersion 33
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
    }

    signingConfigs {
        debug {
            storeFile file('key.jks')
            storePassword 'android'
            keyAlias 'androiddebugkeynew'
            keyPassword 'android'
        }
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        debug {
            applicationIdSuffix ".debug"
            signingConfig signingConfigs.debug
        }
        release {
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'

    implementation platform('com.google.firebase:firebase-bom:29.0.3')

    // Declare the dependencies for the Firebase Cloud Messaging and Analytics libraries
    // When using the BoM, you don't specify versions in Firebase library dependencies
    implementation 'com.google.firebase:firebase-messaging'
    implementation 'com.google.firebase:firebase-analytics'

    implementation 'com.android.support:multidex:2.0.1'
}

apply plugin: 'com.google.gms.google-services'  // Google Services plugin
`

**Comment by brent777** [comment]
@sowens-csd - just checking in to see if you need any more info from me or if the above is sufficient? I have had to remove speech to text from my app due to this issue, I cannot build the app otherwise.

**Comment by sowens-csd** [comment]
Could you try the repo version? If it's working for you I'll do a release. Thanks!

**Comment by KimVinod** [comment]
I'm also getting the same error as the OP.

**Comment by KimVinod** [comment]
I just tested speech_to_text (version: 6.1.0) in my project. The build error is gone now. I think you can update the package

**Comment by sowens-csd** [comment]
Thanks for testing. I'll put it out shortly.

**Comment by brent777** [comment]
@sowens-csd my apologies for my lack of response, I was very busy with some other issues for my upcoming release. I got around to testing this on 6.1.0 today and as @KimVinod said, it seems to be working now. Thanks so much!
