### ISSUE TITLE
Windows platform

### ISSUE THREAD

**Issue by vagoston** [csdcorp/speech_to_text#343]
Would you be interested in a Windows implementation?

**Comment by sowens-csd** [comment]
Yes, very interested! There’s already a platform interface so it is in a good place to accept new implementations. I’d be more than happy to help anyone understand the process or make changes / additions to the interface if required

**Comment by vagoston** [comment]
I was not aware that the changes in Flutter made it even harder to develop a Windows plugin. There is no support for /clr, and since Microsoft is abandoning UWP, flutter abandoned it as well. Long story short, I can't find a way to use modern winrt api without msvc support.
