### ISSUE TITLE
Message: Failed to create speech recognizer

### ISSUE THREAD

**Issue by NightSkyDev** [csdcorp/speech_to_text#346]
I'm getting the following exception when calling the listen method: "Unhandled Exception: Instance of 'ListenFailedException'" when calling listen.  

I set a breakpoint to check the message, and all I see is "Failed to create speech recognizer.  The details and stacktrace are null.

This is only happening on iOS - both the simulator and physical devices.  The thing is, this used to work when I was testing months ago.  I have no idea what could have broken this functionality since I hadn't made any changes to this code.  

Any tips on how to proceed with troubleshooting this?

Thanks!

**Comment by sowens-csd** [comment]
The first thing to try is to set `debugLogging` to true in the `initialize` method and then have a look at the debug output from the plugin. It's odd that it used to work and has stopped. Have you tried the example app on the same device? Is it working?

**Comment by NightSkyDev** [comment]
I should have been clearer - this code is working on Android.

When I first saw the problem I was on version 5.5.0 so I upgraded to version 6.0.0.  Same issue.

**Comment by sowens-csd** [comment]
That's good news about the sample app. 

Sorry, I should have said that the debug logs on iOS only show up in the Mac Console app if you are watching the device when the logging occurs. So you should open Console, connect to your device and start tracing before doing the initialize / start listen in the app. You can post the full log here if you'd like help reading the output. Select all + copy gets it.

**Comment by NightSkyDev** [comment]
>I should have said that the debug logs on iOS only show up in the Mac Console app

Thank you!  Once I could see the logs, I figured out the problem.  Turns out, I was not getting the current locale to pass to the listen method.
