### ISSUE TITLE
IOS offline recording does not work (Iphone 6)

### ISSUE THREAD

**Issue by smg-clouds** [csdcorp/speech_to_text#348]
The recording works fine until I turn off my internet connection ( On Android it works offline to) Is it a IOS problem or a IPhone 6 Problem ?

**Comment by smg-clouds** [comment]
Sure I can do that ...
I tested my App on Ipad too on Ipad it worked fine so yeah i guess it is a iphone6 Problem ... 
But here is my Code 
```
static Future<bool> toggleRecording({
    required Function(String text) onResult,
  }) async {




    final isAvailible = await _speech.initialize();

    if(isAvailible) {
      await _speech.listen(onResult: (value) => onResult(value.recognizedWords));
    }



    return isAvailible;
  }
```

**Comment by sowens-csd** [comment]
Okay, yes, this makes sense. I had thought you were using the onDevice flag but with this set of parameters the behaviour is correct.
