### ISSUE TITLE
how to keep control mic on own

### ISSUE THREAD

**Issue by vaibhavkumar049** [csdcorp/speech_to_text#35]
I am trying to develop an app that requires this plugin. When I run the example app I noticed that you can not keep mic open for a longer time. If it doesn't listen to the voice it shuts down. Is it the android issue or I am not using the plugin in the right way

**Comment by sowens-csd** [comment]
Yes, that is the design of the Android speech recognizer. It seems to be designed for relatively short duration interactions.

**Comment by sowens-csd** [comment]
Let me know if you have more questions. Closing this for now as it's working as expected.
