### ISSUE TITLE
empty locales 

### ISSUE THREAD

**Issue by westlinkin** [csdcorp/speech_to_text#355]
First of all, Great work!

I am using this for my Flutter web project. After initializing `SpeechToText` object, listen doesn't work. I log the `_speechToText.locales()`, it turns out be to empty. And the `systemLocale` is null

---

Chrome: Version 108.0.5359.98 (Official Build) (arm64)

---

Flutter 3.3.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b8f7f1f986 (3 weeks ago) • 2022-11-23 06:43:51 +0900
Engine • revision 8f2221fbef
Tools • Dart 2.18.5 • DevTools 2.15.0

Thanks in advance

**Comment by sowens-csd** [comment]
Is this on Chrome mobile or desktop? What language would you expect for the locale if it was working?

**Comment by westlinkin** [comment]
This is on desktop. I expected `en` or `en_US` because my language setting is my OS is `English`, my language setting in Chrome is also `English`.

**Comment by sowens-csd** [comment]
Does the example app work in the same browser?

**Comment by westlinkin** [comment]
Sorry, I found the problem. Google is banned here, so no internet connection with Google, so the `locales` is empty, therefore the plugin is down. I turn on the VPN and everything is working fine.

No problem with this plugin here!
