### ISSUE TITLE
Flutter web, no sound level,  onSoundLevelChange  not called

### ISSUE THREAD

**Issue by westlinkin** [csdcorp/speech_to_text#356]
```
await speech?.listen(
      onResult: _onSpeechResult,
      listenMode: ListenMode.dictation,
      onSoundLevelChange: _onSoundLevelChange,
      localeId: "en",
      cancelOnError: false,
      listenFor: const Duration(seconds: 180),
      pauseFor: const Duration(seconds: 5),
    );
```

this `_onSoundLevelChange` never gets called.

Flutter: 3.3.10
Chrome: Version 108.0.5359.124 (Official Build) (arm64)

**Comment by sowens-csd** [comment]
Yes, that's correct, this isn't supported on the web. I don't think the web speech API supports this although I haven't checked again recently. I should probably add a chart of supported features on each platform.
