### ISSUE TITLE
Google Assistant on Android Temporarily Becomes Unresponsive

### ISSUE THREAD

**Issue by syota-keica** [csdcorp/speech_to_text#357]
I have implemented speech recognition transcription using speech_to_text and it worked very well.

However, I encountered a phenomenon where "Hey, Google" to Google Assistant stopped responding.

My terminal information is below.
・OS version: Android 9.0
・Device name: Lenovo Tab5 801LV

Once speak_to_text is successfully initialized and litsten is run, Google Assistant will stop responding.
This is the same even if you execute stop() or cancel().

I tested on another device with the same Android 9.0 and some worked and some didn't.
I have a feeling it's more likely a device-specific issue than a code cause, but I'd appreciate any information you can give me.

thank you very much.

**Comment by sowens-csd** [comment]
That's very interesting, the first report I've heard about an interaction between Google Assistant and Speech To Text. I can understand how there could be an interaction. I'll do some testing on some devices I have here and see if I can reproduce the problem. Can you reproduce it with the example app?

**Comment by syota-keica** [comment]
thank you for your reply.

We have confirmed that it can be reproduced in the sample application.

The development environment other than the terminal information from the other day is as follows.
・Flutter: 3.0.5
・Dart: 2.17.6

**Comment by sowens-csd** [comment]
I just tried this on a Pixel 6a with Android 13 and couldn't reproduce the issue. Have you found out anything new about the cause?

**Comment by syota-keica** [comment]
Nothing new is known about the cause so far.
The following are the conditions that have been confirmed to occur.

1. What happens when you go through the listen function of spach to text
2. You are using a "Lenovo TAB5" device
3. Unrelated to "speak to text", but after using voice input from other apps on the "Lenovo TAB5" device, "OK, Google" can no longer be called.

An example of number 3:
After pressing the Chrome voice search button and finishing searching, there is no response even if you say "OK, Google".
