### ISSUE TITLE
Does speech_to_text work on Emulator?

### ISSUE THREAD

**Issue by PavelTurkish** [csdcorp/speech_to_text#358]
A have a real Android 11 device (Galaxy A12) and then this example - https://github.com/csdcorp/speech_to_text/tree/main/speech_to_text/example/ works. However, on my Android 11 emulator I get `error_permission`:

![Screenshot from 2022-12-23 12-42-42](https://user-images.githubusercontent.com/10261361/209322425-711f84b2-e5eb-4d33-b140-9addd03851c1.png)

Both android manifest (main and debug) have these lines:

```
    <uses-permission android:name="android.permission.RECORD_AUDIO"/>
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.BLUETOOTH"/>
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT"/>
    <queries>
        <intent>
            <action android:name="android.speech.RecognitionService" />
        </intent>
    </queries>
```

On [SO](https://stackoverflow.com/a/71874891/5057736) it says that speech_to_text doesn't work on emulators. Is this true (hard to believe)?. If not, could anyone say how to fix it?

**Comment by sowens-csd** [comment]
From other comments in this forum users have stated that they have been able to get it to work. You can search this forum for the discussions. The issue seems to be getting the correct Google components installed on the emulator along with the language packs. See #90 for example.
