### ISSUE TITLE
PauseFor parameter in SpeechToText.listen() method is ignored

### ISSUE THREAD

**Issue by PavelTurk** [csdcorp/speech_to_text#359]
I trying  https://github.com/csdcorp/speech_to_text/tree/main/speech_to_text/example/example with different parameters for `speech.listen()`. This is my code:

```
 void startListening() {
    lastWords = "";
    lastError = "";
    speech.listen(onResult: resultListener, listenFor: Duration(minutes: 10), pauseFor:  Duration(minutes: 1));
    setState(() {

    });
  }
```

This is from method docs:

```
  /// [listenFor] sets the maximum duration that it will listen for, after
  /// that it automatically stops the listen for you.
  ///
  /// [pauseFor] sets the maximum duration of a pause in speech with no words
  /// detected, after that it automatically stops the listen for you.
```
So, if I understand API correct, with these settings: `speech.listen(onResult: resultListener, listenFor: Duration(minutes: 10), pauseFor:  Duration(minutes: 1))` listening mustn't stop if a user makes a 3 seconds pause in his speech. But it stops! Or I do something wrong. Could anyone say how to make speech_to_text keep configured pauses?

**Comment by sowens-csd** [comment]
You are reading the documentation correctly, unfortunately Android and iOS don't completely respect the settings which is why I say those are maximum values, they set an upper bound. Android is not configurable at all, while iOS is a bit more configurable. On Android the pause seems to be 2-3 seconds and the maximum listening duration is unclear.

**Comment by sowens-csd** [comment]
Android doesn't support it, so yes, I should note that in the docs. I'd been holding out some hope that Android might start supporting it, but it is long past time that I gave up on that overly optimistic view and just documented it.

**Comment by dyardy** [comment]
On Android it stops listening after a taking a breath.  This makes it unusable on Android.  I have been looking for an approach to work around this limitation.  I have yet to find a solution.  Am I correct that there are not solutions to the listening stopping?
