### ISSUE TITLE
Stops listening after a very short time period.

### ISSUE THREAD

**Issue by dyardy** [csdcorp/speech_to_text#360]
On Android it stops listening after a taking a breath. 

This makes it unusable on Android. 

I have been looking for a work around this limitation. I have searched through 'issues' and stackoverflow and yet to find a solution.

Am I correct that there are no solutions to the listening stopping after a brief duration?

**Comment by sowens-csd** [comment]
Yes, that's correct. The Android OS enforces the maximum wait time for silence. Despite having parameters to allow that wait time to be overridden I have not yet found a device or OS version that respects those parameters.

**Comment by nvtphong200401** [comment]
You can re-listen when the status is done
For example:
![image](https://user-images.githubusercontent.com/56443232/210922717-e0a1dd88-7afc-4f20-be70-dba0cd3a10ee.png)

**Comment by DongsubShin** [comment]
same here. 
with android emulator, android stop listening after a short period

**Comment by sowens-csd** [comment]
As this isn't a new issue and I don't think there's anything more to be added I'm going to close this. There's a very lengthy discussion in #253 about how to correctly restart for longer duration listening.

**Comment by AliKarimiENT** [comment]
How can we disable audio when it starts recording while we continue listening in here?
