### ISSUE TITLE
Firebase deploy with Flutter doesn't work on the WEB

### ISSUE THREAD

**Issue by arisAlexis** [csdcorp/speech_to_text#362]
It's working locally. It's working on the Android emulator locally too. When I deploy the web version I get this error:

`Uncaught MissingPluginException(No implementation found for method initialize on channel plugin.csdcorp.com/speech_to_text)`

any ideas how this can be happening?

**Comment by sowens-csd** [comment]
Interesting, not off hand. Does it do this with example app?

**Comment by sowens-csd** [comment]
Any update on this?
