### ISSUE TITLE
Unable to use bluetooth microphone when it is connected

### ISSUE THREAD

**Issue by PremkumarManoharan** [csdcorp/speech_to_text#367]
5.4.2 Supports Bluetooth headsets on Android, this requires new permissions, see the permissions section below. Note that Bluetooth permission is requested from the user, when upgrading users may have to manually set the permission or clear their cache to force a re-request.

This version says this feature is added, but I could not see any implementation for Bluetooth headsets on Android, 
I can only find this implementation which is used for disabling the Bluetooth functionality
/// If your application does not need Bluetooth support on Android and
  /// you'd rather not have to ask for Bluetooth permission pass this option
  /// to disable Bluetooth support on Android.
  static final SpeechConfigOption androidNoBluetooth =
      SpeechConfigOption('android', 'noBluetooth', true);

  /// This option does nothing yet, may disable Bluetooth on iOS if there is
  /// a need.
  static final SpeechConfigOption iosNoBluetooth =
      SpeechConfigOption('ios', 'noBluetooth', true);

Is this functionality implemented ?

**Comment by sowens-csd** [comment]
Yes, it asks for Bluetooth permission by default and will use a Bluetooth mic if one is connected.

**Comment by PremkumarManoharan** [comment]
> Yes, it asks for Bluetooth permission by default and will use a Bluetooth mic if one is connected.

Thank you for your reply, I tried the same but still, it is using the mobile's default microphone. any suggestion ?

**Comment by sowens-csd** [comment]
What device and Android version are you using? It was working when I last tested it but I certainly haven't tried with all versions. Does your Bluetooth microphone work with dictation or other voice support on the device?

**Comment by PremkumarManoharan** [comment]
> What device and Android version are you using? It was working when I last tested it but I certainly haven't tried with all versions. Does your Bluetooth microphone work with dictation or other voice support on the device?

I tested in Android 13.  Yes, Bluetooth Microphone works with voice recorder application in the same device. Can i know which version of plugin and android version you used for testing ? Thank you so much

**Comment by sowens-csd** [comment]
I've tested on a Samsung Galaxy Tab 10 (tablet) with Android 11. I'll try 13 on a Pixel 6a.

**Comment by sowens-csd** [comment]
Just tried the example app on 13 on a Pixel 6a and it seems to work fine. What issue are you having?
