### ISSUE TITLE
Need guidance when there is "No Speech Detected"

### ISSUE THREAD

**Issue by airwavetechio-gh** [csdcorp/speech_to_text#369]
Hi there, 

On iOS, when talking, the Speech Recognition works fine, but if for some reason nothing is said and the listener is stopped, I get this error as expected:

`FinishSuccessfully with error: ... Code=1110 "No Speech Detected..."`

I've been trying to handle this case but have come up short. This is what I'm trying but I don't know what I'm doing. 

```
 void _transcribeAudio() async {
    print("------- Transcribing audio now");

    bool available = await speech.initialize(
        onError: (error) =>
            print("------ Error initializing speech recognition: $error"));
    if (!available) {
      print("------ Speech recognition is not available on this device");
    }

    final result =
        await speech.listen(localeId: "en_US", onResult: resultListener);
    setState(() {});
  }
```
```
String resultListener(SpeechRecognitionResult result) {
    print(
        'Result listener final: ${result.finalResult}, words: ${result.recognizedWords}, confidence: ${result.confidence}');
    // ignore: unnecessary_null_comparison
    if (result != null) {
      setState(() {
        transcribedAudio =
            result.recognizedWords;
      });
    } else {
      setState(() {
        transcribedAudio =
            "Nothing was said.";
      });
    }
    return transcribedAudio;
  }
  
```

Sorry, this is a bit of pseudocode but hopefully it makes sense.

**Comment by sowens-csd** [comment]
The `resultListener` should only be called when there is a valid result and can't be null. I don't think you should need to do explicit handling for the case where no speech was recognized. You'll be called when there are words available. If you want to inform the user if you were expecting speech then you would do that from the error listener instead. 

Does this help?

**Comment by airwavetechio-gh** [comment]
Totally helps and makes a ton of sense. I ended up not using the error listener, but using state management. Thanks for your response and guidance. I'm still new to Flutter and trying to wrap my head around things.
