### ISSUE TITLE
Getting error when trying to listen in web app in mobile browsers

### ISSUE THREAD

**Issue by vatsa1101** [csdcorp/speech_to_text#370]
NoSuchMethodError: method not found: 'om' (J.bG(a).om is not a function. (In 'J.bG(a).om (a,b,c,d)', 'J.bG(a).om' is undefined))

The above is the error thrown when trying to listen

**Comment by sowens-csd** [comment]
What's the device, OS version and browser you tried it with? Did you test with a local debug version or a deployed version?
