### ISSUE TITLE
String Buffer null

### ISSUE THREAD

**Issue by akhilgorantala** [csdcorp/speech_to_text#371]
when i try to print val.recognizedWords am getting the values but when i try to print string buffer no value is getting printed.
![Screenshot 2023-03-01 182351](https://user-images.githubusercontent.com/75612659/222444284-3b6dc177-c478-4301-a654-b8d8af584a0c.png)

**Comment by sowens-csd** [comment]
Could you provide a code snippet showing what you're doing and the log output from the plugin. You can get the log output by adding `debugLogging: true` on the `initialize` call. Is your comment about your friend's device no working part of the same issue or is it a different issue?

**Comment by sowens-csd** [comment]
Sorry. I'm afraid I don't understand in what case the null appears and which value is null. Can you give me a step by step of the success condition and then a separate step by step of the failure condition?

**Comment by sowens-csd** [comment]
Any update on this?
