### ISSUE TITLE
Question about how to handle waiting for speech, and then leveraging pauseFor

### ISSUE THREAD

**Issue by airwavetechio-gh** [csdcorp/speech_to_text#376]
Hi, 

First off, thank you for this package. It's been working great! 

My question is this: 
Is there a way to wait indefinitely (or even for a static duration, like 10 seconds) for the initial speech to be recognized, and then have the `pauseFor` kick in after that? 

My use case is I want to start auto-capturing when someone lands on a specific route, wait until they start talking, and then auto-stop when there is a pause. 

Surprisingly, my users are having difficulty using a record button, just like their native camera app video functionality, so I've been trying clever ways to try and automate it for them. My apologies if this is more of a UX issue and beyond your scope, but any insights on this would be appreciated. Thanks again.

**Comment by sowens-csd** [comment]
Glad to hear it's been working for you. The plugin doesn't have that behaviour out of the box. 

My first thought would be to start your own timer when you get the first non-final result callback, restart it on each subsequent result and then have it call stop if the timer elapses.

**Comment by sowens-csd** [comment]
Yes, you could try using the error callback to detect that, the event would be 'error_no_match'. or alternately 'error_speech_timeout' if no recognition was attempted.

**Comment by airwavetechio-gh** [comment]
Awesome! I appreciate your help. I'll close the issue but can post an update after the fact in case someone else wants to replicate this behavior.

**Comment by coderof19clc7** [comment]
@sowens-csd although this issue had been closed, I'm still having some problem with it so I want to ask that I try to set pauseFor duration to 30 minutes but when start listen, if user does not say anything, the stt will stop after 5-6s even though the minDuration is 30 minutes. How can I make the stt start listening on the first click and it will keep listening until user makes a second click ?
