### ISSUE TITLE
Plugin not working on Android 13 if I add a package visibility for android.speech.RecognitionService

### ISSUE THREAD

**Issue by raymondlui719** [csdcorp/speech_to_text#377]
As the title suggests:
```
<uses-permission android:name="android.permission.RECORD_AUDIO" />
<uses-permission android:name="android.permission.INTERNET" />
<!-- speech recognition -->
<queries>
    <intent>
        <action android:name="android.speech.RecognitionService" />
    </intent>
</queries>
```
In my Pixel 6 Pro device (Android 13), if I build the app without the above "queries" tag, it's working properly;

But in my another Samsung A20s (Android 11), the "queries" tag is required for the plugin to work.

It seems the requirements have some conflicts, I also checked the below link:
[https://developer.android.com/about/versions/13/behavior-changes-all#speech-service](https://developer.android.com/about/versions/13/behavior-changes-all#speech-service)
are there any workarounds for that?

Here's the version I'm targeting:
minSdkVersion 21
targetSdkVersion 33

Any help would be much appreciated. Thank you very much!

**Comment by sowens-csd** [comment]
What happens on the Pixel 6 Pro if you build it with the queries tag?

**Comment by sowens-csd** [comment]
Also, you included a link to the a13 behaviour changes but I don't see anything in that linked content about the query. Did you see a relevant issue documented?

**Comment by raymondlui719** [comment]
I don't have the Pixel 6 Pro on my hands right now, I will give you the error log tomorrow.
But if I build it with the queries tag, the plugin returns an error right after I call the listen method.
As I recall, the error code is 12 (ERROR_LANGUAGE_NOT_SUPPORTED), but I will confirm the behavior tomorrow.

**Comment by sowens-csd** [comment]
Thanks, I would be very surprised if that changed based on the query tag but stranger things have happened. Please let me know.

**Comment by raymondlui719** [comment]
So I got the error logs from the Pixel phone now, I am calling speech.initialize with debugLogging = true, and the supported locales for this device is en_HK. Also I didn't specify the localeId when I called speech.listen.

Here are the outputs with and without the query tag:
With query tag:
```
03-16 10:52:54.112  3754  3754 D SpeechToTextPlugin: Start listening
03-16 10:52:54.112  3754  3754 D SpeechToTextPlugin: setupRecognizerIntent
03-16 10:52:54.112  3754  3754 D SpeechToTextPlugin: Notify status:listening
03-16 10:52:54.112  3754  3754 D SpeechToTextPlugin: Start listening done
03-16 10:52:54.114 13045 13045 I AiAi    : AiAiSpeechRecognitionService#onStartListening
03-16 10:52:54.117 13045 13045 I AiAiSpeechRecognition: [AiAi RecognitionService] session start logged
03-16 10:52:54.117 13045 13045 I AiAiSpeechRecognition: [AiAi RecognitionService] prefer offline logged
03-16 10:52:54.117 13045 13045 I SodaSpeechRecognizer: Offline recognizer - start listening
03-16 10:52:54.117 13045 13045 I SodaSpeechRecognizer: Initialize Soda [locale: en-HK]
03-16 10:52:54.147 13045 13200 E SodaSpeechRecognizer: Failed to get language pack of required locale: error 12
03-16 10:52:54.147 13045 13200 I AiAiSpeechRecognition: [AiAi RecognitionService] mic close logged
03-16 10:52:54.149  3754  3754 D SpeechToTextPlugin: rmsDB -2.0 / -2.0
03-16 10:52:54.149 13045 13114 I AiAiSpeechRecognition: [AiAi RecognitionService] session end logged
03-16 10:52:54.149 13045 13114 I AiAiSpeechRecognition: kbq: Locale not supported
03-16 10:52:54.149 13045 13114 I AiAiSpeechRecognition: 	at kxv.a(PG:13)
03-16 10:52:54.149 13045 13114 I AiAiSpeechRecognition: 	at pdd.a(PG:4)
03-16 10:52:54.149 13045 13114 I AiAiSpeechRecognition: 	at pcp.e(PG:2)
03-16 10:52:54.149 13045 13114 I AiAiSpeechRecognition: 	at pcr.run(PG:9)
03-16 10:52:54.149 13045 13114 I AiAiSpeechRecognition: 	at koq.run(PG:1)
03-16 10:52:54.149 13045 13114 I AiAiSpeechRecognition: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
03-16 10:52:54.149 13045 13114 I AiAiSpeechRecognition: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
03-16 10:52:54.149 13045 13114 I AiAiSpeechRecognition: 	at jsr.run(PG:54)
03-16 10:52:54.149 13045 13114 I AiAiSpeechRecognition: 	at java.lang.Thread.run(Thread.java:1012)
03-16 10:52:54.149 13045 13114 I AiAiSpeechRecognition: 	at kot.run(PG:6)
03-16 10:52:54.149  3754  3754 D SpeechToTextPlugin: Error 12 after start at 37 -2.0 / -2.0
03-16 10:52:54.149  3754  3754 D SpeechToTextPlugin: Notify status:notListening
03-16 10:52:54.149  3754  3754 D SpeechToTextPlugin: Notify status:doneNoResult
```

Without query tag:
```
03-16 10:58:37.230  5359  5359 D SpeechToTextPlugin: Received extra language broadcast
03-16 10:58:37.230  5359  5359 D SpeechToTextPlugin: No extra supported languages
03-16 10:58:37.237  5359  5359 D SpeechToTextPlugin: Start listening
03-16 10:58:37.237  5359  5359 D SpeechToTextPlugin: setupRecognizerIntent
03-16 10:58:37.237  5359  5359 D SpeechToTextPlugin: Notify status:listening
03-16 10:58:37.237  5359  5359 D SpeechToTextPlugin: Start listening done
03-16 10:58:37.237  5359  5359 D SpeechToTextPlugin: In RecognizerIntent apply
03-16 10:58:37.237  5359  5359 D SpeechToTextPlugin: put model
03-16 10:58:37.237  5359  5359 D SpeechToTextPlugin: put package
03-16 10:58:37.237  5359  5359 D SpeechToTextPlugin: put partial
03-16 10:58:37.290 13342 13342 I NetworkSpeechRecognizer: Online recognizer - start listening
03-16 10:58:37.290 13342 13342 I SodaSpeechRecognizer: Offline recognizer - start listening
03-16 10:58:37.290 13342 13342 I SodaSpeechRecognizer: Initialize Soda [locale: en-HK]
03-16 10:58:37.300 13342 13366 E SodaSpeechRecognizer: Failed to get language pack of required locale: error 12
03-16 10:58:37.379  5359  5359 D SpeechToTextPlugin: rmsDB -2.0 / -2.0
03-16 10:58:37.499  5359  5359 D SpeechToTextPlugin: rmsDB -2.0 / -0.31999993
03-16 10:58:37.518  5359  5359 D SpeechToTextPlugin: rmsDB -2.0 / -0.31999993
03-16 10:58:37.539  5359  5359 D SpeechToTextPlugin: rmsDB -2.0 / 0.16000009
...
03-16 10:58:38.568  5359  5359 D SpeechToTextPlugin: Stop listening
03-16 10:58:38.568  5359  5359 D SpeechToTextPlugin: Notify status:notListening
03-16 10:58:38.568  5359  5359 D SpeechToTextPlugin: Notify status:doneNoResult
03-16 10:58:38.568  5359  5359 D SpeechToTextPlugin: Stop listening done
03-16 10:58:38.598  5359  5359 D SpeechToTextPlugin: rmsDB -2.0 / 6.76
03-16 10:58:38.598  5359  5359 D SpeechToTextPlugin: rmsDB -2.0 / 6.76
03-16 10:58:38.599  5359  5359 D SpeechToTextPlugin: rmsDB -2.0 / 6.76
03-16 10:58:38.630  5359  5359 D SpeechToTextPlugin: Error 7 after start at 1393 -2.0 / 6.76
```

The interesting part is that the error 12 happened for both case, but the plugin is working without the query tag but not with the query tag.

**Comment by sowens-csd** [comment]
Thanks for the details, this is really helpful. Android really makes my head hurt sometimes. 

Is the log with the query tag complete? I ask because the `Received extra language broadcast` is not there in the query tag case. 

It definitely seems like two different recognizers are being used in the two cases. The query tag should only indicate if the app is allowed to query for a recognizer intent. Without it asking for a recognizer should not be permitted. Clearly in Android 13 that is not happening. I'll look for documentation on this and try it on my Pixel 6a.

**Comment by raymondlui719** [comment]
Thank you for your response.

The above logs were supposed to be the logs starting from calling speech.listen to the point that the plugin stops listening or throws an exception, so I am not sure whether `Received extra language broadcast` is useful for you. Let's take `SpeechToTextPlugin: Start listening` line as the entry point for both cases then.

I am hoping you can reproduce this issue in your device as well because this issue is making my head hurt so much.

Thank you again.

**Comment by sowens-csd** [comment]
Unfortunately I can't reproduce your results on my Pixel6a. For me it is working either with or without the queries entry. My theory is that it is locale or language specific. It's working for me probably because I have a very simple default language selection on the device. 

I have found a relevant looking thread. Could you try the troubleshooting steps outlined here: https://stackoverflow.com/questions/69827554/why-did-my-android-app-using-speechrecognizer-stop-working-after-upgrading-to-an

In particular this section:
> This can be fixed by the user of the device, by going into Settings > Apps > Default apps > Digital assistant app > Voice input and changing it back to "Speech services by Google" (you may first need to update Speech services by Google via the Play Store). Once this is done, Android System Intelligence will disappear from the list of options in that setting, suggesting it was never intended to be chosen in the first place

**Comment by sowens-csd** [comment]
Any updates? Did the troubleshooting steps help?
