### ISSUE TITLE
Get Audio

### ISSUE THREAD

**Issue by Tryad0** [csdcorp/speech_to_text#378]
Is there any feature or possibility to get the recorded audio? I don't want to record an extra audio file but get the already recognized audio as file (Bytes etc.).

Thanks for your awesome work!

**Comment by sowens-csd** [comment]
No, there isn't. As far as I've been able to tell this isn't possible in Android, it is possible for iOS but I haven't implemented it yet as I've preferred to only offer cross platform features. However I will probably do the iOS implementation given how many people need this feature.

**Comment by nixuan** [comment]
@sowens-csd 

I also need this function,  can you offer some instructions form ios ?

Thanks for your awesome work!
