### ISSUE TITLE
Speech to text do not working on person name

### ISSUE THREAD

**Issue by wildanlsfs** [csdcorp/speech_to_text#379]
hello, i'm currently working on an education system that has a dialogue practice in english, but in Indonesia we have an uncommon name that need to put on the script. 

for example ,

Hello, My name is Wildan Lutfi

the speech to text will write it like 

Hello, My name is Will done lutfi

which is wrong, 

in my app we are checking word by word so it will cause and error after the world Wildan lutfi because the 'Will done lutfi"

can you please tell me how to solve this problem?

**Comment by sowens-csd** [comment]
Unfortunately there isn't a good solution for proper nouns or other words that the recognizer doesn't know.
