### ISSUE TITLE
Without noticing the listening event, speech.isListening does not work.

### ISSUE THREAD

**Issue by huynhphu-pufu** [csdcorp/speech_to_text#38]
Hi admins. I'm using your package for my project. I detected a occur when speech listening. That is when I don't speak anything, I received twice onError (I set print() inside onError). And I notice that this error occurs after I run for the second time onwards. I don't know how to explain it to you, sort of it doesn't get stopped listening. Or you can test with your example project, with your example I see Text("I'm listening...", style: TextStyle(fontWeight: FontWeight.bold),) instead of Text("Not listening", style: TextStyle(fontWeight: FontWeight.bold),).
So, I hope you can understand occur which I am getting, and help me to solve it. Thanks for your reading.

**Comment by sowens-csd** [comment]
I'll try it in the sample app. Just to be sure I understand to reproduce I
1) Initialize
2) Start listening
3) say nothing until error occurs (I should see two errors)
4) Cancel or stop
5) Try to start listening again?

**Comment by huynhphu-pufu** [comment]
Please forgive me for the late reply. I have encountered the following error:
1. Initialize
2. Start listening
3. Say something => first time ok
4. Cancel or stop
5. Initialize
6. Start listening 
7. Say nothing utils error occurs (I logged and saw 2 times print)
8. I saw Text("I'm listening...") although it has stopped listening (status is notListening at 7th step)

**Comment by sowens-csd** [comment]
Thanks, I see what's happening now. I'm not currently canceling the session when an error occurs and probably should be, however this will break backwards compatibility in some cases. I think I'll add a cancelOnError option to the listen method to enable this behaviour and improve the documentation.

**Comment by huynhphu-pufu** [comment]
I think you'll have a perfect solution for this. I'm looking forward to new updates on pub.dev from you. And thanks for your supports.
As for my project currently, I have temporarily set a countdowntimer to cancel listening for this case.

**Comment by sowens-csd** [comment]
1.0.0 is now on pub.dev.

**Comment by manhlhvm** [comment]
> Please forgive me for the late reply. I have encountered the following error:
> 
> 1. Initialize
> 2. Start listening
> 3. Say something => first time ok
> 4. Cancel or stop
> 5. Initialize
> 6. Start listening
> 7. Say nothing utils error occurs (I logged and saw 2 times print)
> 8. I saw Text("I'm listening...") although it has stopped listening (status is notListening at 7th step)

have solution for this ? I same error at version 3.2.0
@override
  void dispose() {
    print("dispose voice search");
    speech.stop();
    speech.cancel();
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
    if (_hasSpeech == false) {
      initSpeechState();
    }
  }

  Future<void> initSpeechState() async {
    var hasSpeech = await speech.initialize(
      onError: errorListener,
      onStatus: statusListener,
      debugLogging: true,
      finalTimeout: Duration(milliseconds: 2),
      options: [
        SpeechToText.androidAlwaysUseStop,
      ],
    );

    if (!mounted) return;

    setState(() {
      _hasSpeech = hasSpeech;
    });
    startListening();
  }
  void startListening() {
    print("_currentLocaleId: $_currentLocaleId");
    lastWords = '';
    lastError = '';
    speech.listen(
      onResult: resultListener,
      listenFor: Duration(seconds: 5),
      pauseFor: Duration(seconds: 5),
      partialResults: false,
      localeId: _currentLocaleId,
      onSoundLevelChange: soundLevelListener,
      cancelOnError: true,
      listenMode: ListenMode.confirmation,
    );
    setState(() {});
  }
