### ISSUE TITLE
Not working on iOS

### ISSUE THREAD

**Issue by shaheer-hybreed** [csdcorp/speech_to_text#380]
I am using the latest version of the package. It perfectly working on Web and Android but when comes to iOS and Mac it is not working even the mic is not starting (no orange dot on control center). I don't know why this happens . I verified eveything is latest including xcode flutter cocopods.

Anyways kudos 👏  for the hardwork behind this package

**Comment by coderof19clc7** [comment]
@shaheer-hybreed  did you solve it ? I'm having the same issue

**Comment by shaheer-hybreed** [comment]
> @shaheer-hybreed  did you solve it ? I'm having the same issue

Nop I am waiting for the developer statement

**Comment by sowens-csd** [comment]
Are you using the example app? What version of iOS and what device are you testing with? 

There is currently no support for speech recognition on the Mac. The package is supported but it always reports that there is no recognition available.

**Comment by shaheer-hybreed** [comment]
> Are you using the example app? What version of iOS and what device are you testing with? 
> 
> There is currently no support for speech recognition on the Mac. The package is supported but it always reports that there is no recognition available. 

iOS 16.2 testing on simulator 

This is output when I tested the sample app from guthub ![IMG-20230330-WA0072.jpg](https://user-images.githubusercontent.com/89133344/228874574-831c932d-bfa6-4acb-aaa8-645e99f3effc.jpg)

**Comment by KristijanZic** [comment]
> > I have had very mixed success testing on the simulator. Apple keeps breaking the simulator usage in various subtle ways so I've kind of given up on it. Try it on a real device and let me know.
> 
> Okay I will update here once done

Any update to report? I'm facing the same issue on the simulator.

**Comment by shaheer-hybreed** [comment]
> > > I have had very mixed success testing on the simulator. Apple keeps breaking the simulator usage in various subtle ways so I've kind of given up on it. Try it on a real device and let me know.
> > 
> > Okay I will update here once done
> 
> Any update to report? I'm facing the same issue on the simulator.

Nop, 
I didn't tested this on real device , need to reach at my studio to check this ,these days are iam away from worskapce, 

on simulator not working right now

**Comment by johnareid54** [comment]
I have been watching this issue, hoping that solution will be posted - why has it been closed?

**Comment by sowens-csd** [comment]
I'm just updating the README now for a new release. I had given up on simulator testing but did just find an answer. I still recommend testing on real devices but it appears that it is possible to get speech to text to work on a simulator. 

If speech recognition is not working on your simulator try going to the Settings app in the simulator:
Accessibility -> Spoken content -> Voices

From there select any language and any speaker and it should download to the device. After that speech 
recognition should work on the simulator.

**Comment by Melbourneandrew** [comment]
It may be broken again. iOS 16.2 simulator gives "error_listened_failed" and "error_retry" when testing with the demo app. I have downloaded multiple English voices and enabled dictation from the General > Keyboard menu. Still no luck. 

Perhaps this issue can be reopened?
