### ISSUE TITLE
Bluetooth headset disconnects randomly on Android

### ISSUE THREAD

**Issue by kenwen** [csdcorp/speech_to_text#381]
Getting an interesting bug when I try to run my app on Android

It starts speech recognition okay but then randomly stops it

Checking the logs, I usually get an audio focus change listener message such as below

W/FlutterWebRTCPlugin(18373): audioFocusChangeListener [BluetoothHeadset(name=Google Pixel Watch 005P), Speakerphone(name=Speakerphone), Earpiece(name=Earpiece)] BluetoothHeadset(name=Google Pixel Watch 005P)

and then a message saying speech recognition stops. This happens randomly :-/

```
D/BluetoothHeadset(18373): Proxy object connected
D/BluetoothHeadset(18373): startVoiceRecognition()
D/BluetoothHeadset(18373): startVoiceRecognition()
D/BluetoothHeadset(18373): startVoiceRecognition()
W/FlutterWebRTCPlugin(18373): audioFocusChangeListener [BluetoothHeadset(name=Google Pixel Watch 005P), Speakerphone(name=Speakerphone), Earpiece(name=Earpiece)] BluetoothHeadset(name=Google Pixel Watch 005P)
W/FlutterWebRTCPlugin(18373): audioFocusChangeListener [BluetoothHeadset(name=Google Pixel Watch 005P), Speakerphone(name=Speakerphone), Earpiece(name=Earpiece)] BluetoothHeadset(name=Google Pixel Watch 005P)
D/BluetoothHeadset(18373): stopVoiceRecognition()
W/FlutterWebRTCPlugin(18373): audioFocusChangeListener [Speakerphone(name=Speakerphone), Earpiece(name=Earpiece)] Speakerphone(name=Speakerphone)
W/FlutterWebRTCPlugin(18373): audioFocusChangeListener [Speakerphone(name=Speakerphone), Earpiece(name=Earpiece)] Speakerphone(name=Speakerphone)
D/BluetoothHeadset(18373): startVoiceRecognition()
D/BluetoothHeadset(18373): startVoiceRecognition()
D/BluetoothHeadset(18373): startVoiceRecognition()
W/FlutterWebRTCPlugin(18373): audioFocusChangeListener [BluetoothHeadset(name=Google Pixel Watch 005P), Speakerphone(name=Speakerphone), Earpiece(name=Earpiece)] BluetoothHeadset(name=Google Pixel Watch 005P)
```

**Comment by sowens-csd** [comment]
From a quick glance I don't see any speech to text related log messages there. Looks like your app uses the Flutter WebRTC plugin as well as speech to text? It seems like they might be fighting over ownership of the bluetooth headset. Do you expect both plugins to be active at the same time? Or should only one of them be in use at any given time?

**Comment by kenwen** [comment]
The strange thing is, which I forgot to add, I'm not using a bluetooth headset!

I'm starting an app without webRTC so will experiment and see if I experience the same on my Pixel

**Comment by sowens-csd** [comment]
Any updates on this? If not I'll close it.
