### ISSUE TITLE
Service protocol connection closed.

### ISSUE THREAD

**Issue by Shinjou** [csdcorp/speech_to_text#384]
I created a new Flutter project. Then I copied and pasted the speech_to_text 6.1.1 example to main.dart. I then
1. flutter run --verbose
2. (the screen came up perfectly)
3. I pressed "initialize"
4. system crashed. (Service protocol connection closed. Lost connection to device.)
The following is my Flutter version:
Flutter 3.7.10 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4b12645012 (9 days ago) • 2023-04-03 17:46:48 -0700
Engine • revision ec975089ac
Tools • Dart 2.19.6 • DevTools 2.20.1
Can you help me find out what went wrong? Thanks.

**Comment by sowens-csd** [comment]
Please read the setup instructions in the README for both iOS and Android. There are configuration changes you need to make to a new project.

**Comment by Shinjou** [comment]
Thank you so much, Stephen. It works for me. Great job!

Stephen Owens ***@***.***> 於 2023年4月12日 週三 上午10:31寫道：
