### ISSUE TITLE
Bluetooth microphone

### ISSUE THREAD

**Issue by arithai** [csdcorp/speech_to_text#385]
Flutter speech to text library is good. But I don't know how to use voice recognizer by bluetooth microphone. No example for bluetooth.
Do we need a special bluetooth microphone for test?

**Comment by toknT** [comment]
Same issue , I connect a extra usb micrphone,this library seem to only get the voice from the microphone on smartphone. And   I cant't find any params like `VoiceResource` to change it listen other device's voice.

**Comment by sowens-csd** [comment]
Bluetooth should work with no special configuration required on both iOS and Android. 

A USB microphone would be a different issue. On iOS at least when a microphone is plugged into the device it becomes the new primary so I don't think there's anything special required to support it. I'm less confident about Android. The plugin doesn't have any special handling for external microphones other than Bluetooth.

**Comment by sowens-csd** [comment]
Any updates on this? If not I'll close it.

**Comment by toknT** [comment]
> Any updates on this? If not I'll close it.

Yeah. Sorry I can't access github for some days
