### ISSUE TITLE
_pauseFor ,ListenFor not working properly

### ISSUE THREAD

**Issue by Appstute-Prerna** [csdcorp/speech_to_text#386]
speech.listen(
          pauseFor: Duration(seconds: 60),
          listenFor: Duration(minutes: 30),
          onResult: resultListener,
          listenMode: ListenMode.confirmation,
          onDevice: true,
          partialResults: false);
          
          
          Given parameters not holding pause for given seconds. Sops immediately.

**Comment by sowens-csd** [comment]
If this is on Android please read the README troubleshooting section.
