### ISSUE TITLE
Should bluetooth headsets work on iOS?

### ISSUE THREAD

**Issue by darekmm** [csdcorp/speech_to_text#388]
Tried with both AirPods Pro 2 and other external bluetooth microphones. IOS v 16.3.1, iPhone Pro 13 - tested on device.
Recognition works with the device microphone, but as soon as a Bluetooth mic is connected, no speech is recognised.

` FinishSuccessfully with error: Optional(Error Domain=kAFAssistantErrorDomain Code=1110 "No speech detected" UserInfo={NSLocalizedDescription=No speech detected})`

Disabling bluetooth makes it work again.

**Comment by sowens-csd** [comment]
It has worked previously. Can you reproduce it in the example app? If so I'll try it again.

**Comment by sowens-csd** [comment]
Any update on this?
