### ISSUE TITLE
Package not working in mobile browser.

### ISSUE THREAD

**Issue by aiet7** [csdcorp/speech_to_text#389]
The speech_to_text is not working on any mobile browser.  It works only on desktop browser....  When I click on the mic button in safari on my iphone, it doesnt capture anything.  What is the issue?

**Comment by aiet7** [comment]
???????????

**Comment by sowens-csd** [comment]
Have you checked if the mobile browsers you are testing support speech recognition? Speech to text depends on the browser's implementation of the speech API. If it's not available then STT won't work.
