### ISSUE TITLE
error_audio_error

### ISSUE THREAD

**Issue by FraglyG** [csdcorp/speech_to_text#391]
Getting this `SpeechRecognitionError msg: error_audio_error, permanent: true` error, running on android

```
I/flutter (26869): listening
D/TTS     (26869): Utterance ID has started: 4c8e1daf-cd47-4aed-8791-7946dc509fbd
I/flutter (26869): notListening
I/flutter (26869): done
I/flutter (26869): SpeechRecognitionError msg: error_audio_error, permanent: true
D/ViewRootImpl@6ba5018[MainActivity](26869): ViewPostIme pointer 0
D/TTS     (26869): Utterance ID has completed: 4c8e1daf-cd47-4aed-8791-7946dc509fbd
D/ViewRootImpl@6ba5018[MainActivity](26869): ViewPostIme pointer 1
I/flutter (26869): stop listening
```

**Comment by sowens-csd** [comment]
Are you running on an emulator or a physical device?

**Comment by FraglyG** [comment]
I was running on a physical device here

**Comment by sowens-csd** [comment]
What was the device type and the Android version? Can you reproduce it with the example app?

**Comment by sowens-csd** [comment]
Would be worth doing a run with `debugLogging: true` on the `initialize` method. It might provide more detail.

**Comment by FraglyG** [comment]
I was using Huawei first until I learned that it doesn't function on Huawei devices, I then ran it on a Samsung Galaxy S8, running on Android version 9.

I'll try running it with `debugLogging: true` tomorrow and see if I can come up with anything, if that fails I'll send an example app, thank you for your help!

**Comment by FraglyG** [comment]
Okay, I figured it out
I had wake-word detection and that was recording in the background causing it to not work, I saw this issue with other users as well but I completely overlooked wake-word detection as a culpirate, in hindsight it should've been obvious lol

I fixed it by just disabled wake-word detection when a wake word was detected, before enabling speech to text, then I just enable it again after speech to text is finished.

Thanks for your help!
