### ISSUE TITLE
Permissions correct, but still Error: SpeechRecognitionError msg: error_permission

### ISSUE THREAD

**Issue by bbottema** [csdcorp/speech_to_text#393]
So I double/triple checked the permissions in my manifest, android microphone settings and clean install etc. But the listening process immediately finishes, with the following message:

> D/SpeechToTextPlugin( 6064): Start initialize
> D/SpeechToTextPlugin( 6064): Checked permission
> D/SpeechToTextPlugin( 6064): has permission, completing
> D/SpeechToTextPlugin( 6064): completeInitialize
> D/SpeechToTextPlugin( 6064): Testing recognition availability
> D/SpeechToTextPlugin( 6064): sending result
> D/SpeechToTextPlugin( 6064): leaving complete
> D/SpeechToTextPlugin( 6064): leaving initializeIfPermitted
> D/SpeechToTextPlugin( 6064): Start listening
> D/SpeechToTextPlugin( 6064): setupRecognizerIntent
> D/SpeechToTextPlugin( 6064): Notify status:listening
> D/SpeechToTextPlugin( 6064): Start listening done
> D/SpeechToTextPlugin( 6064): Error 9 after start at 3 1000.0 / -100.0
> D/SpeechToTextPlugin( 6064): Notify status:notListening
> D/SpeechToTextPlugin( 6064): Notify status:doneNoResult
> I/flutter ( 6064): Status: listening
> I/flutter ( 6064): Status: notListening
> I/flutter ( 6064): Status: done
> I/flutter ( 6064): Error: SpeechRecognitionError msg: error_permission, permanent: true

How do I get this to work, I'm at a loss.

Versions:
speech_to_text: 6.1.1
Flutter: 3.10.1
DevTools: 2.23.1
Device: virtual device, Pixel 4

**Comment by sowens-csd** [comment]
Try it on a real device. Although it is apparently possible to set it up on a virtual device I have had very mixed success doing so and don't recommend it.

**Comment by bbottema** [comment]
It works on my S22 real device. I guess emulators are still crippled, nearly ten years later (since I started dipping into mobile development).
