### ISSUE TITLE
Error status never cleared, making .hasError and .lastError unreliable.

### ISSUE THREAD

**Issue by bbottema** [csdcorp/speech_to_text#395]
The `.hasError` and `.lastError` properties in the `SpeechToText` class of the `speech_to_text` package are never explicitly reset, which may lead to potential issues in error handling.

**Expected Behavior:**
After an error has been handled or a new listening session has started, the `.lastError` property should be reset to null, and consequently, the `.hasError` property should be reset to false.

**Current Behavior:**
Once an error occurs during a listening session, the `.lastError` property is set and remains even if a new listening session starts. As a result, the `.hasError` property, which checks whether `.lastError` is not null, also remains true.

**Steps to Reproduce:**

1. Start a listening session where an error is expected to occur (e.g., with no microphone access).
2. Check the `.hasError` and `.lastError` properties after the error occurs. They should now reflect the error.
3. Start a new listening session without any errors.
4. Check the `.hasError` and `.lastError` properties again. They still reflect the previous error, even though a new session has started and completed without errors.

**Suggested Fix:**
An explicit reset or clear function for the `.hasError` and `.lastError` properties could be beneficial. This could be implemented in the `listen` method at the start of a new listening session or as a separate public method. This would give users better control over the error state and ensure that old errors do not affect new sessions.

**Comment by sowens-csd** [comment]
Good suggestion, thanks.

**Comment by sowens-csd** [comment]
The error status is cleared whenever `listen` is called. This is in version 6.2.0.
