### ISSUE TITLE
Audio mutes after SpeechToText instance stop.

### ISSUE THREAD

**Issue by likwifi** [csdcorp/speech_to_text#396]
Hello,
I'm using flutter with unity view.
After calling SpeechToText instance stop audio from Unity view is gone.

I guess it has something to do with audio output.
Appreciate if you can suggest any tips to fix this.

**Comment by sowens-csd** [comment]
I'm sorry, this isn't enough information for me to provide any help. It sounds like you're having some interaction between various audio output? I can certainly see there could be collisions in sound handling between Unity and STT as both would likely want control of the shared audio channel. I usually recommend that you fully stop STT before starting any audio from another plugin and vice versa.
