### ISSUE TITLE
Feature Request: detect language

### ISSUE THREAD

**Issue by colingoldberg** [csdcorp/speech_to_text#397]
My apologies if this feature request is in the wrong place - please advise if there is another way to submit feature requests.
 (as opposed to issues).

In my newly-built app (which I have successfully tested on a physical Android phone - thank you for this marvelous package), I provide a microphone and text field as two ways to "enter" words to be handled by my backend service. The backend service can handle words in English or Hebrew. Of course, the text field keyboard allows me to switch the language on my phone. 

But if I want to use voice only, I would like to be able to have the ability to automatically detect which language is being spoken - English or Hebrew, and then have the package produce text in the appropriate language.

I see that a DetectLanguage method is listed in another speech recognition package (https://pub.dev/packages/speech_recognition), which is shown as "Discontinued". I see that this capability is also shown in the Google Speech To Text API V2 (https://cloud.google.com/speech-to-text/v2/docs/multiple-languages). So this has been done before. How much would it take to include it in this package?

Once again, thank you for a great package, that is so very very useful.

Regards
Colin Goldberg

**Comment by colingoldberg** [comment]
How about the discontinued speech_recognition package - how did they do it (assuming it worked)?

It would be a useful addition to your package if/when you add it.

**Comment by sowens-csd** [comment]
I don't see a DetectLanguage method in that package, could you point me at it?
