### ISSUE TITLE
Stop Button dont work on my Galaxy s10 +

### ISSUE THREAD

**Issue by mpigorini** [csdcorp/speech_to_text#40]
Running the example I realized that the stop button (speech.stop ()), does not work on my galaxy s10 +, but it does work on a galaxy s8

**Comment by sowens-csd** [comment]
Do you see any errors or anything in the log? What is difference in behaviour between the S8 and the S10? What are the Android versions on those two devices?

**Comment by mpigorini** [comment]
I tried and in s8 it works fine, but in my s10 the stop does nothing. Continue recording until you say something or timeout. The timeout varible "speech.listen(listenFor: Duration)" not work on my s10 too. The s8 has android 8 and my s10 has android 10. I dont see any error on logs

**Comment by sowens-csd** [comment]
There's a new 1.0.0 release on pub.dev. Some of the behaviours have been moved to the main thread. That might help with the issue you're seeing it. Could you try that version and let me know?

**Comment by mpigorini** [comment]
I've tried it and I still have the same behavior despite being called the speech.stop () function. The microphone is still active

**Comment by sowens-csd** [comment]
I'm still a bit unclear on what happens on the S10. Despite calling stop() are you still getting speech recognition results in the callback? I'd like to understand how you can tell that the microphone is still active. I'm going to add some more logging around the start and stop call and ask you to try a new version.

**Comment by sowens-csd** [comment]
The extra logging is there now, if you run in debug mode you will see logs indicating whether it called stop (at the Android intent level) and whether it completed.

**Comment by sowens-csd** [comment]
The latest version of the plugin in the repo has a new architecture for interacting with the main loop. It may also help with this issue. Let me know if you have time to try it out.

**Comment by mpigorini** [comment]
hello, Sorry for my flashing, I have tried the latest version and continued with the same problem on my device. After pressing stop if I say something the microphone captures it as if it was active.

**Comment by sowens-csd** [comment]
Can you provide the steps to reproduce. In particular what happens that you think is incorrect? You say 'the microphone captures it'. Is the onResult callback being notified with partial word matches? With a final match? Is this with the example app or some of your own code? If it is your own code can you try it with the example app and let me know if you see the same behaviour?

**Comment by sowens-csd** [comment]
Closing this as I don't have enough information to figure out what's happening. Please open a new issue if you are having problems.
