### ISSUE TITLE
SpeechRecognitionError on the simulator iPhone SE/14/14pro, but working on a real iPhone device

### ISSUE THREAD

**Issue by 8088boy** [csdcorp/speech_to_text#401]
Hi everyone,

I am having an issue with my speech recognition function. It works perfectly fine on a real iPhone device, but it won't work on the simulator iPhone SE/14/14 Pro.

```dart
  /// This has to happen only once per app
  Future<void> _initSpeech() async {
    _speechEnabled = await _speech.initialize(
      onStatus: (val) => debugPrint('🎤 onStatus: $val'),
      // onError: (val) => print('🎤 onError: $val'),
      onError: errorListener,
    );
    setState(() {
    });
  }
  void errorListener(SpeechRecognitionError error) {
    debugPrint('❌ ${error.errorMsg.toString()}');
  }
```
Console log for iOS simulator, **FAILED**
![image](https://github.com/csdcorp/speech_to_text/assets/95098546/821cb5a3-8f7b-42f7-b82c-938bab8a33d2)

Console log for the real iPhone device, **WORKING**
![image](https://github.com/csdcorp/speech_to_text/assets/95098546/b8392b86-5afa-4d03-baa0-d749a4037a71)
 
Package version: speech_to_text: ^6.1.1
Env: Flutter 3.10.5 on MacOS 12.6.6, Dart 3.0.5, Xcode 14.2
Xcode deployment Info : iOS 12.0

I have tried everything I can think of, including checking the permissions and making sure the microphone is enabled in the simulator.

If anyone has any ideas or suggestions on how to debug this issue, I would greatly appreciate it. Thank you in advance for your help!

**Comment by sowens-csd** [comment]
Yes, I'm afraid I've given up on using simulators for this. I'll add that to the README because it's caught quite a few people.

**Comment by 8088boy** [comment]
> Yes, I'm afraid I've given up on using simulators for this. I'll add that to the README because it's caught quite a few people.

OK. I see. It would be very helpful to everyone.
