### ISSUE TITLE
Cannot control stop delay while recording

### ISSUE THREAD

**Issue by mikron123** [csdcorp/speech_to_text#404]
There is no parameter to direct the listen function to stop after more than 1 second of silence.

**Comment by sowens-csd** [comment]
I think `pauseFor` is the parameter you're looking for?

**Comment by mikron123** [comment]
@sowens-csd  No, pauseFor only delays the waiting time on the start. Users have been complaining that while talking, if the user pauses for more than 1 second, it stops listening. And now I've seen that in the package's readme it says that it cannot be changed, and that's about it.
It's a shame since it's a major UX problem which can make a product annoying to some people.

**Comment by sowens-csd** [comment]
`pauseFor` ensures that the system never pauses for longer than the specified time. Android unfortunately has a shorter default that cannot be overridden.

**Comment by onursahindur** [comment]
@mikron123 Please have a look at my comment here:
https://github.com/csdcorp/speech_to_text/issues/429#issuecomment-1714551115
