### ISSUE TITLE
Request nearby devices permission

### ISSUE THREAD

**Issue by KrKgg** [csdcorp/speech_to_text#405]
This  my code`  initSpeechToText() async {
    try {
      await speech.value.initialize(
        onStatus: statusListener,
        onError: errorListner,
      );
    } catch (e) {
      ShowToastDialog.showToast(e.toString());
    }
  }
    @override
  void onReady() {
    super.onReady();
    initSpeechToText();
  }
`

it show request permission allow to find, connect to and determine the relative position of nearby devices. and when i don't initSpeechToText in onReady it doesn't show Request

**Comment by doppio** [comment]
Was there a solution to this? 🤔
