### ISSUE TITLE
System Exception on Speech to Text init

### ISSUE THREAD

**Issue by Terranic** [csdcorp/speech_to_text#407]
Hi all,

I just updated to the most recent version and now getting this fatal exception on andoird "Pixel 6 API 30" Emulator:

using
  speech_to_text: ^6.2.0

`D/AndroidRuntime( 3922): Shutting down VM
E/AndroidRuntime( 3922): FATAL EXCEPTION: main
E/AndroidRuntime( 3922): Process: de.tsst.ncheck, PID: 3922
E/AndroidRuntime( 3922): java.lang.NoSuchMethodError: No static method isOnDeviceRecognitionAvailable(Landroid/content/Context;)Z in class Landroid/speech/SpeechRecognizer; or its super classes (declaration of 'android.speech.SpeechRecognizer' appears in /system/framework/framework.jar!classes2.dex)
E/AndroidRuntime( 3922): 	at com.csdcorp.speech_to_text.SpeechToTextPlugin.completeInitialize(SpeechToTextPlugin.kt:496)
E/AndroidRuntime( 3922): 	at com.csdcorp.speech_to_text.SpeechToTextPlugin.onRequestPermissionsResult(SpeechToTextPlugin.kt:658)
E/AndroidRuntime( 3922): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:781)
E/AndroidRuntime( 3922): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:413)
E/AndroidRuntime( 3922): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:820)
E/AndroidRuntime( 3922): 	at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:941)
E/AndroidRuntime( 3922): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8460)
E/AndroidRuntime( 3922): 	at android.app.Activity.dispatchActivityResult(Activity.java:8308)
E/AndroidRuntime( 3922): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5008)
E/AndroidRuntime( 3922): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5056)
E/AndroidRuntime( 3922): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime( 3922): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 3922): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 3922): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime( 3922): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 3922): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime( 3922): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime( 3922): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3922): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime( 3922): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process ( 3922): Sending signal. PID: 3922 SIG: 9
Lost connection to device.
`

**Comment by sowens-csd** [comment]
I think this is related to PR #409. Should be resolved once that is merged. Until then please downgrade to your previous version if you need a build.

**Comment by sowens-csd** [comment]
6.3.0 is published now with #409. Please try it out.
