### ISSUE TITLE
Chromeapp Crash

### ISSUE THREAD

**Issue by selvam920** [csdcorp/speech_to_text#411]
When i run the android app in chromebook it's crashed.

**Comment by sowens-csd** [comment]
I don't know if the plugin supports Chromebooks. Did it used to work? Has the crash started recently?

**Comment by selvam920** [comment]
i checked first time, other plugin is not crashed and also speech recognition did not work

**Comment by sowens-csd** [comment]
What version of Android does it support? Did you try running the sample app on it? What's the log show when it crashes?
