### ISSUE TITLE
Multiple language support ?

### ISSUE THREAD

**Issue by eav-solution** [csdcorp/speech_to_text#414]
Hello author,

I use xiaomi K40 device but after I list all support language I got only language of device.
    bool initSpeechStatus = await speechToText.initialize();
    if (initSpeechStatus) {
      List localeNames = await speechToText.locales();
How I can change to other language without change system language ?
Please help me.

Thanks you.

**Comment by sowens-csd** [comment]
In recent Android releases there seems to be an issue with retrieving the list of supported locales for speech. I'm still investigating. In the meantime you can still switch to any supported language, the plugin just can't provide the language codes for you. That means you will have to provide your own locale list.
