### ISSUE TITLE
No implementation on production but not in development (latest version)

### ISSUE THREAD

**Issue by arisAlexis** [csdcorp/speech_to_text#415]
Hi, I am using version 6.3.0 and the initialize function works fine on android,ios and web locally but when I push the code to production it fails with:

Uncaught MissingPluginException(No implementation found for method initialize on channel plugin.csdcorp.com/speech_to_text)

This makes no sense unless the code hits some http site?

**Comment by sowens-csd** [comment]
What platform are you seeing the message on? 

That message is from the Flutter plugin communication handler, it's not an external http address, just a way of identifying communication channels internally. Is it possible that you tried to call initialize before Flutter platform initialization? I can't think why it would work locally but then fail in a prod release. Does it work locally if you do a release build for local use? Do you use kDebug or kRelease flags in the code to change behaviour?

**Comment by arisAlexis** [comment]
Hi, I am deploying to firebase hosting. There was a similar bug reported in the issues with difference between production and development  #221 and it was resolved by upgrading but maybe the same bug slipped in again? I am initializing Flutter and the speech.initialize call is done much later in the code after the user is logged in etc. Also, it works on mobile both Android and iOS and web locally so the code should be correct I guess?

**Comment by sowens-csd** [comment]
Unfortunately there wasn't a clear cause for #221. Nothing in the upgrade should have fixed it other than maybe general Flutter improvements to the web version. So if you're still getting the no implementation error and only in production then it seems like something is going wrong with the plugin initialization cycle in production. I'm wondering about some type of compiler code optimization or something that is not generating the correct code path in a prod build. That's an absolute wild guess, just trying to think of what could be different. 

Could you try a `profile` build in your development environment and see if that works?

**Comment by sowens-csd** [comment]
Did you get a chance to try a profile build in your dev environment?

**Comment by sowens-csd** [comment]
Any updates on this?
