### ISSUE TITLE
Question about different accents

### ISSUE THREAD

**Issue by dinhan92** [csdcorp/speech_to_text#418]
I want to use this package speech to text in a app for Vietnamese people. However, in Vietnam, there are some regions that use different accents. I wonder if this package can recognize those accents and translate them into text ?

**Comment by sowens-csd** [comment]
If those accents are properly understood by the OS speech recognition capability then they would work the same in speech_to_text. For example if you can use Google Assistant via voice successfully then speech_to_text should work. If the accent cannot be understood by the device then speech_to_text will not work.
