### ISSUE TITLE
[ios] There is a block UI when using with UnityWidget

### ISSUE THREAD

**Issue by dungbk1995** [csdcorp/speech_to_text#419]
**Describe the bug**
There is a gap stop UI when starting listening (`speech_to_text` start listening/stopping).
It seems like there is a block main thread here.
[flutter_unity_widget 2022.2.0](https://pub.dev/packages/flutter_unity_widget)

**To Reproduce**
1. Go to 'Simple Unity Demo'
2. Click on 'Audio button' on the `textBox`
3. See that the `CircularProgressIndicator` is stop loading a little bit.
Note: It doesn't happen at `MenuList` screen since, we don't use `UnityWidget` here.

**Expected behavior**
The block UI will be no longer exist.

**Screenshots**
https://github.com/csdcorp/speech_to_text/assets/20292588/225aaffb-58ac-4496-85a4-c180a2458331

**Unity (please complete the following information):**
 - OS: [iOS]
 - Version [22]

**Smartphone (please complete the following information):**
 - Device: [iPhone11]
 - OS: [iOS15.6]
 - Version [22]

**Additional context**
Source code here: 
https://github.com/dungbk1995/flutter-unity-view-widget/tree/master/example

**Comment by dungbk1995** [comment]
https://github.com/csdcorp/speech_to_text/assets/20292588/225aaffb-58ac-4496-85a4-c180a2458331

**Comment by sowens-csd** [comment]
There was a similar report in issue #374 that I did extensive troubleshooting on a while ago. Have a look at that thread.

**Comment by dungbk1995** [comment]
@sowens-csd Thank you and so sorry for late replying,
This is only happened on `IOs` `android` is working fine!

I will checking #374 and write other simple testing!
I'll update here later...

**Comment by sowens-csd** [comment]
Any update on this?
