### ISSUE TITLE
error type "timeout" should be separated, to identify if input or network problem

### ISSUE THREAD

**Issue by peterweb2005** [csdcorp/speech_to_text#42]
thanks

https://developer.android.com/reference/android/speech/SpeechRecognizer

ERROR_NETWORK_TIMEOUT
Network operation timed out.

ERROR_SPEECH_TIMEOUT
No speech input

**Comment by peterweb2005** [comment]
IE

      case "error_audio_error":
      case "error_client":
      case "error_no_match":
      case "error_speech_timeout":
        return '輸入錯誤'; // input error
      case "error_network":
      case "error_network_timeout":
      case "error_busy":
      case "error_server":
        return '網絡問題'; // network error
      default: // never?
        return '未知問題';

**Comment by sowens-csd** [comment]
Thanks, that's a good catch. I'll patch that and put out a new version.

**Comment by sowens-csd** [comment]
1.1.0 is out now with this fix.
