### ISSUE TITLE
Grdale 8 support?

### ISSUE THREAD

**Issue by sanidhya09** [csdcorp/speech_to_text#420]
My project is using gradle 8.0.0, but your library is in gradle 7.5, when can we expect the update?

**Comment by sowens-csd** [comment]
I usually try to keep in sync with the current version used by new Flutter projects. Looks like Flutter is currently using 7.5? Did you upgrade your Gradle version manually or did Flutter create a new project for you that used Gradle 8?

**Comment by m-derakhshi** [comment]
@sowens-csd 

```
Failed to query the value of property 'buildFlowServiceProperty'.
> Could not isolate value org.jetbrains.kotlin.gradle.plugin.statistics.BuildFlowService$Parameters_Decorated@6fcb99e7 of type BuildFlowService.Parameters
   > A problem occurred configuring project ':speech_to_text'.
      > Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
         > Namespace not specified. Specify a namespace in the module

```

i cant create pull request:

```


    namespace 'com.csdcorp.speech_to_text'
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }
    

```

**Comment by sowens-csd** [comment]
I just got back to this and I see that new Flutter projects still use Gradle 7.3.0 which is the same as the plugin. There's a guide on upgrading [here](https://docs.flutter.dev/release/breaking-changes/android-java-gradle-migration-guide) that mentions up to 7.6.1 but nothing higher. I'm going to stick with the Flutter version for the project now. 

Sorry, you'll have to fork it until Flutter catches up with your project.

**Comment by sowens-csd** [comment]
Sorry, I had misunderstood your request. I thought you were asking for Gradle 8 support but I now see your PR is just setting some compile compatibility options. Those look good. I'll review the PR.
