### ISSUE TITLE
Support automatic punctuation

### ISSUE THREAD

**Issue by marwan-at-work** [csdcorp/speech_to_text#430]
Hi there,

Thank you for this very helpful package! 

The iOS implementation has the following option which I don't see in Dart: https://developer.apple.com/documentation/speech/sfspeechrecognitionrequest/3930023-addspunctuation?changes=_9

Would it be possible to add this option to the Dart side? I'm not familiar enough with either languages but happy to help however I can. 

Thanks

**Comment by andida** [comment]
> Hi there,
> 
> Thank you for this very helpful package!
> 
> The iOS implementation has the following option which I don't see in Dart: https://developer.apple.com/documentation/speech/sfspeechrecognitionrequest/3930023-addspunctuation?changes=_9
> 
> Would it be possible to add this option to the Dart side? I'm not familiar enough with either languages but happy to help however I can.
> 
> Thanks

you can add this feature at SwiftSpeechToTextPlugin.swift.   add  the code  in listenForSpeech function:
`if #available(iOS 16, *) {
           currentRequest.addsPunctuation = true
  }`

**Comment by sowens-csd** [comment]
There is a new version in pub.dev now, 6.6.0-dev which supports an option to enable automatic punctuation on iOS during recognition. I've changed the listen method to optionally use a listenOptions parameter instead of other individual parameters for the options. It is a SpeechListenOptions type which has autoPunctuation as an available option. So it would look like this:

```dart
    final options = SpeechListenOptions(
        onDevice: _onDevice,
        listenMode: ListenMode.confirmation,
        cancelOnError: true,
        partialResults: true,
        autoPunctuation: true,
        enableHapticFeedback: true);
    speech.listen(
      onResult: resultListener,
      listenFor: Duration(seconds: listenFor ?? 30),
      pauseFor: Duration(seconds: pauseFor ?? 3),
      localeId: _currentLocaleId,
      onSoundLevelChange: soundLevelListener,
      listenOptions: options,
    );
```
Please let me know if you have a chance to try it.

**Comment by filippkowalski** [comment]
@sowens-csd thank you very much 🙏  I was about to fork the repo this/next week so I'm super stoked that you took your time to add it to your library

btw. I'd love to buy you a virtual coffee if you have it

**Comment by sowens-csd** [comment]
Interesting, it shouldn't have changed at all. I can't think of anything recent that would have affected the initialization. What kind of time difference are you seeing?

**Comment by filippkowalski** [comment]
Ok, works ok now. Sorry, false alarm.

**Comment by sowens-csd** [comment]
Thanks for verifying and for letting me know.
