### ISSUE TITLE
Issues in recognising numbers

### ISSUE THREAD

**Issue by k-pandey** [csdcorp/speech_to_text#432]
At times there is an issue when listening for numbers - it takes the string of the number instead of the numeral value.
For example, 4 becomes four. Can we have a property through which numbers are always treated as numerals in the resulting text?

**Comment by sowens-csd** [comment]
Unfortunately none of the platforms provide this option. The plugin can only expose what the platforms support.

**Comment by k-pandey** [comment]
okay, thanks for the response. I guess I will have to do some workaround then.

**Comment by sowens-csd** [comment]
Did you check the alternates to see if the number is one of the possible options returned?
