### ISSUE TITLE
Ubuntu 22.04.3 LTS Exception has occurred. MissingPluginException (MissingPluginException(No implementation found for method initialize on channel plugin.csdcorp.com/speech_to_text))

### ISSUE THREAD

**Issue by yanncarlier** [csdcorp/speech_to_text#433]
+++++++++++++++++++++++++++++++++++++++++++++++++++
running the Complete Flutter example code for linux 
Ubuntu 22.04.3 LTS and Visual Studio
+++++++++++++++++++++++++++++++++++++++++++++++++++
Exception has occurred. 
MissingPluginException (MissingPluginException(No implementation found for method initialize on channel plugin.csdcorp.com/speech_to_text))

+++++++++++++++++++++++++++++++++++++++++++++++++++
pubspec.yaml

name: namer_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  speech_to_text: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

+++++++++++++++++++++++++++++++++++++++++++++++++++

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.4, on Ubuntu 22.04.3 LTS 6.2.0-32-generic, locale en_HK.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] VS Code (version unknown)
    ✗ Unable to determine VS Code version.
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 2 categories.

**Comment by sowens-csd** [comment]
Linux is not yet supported, that's why you're seeing this message.
