### ISSUE TITLE
Last word of spoken content gets lost in Android

### ISSUE THREAD

**Issue by Jayasubin** [csdcorp/speech_to_text#434]
I am using this package to convert speech to text on Android, iOS, and the web.
On iOS and web, speech is working fine, but on Android, the last word gets lost.

For example, if the user spoke out "What is the weather", the detected words come out as "What is the", leaving out the last word.

A quick google search gave me [this android issue](https://support.google.com/translate/thread/23855711/vocie-to-text-recognition-cuts-out-end-of-sentance?hl=en) and [this post](https://github.com/termux/termux-api/issues/288) where other people faced the same problem in the past. 

Anyone has a solution for this?

**Comment by sowens-csd** [comment]
Disappointing that Google would let an apparently major issue sit unresolved for this long. Doesn't look like there's anything the plugin can do to mitigate it. Unless you have new information I'm tempted to add this to the FAQ and close this issue. Thoughts?

**Comment by sowens-csd** [comment]
I've added a note to the README for 6.4.0 and I'm going to close this as there's nothing the plugin can do.

**Comment by jayasubin-reizend** [comment]
The issue still exists in other products like G-Board that use Google's speech recognition service. I have not found a solution yet, but this issue may be closed as you said there is nothing the plugin can do to solve the problem. Let's hope that google will rollout a fix soon.

> Disappointing that Google would let an apparently major issue sit unresolved for this long. Doesn't look like there's anything the plugin can do to mitigate it. Unless you have new information I'm tempted to add this to the FAQ and close this issue. Thoughts?
