### ISSUE TITLE
How can I make the plugin recognise single letters?

### ISSUE THREAD

**Issue by ksegla** [csdcorp/speech_to_text#437]
Hi

I have an issue with single letters A, B etc. (tested in French and English). The same thing occurs with some single syllable words (such as "un", "deux" in French). I know that this may be a limitation of my device software (Samsung S22+) but I was wondering if there was a way to trick the plugin. To make it think that there was a word before, since saying "letter A", "letter B", always work. The issue seems to be really on single syllables. There is no issue with w ("double u") for instance. 

From my Google search, I found this: 
https://stackoverflow.com/questions/52419808/how-to-get-google-cloud-speech-voice-to-text-to-recognize-letters-and-sounds
It's about how a list of hints(words) can be supplied to help the speech to text return letters etc.

This issue is close to https://github.com/csdcorp/speech_to_text/issues/421 but that issue is closed and I'm opening this one to try to figure out workarounds. The problem seems common enough.

Thanks

**Comment by sowens-csd** [comment]
Unfortunately no, none of the underlying speech support provide the ability to use hint lists. Have you checked the list of alternate recognitions in the result list to see if the correct recognition is there?
