### ISSUE TITLE
android Network timeout in China

### ISSUE THREAD

**Issue by eric-5512** [csdcorp/speech_to_text#44]
android Network timeout in China

**Comment by sowens-csd** [comment]
Are you having a problem with this? Network timeout errors are always possible depending on the provider, connection, device configuration, etc. The application must be designed to handle them and provide some feedback. Do you feel like you're seeing network timeouts when you should not?

**Comment by eric-5512** [comment]
I just tried it on android again. It works. Thank you. I will close this issue
