### ISSUE TITLE
does this library support Persian(Farsi) language on ios?

### ISSUE THREAD

**Issue by vaaniiaa** [csdcorp/speech_to_text#441]
Hello
I'm using speech_to_text 5.6.1 flutter library in my application. Persian audio search works fine on android devices but on Ios devices it does not work, I added fa-IR locale programmatically but I get this error in Xcode after debugging.

Runner[993:227730] Cannot make recognizer for fa-IR. Supported locale identifiers are {(
    "nl-NL",
    "es-MX",
    "zh-TW",
    "fr-FR",
    "it-IT",
    "vi-VN",
    "fr-CH",
    "en-ZA",
    "ca-ES",
    "ko-KR",
    "es-CL",
    "ro-RO",
    "en-PH",
    "es-419",
    "en-CA",
    "en-SG",
    "en-IN",
    "en-NZ",
    "it-CH",
    "fr-CA",
    "hi-IN",
    "da-DK",
    "de-AT",
    "pt-BR",
    "yue-CN",
    "zh-CN",
    "sv-SE",
    "hi-IN-translit",
    "es-ES",
    "hu-HU",
    "ar-SA",
    "fr-BE",
    "en-GB",
    "ja-JP",
    "zh-HK",
    "fi-FI",
    "tr-TR",
    "nb-NO",
    "en-ID",
    "en-SA",
    "pl-PL",
    "id-ID",
    "ms-MY",
    "el-GR",
    "cs-CZ",
    "hr-HR",
    "en-AE",
    "he-IL",
    "ru-RU",
    "wuu-CN",
    "de-CH",
    "en-AU",
    "de-DE",
    "nl-BE",
    "th-TH",
    "pt-PT",
    "sk-SK",
    "en-US",
    "en-IE",
    "es-CO",
    "hi-Latn",
    "uk-UA",
    "es-US"
)}

would you please help me?

**Comment by sowens-csd** [comment]
The plugin will support any language that the OS supports. Do you know if iOS supports that language code? Have you tried to install a language pack for it?
