### ISSUE TITLE
I love the package. Is there a tip jar?

### ISSUE THREAD

**Issue by davidd647** [csdcorp/speech_to_text#445]
I've been using this library for about an hour a day most days for a couple years now. I'd like to put a small sum of money in a tip jar somewhere to show my appreciation.

Thank you so much.

**Comment by sowens-csd** [comment]
I'm always very happy to hear that people are using the plugin and being productive with it. I don't have a tip jar, posts like this are a great contribution, and very much appreciated. 

If you still want to contribute more I'd be very happy if you donated it to a charity of your choosing. Food banks are usually one of the priorities on my list, but feel free to choose something meaningful to you.

**Comment by davidd647** [comment]
Made a one-time donation of > $100 to **Beast Philanthropy > Beast Pantry**. Will send you a screencap privately via email.

Feels good.

**Comment by sowens-csd** [comment]
Thank you David. Means a lot to me that you took the time to do this. Hope you're having a wonderful day, you helped make mine.
