### ISSUE TITLE
Can't get the word 'Nine' to register accurately in Android

### ISSUE THREAD

**Issue by vallamost** [csdcorp/speech_to_text#446]
Using package version: 6.3.0

This package seems to work great most of the time however I noticed when trying to have it pick up just the Word 'Nine' or the number 9, it fails. I can get it to pick up: 7,8,10,19, 29, 79, 89, 99, 109, but it won't pick up just '9'. There are some oddities where 199 and 299 will sometimes register as $199 or $299, but that may be speech model dependent?

Using the Example app for the plugin, I'm able to replicate this issue
I'm testing on the Android Emulator with API 34.

Is anyone else seeing this issue?

**Comment by sowens-csd** [comment]
I think that may be either device or language / microphone / speaker dependent. I just tested on a Pixel 6a and it got it right several times used when counting and in a sentence where it should be a word. In any event there's nothing the plugin can do about the quality of the speech recognition unfortunately. I'd suggest you try again on a physical device and with a headset and see if you get better results.
