### ISSUE TITLE
Execution failed for task ':speech_to_text:compileDebugKotlin'.

### ISSUE THREAD

**Issue by malamine19** [csdcorp/speech_to_text#447]
Hello Please help how to solve this issue

Execution failed for task ':speech_to_text:compileDebugKotlin'.
> 'compileDebugJavaWithJavac' task (current target is 1.8) and 'compileDebugKotlin' task (current target is 17) jvm target compatibility should be set to the same Java version.
  Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain

**Comment by sowens-csd** [comment]
Is this with your code or with the example app? It looks more like a Flutter usage question than a plugin question. Have you tried generating a new project and testing the plugin with that? If that's working then you could move the new project settings into your project. If there's still an issue let me know.

**Comment by sowens-csd** [comment]
You may want to test this again with 6.4.0 which is in the repo now and will be releasing soon. There was a PR about Java 1.8 compatibility that may resolve the issue.
