### ISSUE TITLE
Library doesn’t work on iOS 16.x.x both simulator and real device

### ISSUE THREAD

**Issue by siiimaay** [csdcorp/speech_to_text#448]
Hi,

Speech to text is not functioning in specific versions
It’s giving below messages when iOS version 16.x.x both real device and simulators.

Below what I get as error messages
```
flutter: Error initializing speech recognition: SpeechRecognitionError msg: error_listen_failed, permanent: true
flutter: status: done => from the onStatus() function
flutter: status: done => from the onStatus() function
flutter: Error initializing speech recognition: SpeechRecognitionError msg: error_no_match, permanent: true

```
I tried already readme suggestion which is enabling the spoken contents and voices.

Appreciate your help here.
Thank you

**Comment by sowens-csd** [comment]
Is this with the example app or your own code?

**Comment by siiimaay** [comment]
Hey Stephan, 

I initially got the error from my code but now tried with an example code and results same
Here are the logs:

`flutter: 2023-10-23T14:58:41.341809 Received listener status: notListening, listening: false
flutter: 2023-10-23T14:58:41.342610 Received error status: SpeechRecognitionError msg: error_listen_failed, permanent: true, listening: false
flutter: 2023-10-23T14:58:41.342853 Received listener status: done, listening: false
flutter: 2023-10-23T14:58:41.368835 Received listener status: done, listening: false
flutter: 2023-10-23T14:58:41.369227 Received error status: SpeechRecognitionError msg: error_no_match, permanent: true, listening: false`

If it helps, leaving couple of details
-- Language is English(United States)
-- Exact version I tried now iOS 16.4
Also, it works  v17.0.3 and v15 variations without any issue

**Comment by sowens-csd** [comment]
So error_no_match means that it thinks it didn't hear any words. That's odd because lots of other things have to be working properly for it to get to error_no_match. Have you tried it with a headset?

**Comment by sowens-csd** [comment]
I just tried the sample app on iOS 16.7.1 and it worked correctly. Not sure what's happening in your copy but it doesn't appear to be a generic iOS 16 issue. I suppose it could be a 16.6.x issue?

**Comment by sowens-csd** [comment]
Any updates on this?

**Comment by siiimaay** [comment]
Hey, sorry for late response
Since this happens in 16.4 and 16.6 as well, maybe lower version from 16.7.x might be the problematic ones, when I tried sample app in simulator still not works for v16.4. Do you have any suggested workaround for these versions? if not, will close the ticket and assume these versions have unknown problem.

**Comment by sowens-csd** [comment]
Sorry, I missed this response. No, that's really bizarre, sorry, I don't have any suggested work arounds.
