### ISSUE TITLE
onResult not working

### ISSUE THREAD

**Issue by ayeshakamran543** [csdcorp/speech_to_text#449]
D/SpeechToTextPlugin(14871): Start listening
D/SpeechToTextPlugin(14871): setupRecognizerIntent
D/SpeechToTextPlugin(14871): Notify status:listening
D/SpeechToTextPlugin(14871): Start listening done
D/SpeechToTextPlugin(14871): Error 8 after start at 11 1000.0 / -100.0
D/SpeechToTextPlugin(14871): Notify status:notListening
D/SpeechToTextPlugin(14871): Notify status:doneNoResult
D/BufferPoolAccessor2.0(14871): bufferpool2 0x7de4e65033d8 : 5(10485760 size) total buffers - 1(2097152 size) used buffers - 209/215 (recycle/alloc) - 7/214 (fetch/transfer)
D/BufferPoolAccessor2.0(14871): bufferpool2 0x7de4e6594348 : 5(40960 size) total buffers - 1(8192 size) used buffers - 306/311 (recycle/alloc) - 5/310 (fetch/transfer)
D/SpeechToTextPlugin(14871): rmsDB 0.4000001 / 0.4000001
D/SpeechToTextPlugin(14871): rmsDB -2.0 / 0.4000001

**Comment by sowens-csd** [comment]
Looks like this is one Android? On a physical device or a simulator? Have you read through the troubleshooting guide for tips on getting speech working?

**Comment by dhruv1710** [comment]
I'm getting this error on iOS simulator. The speechToText.listen isn't working.

**Comment by sowens-csd** [comment]
Simulators can be hard to get working properly. Everything I know about getting speech working on a simulator is in the troubleshooting guide or the issues I linked to from there. I've stopped trying to use simulators myself because I don't trust the results they provide.
