### ISSUE TITLE
error_language_not_supported error caused on example app

### ISSUE THREAD

**Issue by kotran88** [csdcorp/speech_to_text#452]
even though I run just run example app on my android phone, 
it caused error as picture attached

![KakaoTalk_Photo_2023-11-02-14-10-54](https://github.com/csdcorp/speech_to_text/assets/20656932/7361151a-b66e-4c93-9f6c-469cd745145b)

**Comment by sowens-csd** [comment]
Have you tried downloading the language pack for the selected language?
