### ISSUE TITLE
speechToText.cancel and speechToText.stop break flutterTts.speak

### ISSUE THREAD

**Issue by AaEll** [csdcorp/speech_to_text#454]
Expected behavior:
   flutterTts.speak('this sentence');    
   will result in hearing the spoken sentence

Observed behavior
   flutterTts.speak('this sentence');    
   no sound is output

Flutter Doctor
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.5.1 22G90 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[✓] Network resources

Device IPhone 14 Simulator on Mac

```
  final speechToText = SpeechToText();
  final flutterTts = FlutterTts();

Future<void> setupDeps() async {
    await speechToText.initialize();
    await speechToText.hasPermission;
    await flutterTts.setSharedInstance(true);
    await flutterTts.awaitSpeakCompletion(true);
}

void initState(){
    super.initState();
    setupDeps();
}

Future<void> speakTextNoListen() async {
    await speechToText.listen();
    await speechToText.cancel(); // OR speechToText.stop();

    flutterTts.speak('this sentence');    
}

```

**Comment by sowens-csd** [comment]
I think you're on the wrong forum. You're looking for the closely related project text to speech, this is the speech to text project. Pretty confusing naming, sorry about that. Basically we listen when you talk, they talk when you tell them what to say. Good luck getting an answer!

**Comment by AaEll** [comment]
I understand, the issue comes when using both libraries together

**Comment by sowens-csd** [comment]
I think you need to wait for the status callback from STT to report that it has stopped listening before trying to use the sound system again. Let me know if that helps.
