### ISSUE TITLE
MODIFY_PHONE_STATE permission

### ISSUE THREAD

**Issue by giovanni256** [csdcorp/speech_to_text#457]
Hi there,

due to [this change](https://github.com/csdcorp/speech_to_text/commit/3a808cb8d31859d2758dc99ec056ea6a9db23c02) you asked the MODIFY_PHONE_STATE permission which is asking for android.hardware.telephony.

This makes Android tablets without LTE module not available anymore for the app download.

Can you remove it?

**Comment by sowens-csd** [comment]
Yeah, that looks like an error to me. I can't find any support for needing that permission for speech recognition. I'll put out a .1 release. Thanks for the help.

**Comment by giovanni256** [comment]
> 6.4.1 is released now with this change. Let me know if you have a chance to try it.

Thanks, it works!

**Comment by PHPJourney** [comment]
```
speech_to_text-7.1.0-beta.3/android/src/main/kotlin/com/csdcorp/speech_to_text/SpeechToTextPlugin.kt:300: Error: Missing permissions required by BluetoothHeadset.startVoiceRecognition: android.permission.BLUETOOTH_CONNECT and android.permission.MODIFY_PHONE_STATE [MissingPermission]
                  if (lhead.startVoiceRecognition(tryDevice)) { 
```
The last version found some error.
