### ISSUE TITLE
Support Persian?!

### ISSUE THREAD

**Issue by AliEasy** [csdcorp/speech_to_text#458]

**Comment by sowens-csd** [comment]
The plugin should already support any language that is supported and installed on the platform you are using it on. Check the README for some tips on installing language packages and choosing the language to use. 

If the language is not natively supported by the device, iOS, Android, web, then the plugin cannot support it.

**Comment by AliEasy** [comment]
On my Samsung device at Settings > General management > Language, I have 2 active languages: English and Persian, if this is what you mean

**Comment by sowens-csd** [comment]
That's a good start. Does Google Assistant understand you when you speak Persian? 

When you try the language code for Persian in the sample app what happens?

**Comment by erfanh3h** [comment]
persian localid is : "fa_IR"
