### ISSUE TITLE
Can't be changed to another error & status handler

### ISSUE THREAD

**Issue by yoshoten-i-sol** [csdcorp/speech_to_text#46]
Can't change the error & status handler try to a new speech instance when I had another speech instance.
Try to fix it by the bottom code, and it's working but not sure it's right way.
`
  Future<bool> initialize(
      {SpeechErrorListener onError, SpeechStatusListener onStatus}) async {
    if (_initWorked) {
      errorListener = onError;
      statusListener = onStatus;
      channel.setMethodCallHandler(_handleCallbacks);
      return Future.value(_initWorked);
    }
    errorListener = onError;
    statusListener = onStatus;
    channel.setMethodCallHandler(_handleCallbacks);
    _initWorked = await channel.invokeMethod('initialize');
    return _initWorked;
  }
`

**Comment by sowens-csd** [comment]
Sorry, I'm not clear what you're trying to accomplish? You can't have two instances of the speech_to_text class, they would both use the same underlying plugin and one of them would fail to initialize. You should define one speech_to_text instance, initialize it, and use it throughout your application.

**Comment by yoshoten-i-sol** [comment]
Sorry for not clearly, I mean I can change the SpeechResultListener and SpeechSoundLevelChange handler to other function when I call the listen method but I can't change the SpeechStatusListener and SpeechErrorListener to other function.
I'm trying to accomplish checking the listening status on difference view.

**Comment by sowens-csd** [comment]
Ah, I see. For that I'd currently use a `Provider` with a `ChangeNotifier` that wraps the plugin and exposes information to views through change notifications. It's an interesting idea for a new feature for the plugin actually, I could embed a provider implementation as a higher level abstraction for the plugin behaviour. I'll look at that for a future release. Let me know if you still have questions.

**Comment by yoshoten-i-sol** [comment]
Thank you for your help, no more question.
