### ISSUE TITLE
Times and numbers

### ISSUE THREAD

**Issue by kagemusha** [csdcorp/speech_to_text#462]
Speech recognition automatically converts numbers and times to number and string representations

e.g. 
if I say "one thirty" is will return "1:30"
if I say on thirty nine" it will return "139"
"one oh nine" => 109
etc

is there a way to tell it to get the actual spoken text not the number/time translation?

**Comment by sowens-csd** [comment]
Unfortunately no. The speech frameworks don't provide that level of control. Have you checked the alternates list to see if the words are also reported?

**Comment by kagemusha** [comment]
checked this and reports just as numbers unfortunately.
