### ISSUE TITLE
please solve recording issue with speech to text

### ISSUE THREAD

**Issue by niv123eosys** [csdcorp/speech_to_text#463]
with speech to text flutter package i want use voice recording but i cant record voice ,if am using speech to text and voice recording function simultaneously ,only recording function's works please find a solution for this

**Comment by sowens-csd** [comment]
As far as I know this isn't possible because they both want access to the microphone and can't share it.

**Comment by agladyshev** [comment]
@niv123eosys I've had a similar issue. On iOS you can both record and use voice recognition. On Android it is impossible if you use default Android recognition.
I was able to successfully use vosk_flutter package for Android. But you have to store model data for each language you want to support. Medium-quality model for english is around 40mb and provides similar results to the default STT.
As far as I know, there is no way to have different assets for iOS and Android, so users on both platforms would have to download a larger app size.
I also had to write a wrapper to create a similar interface for both vosk_flutter and speech_to_text to use in my app.
