### ISSUE TITLE
issue with pauseFor

### ISSUE THREAD

**Issue by talhaizzettin** [csdcorp/speech_to_text#464]
i have but pauseFor for 30 m but it is stop when i stop to talk too quickly 

    await _speechToText.listen(
      listenMode: ListenMode.dictation,
      onResult: _onSpeechResult,
      localeId: selectedLocale,
      listenFor: const Duration(minutes: 30),
      pauseFor: const Duration(minutes: 30),
    );

**Comment by sowens-csd** [comment]
If it is on Android that's expected behaviour, see the README for details.
