### ISSUE TITLE
 Issue with Flutter Speech to Text on Android 11 and Earlier

### ISSUE THREAD

**Issue by ArkadaMalo** [csdcorp/speech_to_text#466]
### Description

I am currently using Flutter Speech to Text version 6.4.1 in my application, and it works perfectly on Android versions after 11. However, I've encountered a problem with Android 11 and versions prior to it. It seems like I don't have the necessary permissions, even though they are requested at the start of the app and are properly granted.

One important note is that it works on the Android emulator, but not on physical phones running Android 11 and earlier.

Has anyone else experienced a similar issue? Do you have any insights or solutions to resolve this problem? Any help would be greatly appreciated!

**Comment by sowens-csd** [comment]
Have you tried the sample app? Does it show the same behaviour? What happens when it fails and are there any logs that show an error? Does it fail during initialization or only when you try to `listen`?

**Comment by sowens-csd** [comment]
Any updates on this?

**Comment by ArkadaMalo** [comment]
Sorry it fixed SDK problem ty for your help
