### ISSUE TITLE
Android Permission android.permission.BLUETOOTH_CONNECT should be optional

### ISSUE THREAD

**Issue by adscooli** [csdcorp/speech_to_text#469]
Consider removing the BLUETOOTH_CONNECT permission from the libs Manifest file, as it's flagged as critical or dangerous by various app checkers.

The permission should be optinal and added manually as mentioned in the Docs.

 The permission was introduced in this [commit]( https://github.com/csdcorp/speech_to_text/commit/bc36fcb374c6a1dedd8e785ffbbf912486545d47)

**Comment by sowens-csd** [comment]
So you're suggesting making Bluetooth support optional and only enable it if requested by the developer?

**Comment by adscooli** [comment]
Yes in a sense. 
While Bluetooth is currently optional since it can be disabled using the provided flags,
the BLUETOOTH_CONNECT permission will be added automatically through manifest merge, even if it is not explicitly required.


The permissions mentioned in the doc are:
```
// these permission must be added by the developer:
android.permission.RECORD_AUDIO
android.permission.INTERNET 
android.permission.BLUETOOTH 
android.permission.BLUETOOTH_ADMIN 

// only this is automatically added by manifest merge (which seems unintentional)
android.permission.BLUETOOTH_CONNECT
```

Here is the part of the doc:
![grafik](https://github.com/csdcorp/speech_to_text/assets/123360004/15c526e8-2372-400d-852b-dd568ed0d8bd)

The flags to disable bluetooth are (if anyone else is interested)
```
SpeechToText.androidNoBluetooth
SpeechToText.iosNoBluetooth.
```

**Comment by sowens-csd** [comment]
Makes sense, thanks. I think what happened is that Android Studio tends to complain about those flags and I sometimes get the example and plugin manifests confused when I'm not paying sufficient attention. I'll make the change.

**Comment by sowens-csd** [comment]
6.5.1 is out now with this change. If you have a chance to try it let me know.

**Comment by adscooli** [comment]
Great. Thanks. I tested it with the bluetooth NoBluetooth flags and without the bluetooth permissions. Works as expected an no permission is added to the app anymore.
