### ISSUE TITLE
bind to recognition service failed.    Android

### ISSUE THREAD

**Issue by DuQuanzhong** [csdcorp/speech_to_text#471]
<img width="653" alt="截屏2024-01-04 15 27 27" src="https://github.com/csdcorp/speech_to_text/assets/5549754/a9dfa67f-9f77-4896-a776-c3886cd32a52">

Device Information： HUAWEI honor,    system V:  HarmonnyOS2.0.0

**Comment by timmolter** [comment]
Did you add the correct app permissions in the manifest?

**Comment by DuQuanzhong** [comment]
<img width="777" alt="截屏2024-01-05 09 38 39" src="https://github.com/csdcorp/speech_to_text/assets/5549754/7df5fc14-b3a6-4745-92aa-efe4f3d4c85a">
<img width="641" alt="截屏2024-01-05 09 39 02" src="https://github.com/csdcorp/speech_to_text/assets/5549754/5cc43d69-338c-41ee-9462-45ab505a589a">
Hello, I have added these permissions.  The recognition of speech can be completed on other Android phones, but not on this one.

**Comment by DuQuanzhong** [comment]
The iPhone can perform voice recognition for recording. #470

**Comment by DuQuanzhong** [comment]
I saw someone else encountering the same issue.  #431

**Comment by timmolter** [comment]
What Android version is running on that phone?

**Comment by sowens-csd** [comment]
Unfortunately not all Android devices follow the Android standard for the speech intent.  There is one workaround in the package that works on some devices. Did you try the `SpeechToText.androidIntentLookup` option in the `initialize` call. Usage is like this:
```dart
await speech.initialize(
        onError: errorListener,
        onStatus: statusListener,
        options: [SpeechToText.androidIntentLookup],
      );
```

I have seen reports that this can crash on some devices because they have a secure intent that should not be bound. Let me know if you have a chance to try it.

**Comment by DuQuanzhong** [comment]
<img width="746" alt="截屏2024-01-08 14 33 36" src="https://github.com/csdcorp/speech_to_text/assets/5549754/f00a5a9b-7597-48c7-8b11-8d7f684c9019">
<img width="634" alt="截屏2024-01-08 14 32 41" src="https://github.com/csdcorp/speech_to_text/assets/5549754/2dff17b6-3265-47d1-82f6-90ccda659298">
![WechatIMG1](https://github.com/csdcorp/speech_to_text/assets/5549754/d2f7594b-2ffc-4a0a-9f92-c635d37eb422)


I followed your instructions and wrote the code, but I am still encountering the same error.

**Comment by DuQuanzhong** [comment]
System info:
![WechatIMG1](https://github.com/csdcorp/speech_to_text/assets/5549754/47de7c4e-f8c8-4330-b8de-99293dd1e34d)
my Code:
<img width="746" alt="截屏2024-01-08 14 33 36" src="https://github.com/csdcorp/speech_to_text/assets/5549754/ffb99bb7-9dcb-4d32-a450-4cfb7a57d4da">
print: 
<img width="634" alt="截屏2024-01-08 14 32 41" src="https://github.com/csdcorp/speech_to_text/assets/5549754/2ad5447b-00d0-4d79-ab7e-b5efed65b25c">

I followed your instructions and wrote the code, but I am still encountering the same error.

**Comment by DuQuanzhong** [comment]
> Android

This phone is running HarmonyOS  V: 2.0.0.

**Comment by timmolter** [comment]
From what I can tell Harmony is different enough from Android to consider it a different operating system IMO.

https://www.gizchina.com/2023/01/28/harmonyos-vs-android-vs-ios-huawei-explains-the-main-difference/

**Comment by DuQuanzhong** [comment]
> 大不同，在我看来，Harmony 是一个不同的操作系统。

Thank you for your reply.

**Comment by DuQuanzhong** [comment]
D/SpeechToTextPlugin(27203): Start initialize
D/SpeechToTextPlugin(27203): Checked permission
D/SpeechToTextPlugin(27203): has permission, completing
D/SpeechToTextPlugin(27203): completeInitialize
D/SpeechToTextPlugin(27203): Testing recognition availability
D/SpeechToTextPlugin(27203): sending result
D/SpeechToTextPlugin(27203): leaving complete
D/SpeechToTextPlugin(27203): leaving initializeIfPermitted
D/SpeechToTextPlugin(27203): before setup intent
D/SpeechToTextPlugin(27203): setupRecognizerIntent
D/SpeechToTextPlugin(27203): after setup intent
D/SpeechToTextPlugin(27203): Start listening
D/SpeechToTextPlugin(27203): setupRecognizerIntent
D/SpeechToTextPlugin(27203): Notify status:listening
D/SpeechToTextPlugin(27203): Start listening done
D/SpeechToTextPlugin(27203): Creating recognizer
D/SpeechToTextPlugin(27203): RecognitionService, found: 1
D/SpeechToTextPlugin(27203): RecognitionService: packageName: com.google.android.googlequicksearchbox, name: com.google.android.voicesearch.serviceapi.GoogleRecognitionService
D/SpeechToTextPlugin(27203): Setting listener after intent lookup
D/SpeechToTextPlugin(27203): In RecognizerIntent apply
D/SpeechToTextPlugin(27203): put model
D/SpeechToTextPlugin(27203): put package
D/SpeechToTextPlugin(27203): put partial
E/SpeechRecognizer(27203): bind to recognition service failed
[log] 状态：listening
D/SpeechToTextPlugin(27203): Stop listening
D/SpeechToTextPlugin(27203): Notify status:notListening
D/SpeechToTextPlugin(27203): Notify status:doneNoResult
D/SpeechToTextPlugin(27203): Stop listening done

**Comment by DuQuanzhong** [comment]
![WechatIMG1](https://github.com/csdcorp/speech_to_text/assets/5549754/f9719872-5728-40c6-845d-8574f513ec29)

For HarmonyOS, you need to download "Google Assistant." When you open Google Assistant, it will redirect to voice settings. Choose Google, and you're all set.

**Comment by DuQuanzhong** [comment]
Thank you   @sowens-csd   @timmolter
