### ISSUE TITLE
flutter: Errorrrrr SpeechRecognitionError msg: error_retry, permanent: true

### ISSUE THREAD

**Issue by ZahoorUllah13** [csdcorp/speech_to_text#474]
i am using speech_to_text package in my app ...they work correct on ios 15 simulator but on ios 16 and above show the flutter: Errorrrrr SpeechRecognitionError msg: error_retry, permanent: true issue in console

**Comment by sowens-csd** [comment]
Yes, iOS simulators have some issues. There's a section in the readme that may help. If not I'd suggest trying it on a real device.

**Comment by WhiteSnowGirl** [comment]
fine
