### ISSUE TITLE
Methods for Adding Amplitude Monitoring for Audio

### ISSUE THREAD

**Issue by DuQuanzhong** [csdcorp/speech_to_text#476]
Hello, can you please add a method for monitoring audio amplitude? Thank you.

**Comment by sowens-csd** [comment]
There is a callback available on the `listen` method `onSoundLevelChange` that can be used. Is that what you're looking for?

**Comment by DuQuanzhong** [comment]
Thank you very much,  also the range for this value?

**Comment by sowens-csd** [comment]
The value is in decibels, I don't know how accurate the platform specific decibel calculation done by the OS is but the range should be around what you'd expect for voice.
