### ISSUE TITLE
Remove plugin logs or let them be activated with a flag

### ISSUE THREAD

**Issue by ElZombieIsra** [csdcorp/speech_to_text#48]
I'm currently working with this plugin but it is annoying that every time I make a plugin call, everything that is happening behind the scenes is logged to my console. This can be conflictive with the logs that I'm using to debug my app and it is really tedious to browse through all the logs from the plugin to find 1 log from my app.

This should be eliminated from the plugin or at least add a flag that can be set to debug this calls like ```SpeechToText(debug: true)```

I'm willing to help to do this if you need me to.

Thanks in advance

![Image of my logged code](https://i.imgur.com/disqrIH.png)

**Comment by sowens-csd** [comment]
My bad. That slipped in, should never have been in a release. I'll remove it and put up a new release.

**Comment by sowens-csd** [comment]
The latest version on git has this change now. It will be in the next release.

**Comment by ElZombieIsra** [comment]
Thanks. I see that you removed the logs from the dart file itself. But I think there's also logs being printed from the iOS and Android plugins.

**Comment by sowens-csd** [comment]
New version in the repo now has a debugLogging flag on the initialize method that can be used to turn on detailed logging on Android. It defaults to false so no logs should be shown.
