### ISSUE TITLE
depends on js ^0.7.0 and speech_to_text >=4.0.0-nullsafety depends on js ^0.6.3,

### ISSUE THREAD

**Issue by Yoda-Man** [csdcorp/speech_to_text#482]
Is it possible to upgrade the package to use js 0.7.0

**Comment by saropa** [comment]
This would be great - we're starting to get dependancy errors here.

**Comment by sowens-csd** [comment]
Looks like it should be compatible. I'll do the update in the next minor version.

**Comment by sowens-csd** [comment]
I do find it amusing that a widely used dependency is still 0.x instead of moving to 1.x. Come on folks, signal production quality please.

**Comment by saropa** [comment]
Ideally, js: ^0.7.1

Would a PR help?

**Comment by Yoda-Man** [comment]
js: ^0.7.1 would be best

**Comment by sowens-csd** [comment]
@saropa thanks for the PR offer but no, the work is done, just need to check some other commits and deploy. I have done 0.7.0, I'll have a look 0.7.1.

**Comment by sowens-csd** [comment]
Looks like 0.7.1 is just a README update, should be safe.

**Comment by sowens-csd** [comment]
6.6.1 is now published with this update.
