### ISSUE TITLE
No permissions anymore on IOS

### ISSUE THREAD

**Issue by carpentierchloe** [csdcorp/speech_to_text#490]
I have the version 6.0.0 and it does not work anymore on IOS (it is well working on Android).

I well have permission NSSpeechRecognitionUsageDescription and NSMicrophoneUsageDescription in ios/Runner/Info.plist

```
var hasSpeech = await speech.initialize(
        onError: errorListener,
        onStatus: statusListener,
        debugLogging: true,
      );
```

hasSpeech is returning "false"

I have the last version of flutter, brew and pod are updated.
Impossible to get the version 6.0.1 : speech_to_text >=6.6.1 depends on js ^0.7.1 and connectivity_plus >=4.0.2 depends on js ^0.6.4, speech_to_text >=6.6.1 is incompatible with connectivity_plus >=4.0.2.

Thanks a lot for your help

**Comment by sowens-csd** [comment]
Do you get the same issue with the example app? 
Can you upgrade the connectivity_plus plugin?

**Comment by sowens-csd** [comment]
Try adding this until connectivity_plus upgrades, or just as a test to see if iOS is working for you.
```yaml
dependency_overrides:
  js: ">=0.7.1"
```

**Comment by carpentierchloe** [comment]
Thx, I succeeded to get the version 6.0.1 of the package now. However, hasSpeech is still returning "false" :'(

**Comment by sowens-csd** [comment]
Is this on a real device or an emulator? Have you tried the sample app?

**Comment by carpentierchloe** [comment]
It is on a real device and it was working before.

**Comment by carpentierchloe** [comment]
With the package permission handler Permission.microphone.status is true but await speech.initialize( ) is still returning false.

**Comment by carpentierchloe** [comment]
The issue was with the permission of my device, all apologies.

**Comment by Abhijit-Revamp** [comment]
@carpentierchloe what was the permission issue? May be helpful for others too
