### ISSUE TITLE
Can we add tk-TM locale to the package?

### ISSUE THREAD

**Issue by ataballyyev** [csdcorp/speech_to_text#493]
There is not tk-TM locale and it would be better after adding that locale

**Comment by sowens-csd** [comment]
Unfortunately the plugin does not control the available set of locales. That is controlled by the OS of the device you are trying to use it on. The plugin only exposes the capabilities of the underlying OS. 

If that locale is supported for speech recognition on the device and the plugin does not recognize it then that would be an issue with the plugin. Please let me know.
