### ISSUE TITLE
SpeechRecognitionError msg: error_language_unavailable, permanent: true (Honor Mobiles)

### ISSUE THREAD

**Issue by binSaed** [csdcorp/speech_to_text#494]
`  speech_to_text: ^6.5.1`
DEVICE MODEL: Honor REA-NX9

```dart
 _speechToText.initialize(
      finalTimeout: const Duration(milliseconds: 600),
      options: [
        SpeechToText.androidIntentLookup,
      ],
  );
```

**Comment by binSaed** [comment]
user followed these steps and the issue was not resolved
<img width="649" alt="image" src="https://github.com/csdcorp/speech_to_text/assets/33700292/4feae099-8239-4878-b35b-b6420add7869">
![PHOTO-2024-03-10-17-24-54](https://github.com/csdcorp/speech_to_text/assets/33700292/f0881dcb-2b3d-4974-b176-df06fdd7eada)
![PHOTO-2024-03-10-17-24-55](https://github.com/csdcorp/speech_to_text/assets/33700292/c185427a-f398-4d17-8f58-fbe5c86d1fa5)

**Comment by binSaed** [comment]
@sowens-csd

**Comment by sowens-csd** [comment]
You didn't say what language you were trying to use? It sounds like either the language is not available for the device or that the device doesn't support the default Android speech initialization and the intentLookup option isn't working.

**Comment by alihuseyin** [comment]
Same here, I tried it on emulator (android 14) and real device (android 13)  and it gives me `SpeechRecognitionError msg: error_language_unavailable, permanent: true` error.

**Comment by alihuseyin** [comment]
I figured out that on my Samsung m22 (Android 13) SpeechToText.androidIntentLookup parameter in options is causing the problem
