### ISSUE TITLE
iOS Sounds not always playing

### ISSUE THREAD

**Issue by sowens-csd** [csdcorp/speech_to_text#5]

**Comment by DevonTomatoSandwich** [comment]
How did you solve this? I have this problem now in iOS (works fine in android). Pressing start does not make the start sound. Im using the example project provided. It recognises speech fine but no sounds. 

I checked i have the right assests in the pubspec.yaml and my device volume is up. I'm running on an iphone 5c. 

Also my `soundLevelListener` (the function that tracks changes to sound level) isn't being called at all.

I'm also getting a bottom overflowed by 1.8 pixels but i'm sure that isn't the cause. I think the overflow happens as the text that shows 'Error Status' has a large font size but the flex=1 is too small. The other expanded has a flex of 4 meaning it has to be 4 times bigger that the text with large font (i think) so this causes the overflow on small devices. I know not a major concern but just something i noticed.

Thanks!

**Comment by DevonTomatoSandwich** [comment]
**Update**
I thought this could be device related. I tested on the simulator and it seems to be working fine. For some reason the device is not working. Will test on roommates phone when he wakes up :)

**Comment by sowens-csd** [comment]
I think there might be a regression with the sound playback on iOS. I'll have a look. If it's a problem I'll open a new issue, or feel free to open a new issue if you can reproduce the problem. Thanks for the feedback!

**Comment by sowens-csd** [comment]
I tried the sound playback and it's working for me on both iOS 13 and iOS 10. Can you let me know if you're still having a problem?

**Comment by DevonTomatoSandwich** [comment]
Hey thanks for getting back and doing some tests. 

I couldn't con my roommate into letting me use his device. I might get a device next week though. So hopefully I'll figure it out then. If not I'll open an issue

**Comment by sowens-csd** [comment]
What good is a roommate that won't let you gain trusted access then manually install development level software on their personal device? You need a new roommate.
