### ISSUE TITLE
Error when build with real device

### ISSUE THREAD

**Issue by hoanganhnth** [csdcorp/speech_to_text#502]
I got error when use stt with real device :
E/SpeechRecognizer(19785): bind to recognition service failed
![image](https://github.com/csdcorp/speech_to_text/assets/94519158/f6c8d93a-d402-4de3-9f8d-c962058f9f2b)
![image](https://github.com/csdcorp/speech_to_text/assets/94519158/13cdc5b4-6379-4712-bb0b-70662fabcd38)
![image](https://github.com/csdcorp/speech_to_text/assets/94519158/803c6495-4543-440a-a6b1-41816ea8446c)

**Comment by wamynobe** [comment]
Can you provide your `flutter doctor -v` and your speech_to_text version?

**Comment by sowens-csd** [comment]
This has been open for a while with no responses, closing.
