### ISSUE TITLE
[Question:About hiragana in Japanese]

### ISSUE THREAD

**Issue by coppwii** [csdcorp/speech_to_text#507]
When I say 'I am Mario' in Japanese
‘私はマリオです’ is output. (Of course, this is the most correct way to write Japanese.)
However, Japanese can also be written using only 'hiragana' without using kanji.
'私はマリオです' in hiragana only changes to '私' -> ‘わたし’, ‘マリオ’ -> ‘まりお’, becomes 'わたしはまりおです'.
 (This hiragana-only is common in the beginning of studying Japanese).

Is there a way to output only hiragana in speech_to_text?

**Comment by sowens-csd** [comment]
Thanks for your very interesting question. I actually didn't know how STT would work in Japanese, so good to know it has at least some utility. I did a quick search and I don't see options in either iOS or Android to control the text conversion for the output. That definitely doesn't completely rule it out but I don't see any obvious solution. 

I don't know anything about the differences or how feasible it would be but could you convert the output text from Kanji to Hiragana? I did find this in case it is of any use:

https://pub.dev/packages/kana_kit

**Comment by coppwii** [comment]
I appreciate your help in researching options for both iOS and Android, and thank you for looking into the relevant packages as well. 
I'll go ahead with implementing the solution using the packages you've suggested. 

Thank you very much!
