### ISSUE TITLE
'error_no_match' does not get fired after the update from 0.7.1 to 1.1.0

### ISSUE THREAD

**Issue by BogdanSinitsa** [csdcorp/speech_to_text#51]
The callback onError does not get triggered when the error type is ''error_no_match"

But there are logs from the library witch says that the error has been notified. 

```
I/flutter (23187): SpeechToText call: textRecognition {"finalResult":false,"alternates":[{"recognizedWords":"","confidence":-1}]}
I/flutter (23187): SpeechToText call: notifyError {"errorMsg":"error_no_match","permanent":true}
```

**Comment by BogdanSinitsa** [comment]
I have reverted to version 0.8.0. Now it works.

**Comment by sowens-csd** [comment]
Can you give me the steps to reproduce this? The key difference in error handling in recent versions is that it now only notifies of an error while in listening mode `isListening` is true. From the log excerpt you included it looks like it should have been in listening mode but having the steps to reproduce would help.

**Comment by dcosta-desenbahia** [comment]
The problem is that the listening mode (isListening) is false because the _onNotifyStatus method is called before _onNotifyError method:

I/flutter (24989): SpeechToText call: notifyStatus notListening
I/flutter (24989): notListening
I/flutter (24989): SpeechToText call: notifyError {"errorMsg":"error_no_match","permanent":true}

_onNotifyError:
```
if ( isNotListening ) {
      return;
    }
```

**Comment by BogdanSinitsa** [comment]
> Can you give me the steps to reproduce this? The key difference in error handling in recent versions is that it now only notifies of an error while in listening mode `isListening` is true. From the log excerpt you included it looks like it should have been in listening mode but having the steps to reproduce would help.

Sorry for the long response.
The code is the same as from example.

Steps to reproduce.
1. invoke 'listener' function
2. say something indistinguishable. A sound or a word in another language.
3. v0.7.1 - onError callback got called. v1.1.0 - nothing happens.
