### ISSUE TITLE
Not work with airpods in iOS

### ISSUE THREAD

**Issue by ChungangL** [csdcorp/speech_to_text#510]
I annotated the code for starting the sound file in the example
`#  assets:
#    - assets/sounds/speech_to_text_listening.m4r
#    - assets/sounds/speech_to_text_cancel.m4r
#    - assets/sounds/speech_to_text_stop.m4r`

Wearing AirPods while running Example on iOS may result in unusable situations：

https://github.com/csdcorp/speech_to_text/assets/97420698/fe01a54f-897a-4398-b59c-7967d17b4982

Pay attention to the small yellow dot in the upper right corner, which stops recording shortly after startup, and the plugin does not report stopping recording or reporting errors

**Comment by sowens-csd** [comment]
I haven't actually tried it with AirPods, I would have expected them to work like any other bluetooth source. From your description and the video it sounds like you are not able to get any recognized words using AirPods, is that correct?
