### ISSUE TITLE
Request to Add Option to Disable Notification Sound on Android

### ISSUE THREAD

**Issue by islamzohairy** [csdcorp/speech_to_text#512]
Hello,

I'm using the `speech_to_text` package in my Flutter application and I've noticed that a notification sound is played when the speech recognition starts and stops listening on Android. This sound can be disruptive to the user experience in my application.

I've looked through the documentation and the package's API, but I couldn't find a way to disable this sound. I was wondering if it would be possible to add an option to disable the notification sound when the speech recognition starts and stops listening.

Thank you for your time and consideration.

**Comment by sowens-csd** [comment]
That sound is played by Android and the Android speech API doesn’t allow it to be disabled unfortunately.

**Comment by islamzohairy** [comment]
Thanks, Stephen! That clarifies things a lot. Appreciate you looking into this.

As an additional thought, for users who want more control over interruptions, the flutter_dnd package might be a useful tool to explore. It allows managing Do Not Disturb settings on Android, which could indirectly help silence the sound.
