### ISSUE TITLE
iOS, onResult is not called

### ISSUE THREAD

**Issue by ugochirico** [csdcorp/speech_to_text#516]
On iOS 12 Pro, with iOS 16.5, onResult is never called.
This is my code:

```
await _speech.listen(
        listenOptions: SpeechListenOptions(
          partialResults: false,
          listenMode: ListenMode.deviceDefault,
            autoPunctuation: true,
            enableHapticFeedback: true,
            cancelOnError: true,
        ),
        onResult: (value) => onResult(value.recognizedWords),
        localeId: language,
      );
```
this is the log:
```
flutter: listening
[plugin] HypothesizeTranscription
[plugin] HypothesizeTranscription
[plugin] HypothesizeTranscription
[plugin] HypothesizeTranscription
[plugin] HypothesizeTranscription
[plugin] HypothesizeTranscription
```
it continues until I call _speech.stop();

**Comment by Omu0503** [comment]
Yea same, I'm unable to detect anything. Found any solutions to this?

**Comment by ugochirico** [comment]
Not yet. I'm blocked on this point

**Comment by Omu0503** [comment]
have you tried using other plugins? or should we natively code it?

**Comment by cyberneid** [comment]
I have a native iOS code and it works. I'm now moving my app to flutter but this package has that problem

**Comment by ugochirico** [comment]
I have a native iOS code and it works. I'm now moving my app to flutter but this package has that problem

**Comment by Omu0503** [comment]
could you share the nativer code

**Comment by Ashok-Bhati** [comment]
I tried it with `pauseFor` attribute and it worked for me, It stops after 3 seconds if I didn't utter anything. I tested it with Iphone 11 with iOS 17.4.1.

```
_speech.listen(pauseFor: Duration(seconds: 3), onResult: (result) {
   FFAppState().update(() {
   FFAppState().sttWords = result.recognizedWords;
   });
 });
```

**Comment by sowens-csd** [comment]
Is this only a problem on iOS 16.5? Did you try the example app and does it do the same thing? Can you try running with the `debugLoging` flag set to true on the `initialize` method and then post the resulting log?
