### ISSUE TITLE
Wan't to Add some extra languages, working in andriod but thworing exception in IOS

### ISSUE THREAD

**Issue by sachin2151** [csdcorp/speech_to_text#520]
Hi, I am trying to enforce locale_id (for eg : ta_IN, or_IN,etc) , its working in Android even if the List of Locales given by package doesn't consist it but in IOS its not working throwing exception.

I tried Adding Language to device by going to settings,Later 
var systemLocale = await speech.systemLocale();
this is giving the default language i have set to device but while using microphone its throwing error given below,

SpeechToText.listen (package:speech_to_text/speech_to_text.dart:465:7)

 throw ListenFailedException(e.message, e.details, e.stacktrace);

These is the message i am getting from log : "Failed to create speech recognizer"

**Comment by sowens-csd** [comment]
After you add the language to the device in settings does the language code show up in `speech.locales()`?

**Comment by Prateek0001** [comment]
@sowens-csd I am tried to set locale bn-IN working fine on Android but getting error on IOS 
Unhandled Exception: Instance of 'ListenFailedException'
#0      SpeechToText.listen (package:speech_to_text/speech_to_text.dart:477)

Here are the supported locale i am getting from _speech.locales() for ios

 ar-SA, yue-CN, ca-ES, zh-CN, zh-HK, zh-TW, hr-HR, cs-CZ, da-DK, nl-BE, nl-NL, en-AU, en-CA, en-IN, en-ID, en-IE, en-NZ, en-PH, en-SA, en-SG, en-ZA, en-AE, en-GB, en-US, fi-FI, fr-BE, fr-CA, fr-FR, fr-CH, de-AT, de-DE, de-CH, el-GR, he-IL, hi-IN, hi-Latn, hu-HU, id-ID, it-IT, it-CH, ja-JP, ko-KR, ms-MY, nb-NO, pl-PL, pt-BR, pt-PT, ro-RO, ru-RU, wuu-CN, sk-SK, es-CL, es-CO, es-419, es-MX, es-ES, es-US, sv-SE, th-TH, tr-TR, uk-UA, vi-VN
 
 Supported language for Android
 cmn_CN, cmn_TW, en_AU, en_CA, en_IN, en_IE, en_SG, en_GB, en_US, fr_BE, fr_CA, fr_FR, fr_CH, de_AT, de_BE, de_DE, de_CH, hi_IN, in_ID, it_IT, it_CH, ja_JP, ko_KR, pl_PL, pt_BR, ru_RU, es_ES, es_US, th_TH, tr_TR, vi_VN
 
 Please let me know is their any way i can add bn-IN in ios
