### ISSUE TITLE
ResultListener recognizedWords are bugged? [Android/Web]

### ISSUE THREAD

**Issue by OhioTeppich** [csdcorp/speech_to_text#521]
Hello, 

I am currently facing an issue on Android with the RecognizedWords from the ResultListener. On the following picture, you can see detailed what I mean. 
![Screenshot 2024-05-14 at 13 03 39](https://github.com/csdcorp/speech_to_text/assets/124285972/c42c55d1-9040-49c3-9159-8f0a908fb4fc)
I want to speak: "Hello this is my" and u can see the result above.
I am using a Galaxy A53 5G on Android version 14 and the Chrome Browser version 124.0.63671.171.

I do not face this issue on iOS or Web(Chrome) on a PC.

If u need my implementation or anything else, please don't hesitate to ask for it. 

Thanks for the Help!

**Comment by sowens-csd** [comment]
Yes, Chrome on Android has a very unusual interpretation of the speech interface. There is a fix you can make but you'll have to test the user agent to ensure it's appropriate. Use the `SpeechToText.webDoNotAggregate` option in the `initialize method. That looks like this:
```dart
await speech.initialize(
        onError: errorListener,
        onStatus: statusListener,
        options[ SpeechToText.webDoNotAggregate ],
      );
```

Please let me know if this helps.

**Comment by OhioTeppich** [comment]
The option works fine on my Device and it's fixed. Thanks!

Is there any common way to test of the user agent is appropriate?

**Comment by sowens-csd** [comment]
I haven't looked up the details to detect Chrome on Android. If you do find a good method to do the detection in Flutter maybe you could post it here and I'll add it to the README?

**Comment by OhioTeppich** [comment]
Here's how I resolved the issue:

To retrieve device-specific information, I added the package device_info_plus: [device_info_plus](https://pub.dev/packages/device_info_plus).

Using this package, you can obtain the necessary information and add specific options when the application is running on a specific device and browser. Here's the code I used:

```
import 'package:device_info_plus/device_info_plus.dart';

final deviceInfoPlugin = DeviceInfoPlugin();
final deviceInfo = await deviceInfoPlugin.deviceInfo;
final allInfos = deviceInfo.data;
List<SpeechConfigOption>? options;

const List<BrowserName> browserNames = [BrowserName.chrome];
const String deviceName = 'Android';

const String browserName = 'browserName';
const String appVersion = 'appVersion';

if (browserNames.contains(allInfos?[browserName]) &&
    allInfos?[appVersion].contains(deviceName)) {
  options = [SpeechToText.webDoNotAggregate];
}

final hasSpeech = await speech.initialize(
  onError: errorListener,
  onStatus: statusListener,
  options: options,
);
```

With this code, the application checks for specific browser and device information before initializing the speech recognition with the appropriate options.

**Comment by sowens-csd** [comment]
That doesn't look like the same issue to me. That looks like you are getting intermediate and final results. You should either ask just for final results in your `listen` method or check the `finalResult` property of the returned result.

**Comment by sowens-csd** [comment]
I've added this to the docs for 6.6.2 which is on pub.dev now.
