### ISSUE TITLE
android , if no network, I got error: error_language_not_sopported

### ISSUE THREAD

**Issue by spiderman16888** [csdcorp/speech_to_text#529]
in android  phone , android 12 , if no network , also turn off wifi and 4g/5g networks, I got the error: error_language_not_sopported
the speech recognized can't works.
![Screenshot_20240619_112753](https://github.com/csdcorp/speech_to_text/assets/34176915/391ee573-24a4-43b6-a9ce-24b239f21bab)

**Comment by sowens-csd** [comment]
That sounds like expected behaviour, Android generally depends on a network connection for speech recognition unless you explicitly request on device processing and even then it may only work for some languages.
