### ISSUE TITLE
iPhone's volume is low when trying to call listen method

### ISSUE THREAD

**Issue by yoshoten-i-sol** [csdcorp/speech_to_text#53]
Hey,
Thank you for your hard working.

When I calling the listen method, then iPhone's volume is too low.

Finally found this question to solved it.
Comment this line 
try self.audioSession.setMode(AVAudioSession.Mode.measurement)
volume is working normal

Is it a right way?

**Comment by sowens-csd** [comment]
Interesting. I did a little research and it certainly looks like you're right that there's a problem with volume when using that setting. I'll make that setting optional in the next release of the library. It's only used for the sound level callback and that's not even working in iOS yet. In the meantime you can definitely comment out that line for a local build and it should be fine.

**Comment by yoshoten-i-sol** [comment]
Thank you for your advise.
Waiting for your next release.
