### ISSUE TITLE
Error 9 on Android Emulator

### ISSUE THREAD

**Issue by zerowu49** [csdcorp/speech_to_text#531]
Error Message:

D/SpeechToTextPlugin(12135): Notify status:listening
D/SpeechToTextPlugin(12135): Start listening done
[log] Received listener status: listening, listening: true
D/SpeechToTextPlugin(12135): In RecognizerIntent apply
D/SpeechToTextPlugin(12135): put model
D/SpeechToTextPlugin(12135): put package
D/SpeechToTextPlugin(12135): put partial
D/SpeechToTextPlugin(12135): put languageTag
**D/SpeechToTextPlugin(12135): Error 9 after start at 130 1000.0 / -100.0**
[log] Received listener status: notListening, listening: false
D/SpeechToTextPlugin(12135): Notify status:notListening
[log] Received listener status: done, listening: false
**[log] Received error status: SpeechRecognitionError msg: error_permission, permanent: true, listening: false**

What is this mean? I already state all of the requirement and the example works correctly on the device. But, when I tried to apply in my project, it shows this error.

**Comment by sowens-csd** [comment]
If the example app is working properly on the device then it sounds like your app either does not have the required permissions in the manifest or the user rejected the request on the device.
