### ISSUE TITLE
Not working with many browsers

### ISSUE THREAD

**Issue by lincoln1clarke** [csdcorp/speech_to_text#532]
Running as a web app on Brave on windows, when listen is called, it asks microphone permission and appears to be listening, but it outputs no text.  On Chrome on Android, it somewhat works, but it will repeat everything you say many times.

I haven't tried SpeechToText.webDoNotAggregate because I wasn't able to find any example code with it and don't know how to integrate it.  Would that fix the Chrome Android issue?
On Chrome on Windows, it works perfectly though.

It would be great if it would support more browsers across devices.

**Comment by sowens-csd** [comment]
There is an example in the issues list of using webDoNotAggregate, it is listed in the README. 

Unfortunately browsers do not all support speech recognition and the package is dependent on the browser. It would certainly be preferable if all browsers fully supported it but AFAIK they do not yet.
