### ISSUE TITLE
Does it uses device resources for comuputation or some cloud server ?

### ISSUE THREAD

**Issue by EuclidStellar** [csdcorp/speech_to_text#536]
Can you explain me the internal working of this package in short ?

**Comment by EuclidStellar** [comment]
so if it uses on-device processing then how it works? like I tried to use the whisper-medium model by OpenAI it was similar in comparison to `speech_To_text` in terms of confidence level and response time 
so I want to know how this `speech_to_text` works ? is it trained on a model, or does it use some algorithms to calculate recognised words by pattern matching with phonemes? 

please explain in simple steps what happen in between ( from when I speak to it get display in text field ) ?
I will be more than thankful to you for this

**Comment by sowens-csd** [comment]
The details vary by platform but the plugin does not handle speech recognition. Instead it calls platform APIs that provide speech services for that platform. So iOS has an implementation as does Android, etc.

**Comment by EuclidStellar** [comment]
Thanks
