### ISSUE TITLE
Is there a way to listen for changes to SpeechToText.isListening? 

### ISSUE THREAD

**Issue by LampeMW** [csdcorp/speech_to_text#538]
I have a button in my app to start/stop the microphone speech to text process. On Android specifically, once the user stops speaking for a short period of time, the OS plays a sound and the listening stops. I would like to listen for this change and be able to automatically update the UI once listening has stopped. Currently I am using a timer and checking _speechToText.isListening every 50ms but I wasn't sure if there was an easier way to listen for this change.

**Comment by sowens-csd** [comment]
You can use the `onStatus` listener on the `initialize` method.

**Comment by LampeMW** [comment]
Thank you! I totally missed that the `initialize` method had  properties I could use. Thanks again for the quick reply.
