### ISSUE TITLE
failing recognition on ios simulators when connected via BT headset

### ISSUE THREAD

**Issue by BluePasta23** [csdcorp/speech_to_text#539]
I thought I would quickly share this, since it did cost some time:
- Example programs would run on Android emulators
- Example programs failed on iOS simulators, all permissions set, etc.pp.
- Symptoms: program goes briefly into listening then exiting 
- Turned out, I had  BT headset connected to the Mac Mini, switching to a cabled headset made it work.
- I could not test this on a real device yet.

Best

BP

**Comment by sowens-csd** [comment]
Thanks for sharing, I'll add this to the README. AFAIK this does work on a real device though I have seen a report of a possible issue with AirPods.
