### ISSUE TITLE
reset the buffer of Recognized Words

### ISSUE THREAD

**Issue by benlyazid** [csdcorp/speech_to_text#546]
Hi, I am working on an app like a voice chat but the problem is that I can't reset the recognized words buffer after each voice message because each time  I want to get recognized words it returns all the words from the beginning,
Is there any solution to that?

I have tried to add the resetBuffer() function in the SpeechRecognitionResult class that clears the alternates list, but it doesn't work.

**Comment by sowens-csd** [comment]
Sounds like you might be getting intermediate results? You can control that by setting the `SpeechListenOptions.partialResults' to false when you call `listen`. That way the results callback will only be triggered with the final results. Alternately you can use the `finalResult` property of the `SpeechRecognitionResult` to see if the results are final.
