### ISSUE TITLE
just_audio and speech_to_text version conflict

### ISSUE THREAD

**Issue by alibad** [csdcorp/speech_to_text#548]
Because no versions of just_audio match >0.9.39 <0.10.0 and just_audio 0.9.39 depends on just_audio_web ^0.4.11, just_audio ^0.9.39 requires just_audio_web ^0.4.11.
And because no versions of just_audio_web match >0.4.11 <0.5.0, just_audio ^0.9.39 requires just_audio_web 0.4.11.
And because just_audio_web 0.4.11 depends on web >=0.3.0 <0.6.0 and speech_to_text >=7.0.0-beta.2 depends on web ^1.0.0, just_audio ^0.9.39 is incompatible with speech_to_text >=7.0.0-beta.2.
So, because your app depends on both speech_to_text ^7.0.0 and just_audio ^0.9.39, version solving failed.
2

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on speech_to_text: flutter pub add speech_to_text:^7.0.0-beta.1

**Comment by alibad** [comment]
for this reason, I am staying on speech_to_text: ^7.0.0-beta.1

**Comment by sowens-csd** [comment]
You can also do a dependency override until just_audio updates their dependency.
