### ISSUE TITLE
 error_busy - true

### ISSUE THREAD

**Issue by iampopal** [csdcorp/speech_to_text#55]
getting error  error_busy - true even I stop speech to text before listening.

**Comment by sowens-csd** [comment]
Which version of the plugin are you using? I'd be interested if this was still happening in the latest version. There were some problems with the threading model of earlier versions that could have caused this. If you are using the latest version then I'll look into it.

**Comment by iampopal** [comment]
I am using the latest version

**Comment by iampopal** [comment]
Yes, the current versions  have this problem

**Comment by dumbbell** [comment]
Hi!

I started to use `speech_to_text` today and when I tried the example application on my phone (ZTE Axon 7 A2017G running Android 8), I also get the same error.

**Comment by dumbbell** [comment]
After killing all applications running, the error is gone and the example application works. I suppose the error was genuine in my case, not the fault of `speech_to_text`.

**Comment by sowens-csd** [comment]
Thanks for letting me know. I'll close this then.

**Comment by iampopal** [comment]
I got this error again in 2.1.0 version 
And after killing the application, the error gone.

**Comment by iampopal** [comment]
I produce this error by calling listen and stop multiple time and saying anything
