### ISSUE TITLE
Version 7.0.0 is incompatible with firebase_core

### ISSUE THREAD

**Issue by PetrKubes97** [csdcorp/speech_to_text#551]
Incompatible package: https://pub.dev/packages/firebase_core/install

> Because firebase_core_web 2.17.5 depends on web ^0.5.1 and no versions of firebase_core_web match >2.17.5 <3.0.0, firebase_core_web ^2.17.5 requires web ^0.5.1.
And because speech_to_text >=7.0.0-beta.2 depends on web ^1.0.0, speech_to_text >=7.0.0-beta.2 is incompatible with firebase_core_web ^2.17.5.
And because firebase_core 3.4.0 depends on firebase_core_web ^2.17.5 and no versions of firebase_core match >3.4.0 <4.0.0, speech_to_text >=7.0.0-beta.2 is incompatible with firebase_core ^3.4.0.
So, because **** depends on both firebase_core ^3.4.0 and speech_to_text ^7.0.0, version solving failed.

**Comment by sowens-csd** [comment]
You can use a dependency override to get around that issue until firebase catches up. Or stick with the older version of STT.
