### ISSUE TITLE
listen Time in android

### ISSUE THREAD

**Issue by MoazzamAliSE** [csdcorp/speech_to_text#554]
The listen time is inconsistent in android, but in ios it works fine. why there is very less time in android for listen?
although i had set the time to 1 day/ 1 hour but nothing works. we need continuous listening just like in ios. Thank you.

await _speechToText.listen(
      onResult: (result) {
        _onResultListener(result);
      },
      listenFor: const Duration(days: 1),
      pauseFor: const Duration(days: 1),
      listenOptions: SpeechListenOptions(listenMode: ListenMode.deviceDefault),
    )

**Comment by sowens-csd** [comment]
Yes, Android has a fixed listen time that cannot be overridden. This is covered in the README and in numerous issues here.

**Comment by MoazzamAliSE** [comment]
yeah, i also researched about this that android has fixed listen time due to privacy concern. Thanks.

**Comment by MoazzamAliSE** [comment]
But in some applications like, google translate and the inbuilt keyboard's speech to text has more time.

<img width="103" alt="Screenshot 2024-09-13 at 10 16 51 AM" src="https://github.com/user-attachments/assets/b68a5266-d970-4578-8842-c587b29a0fdc">

**Comment by sowens-csd** [comment]
Yes, Google has access that they don't expose through the API unfortunately.
