### ISSUE TITLE
A problem occurred configuring project ':speech_to_text'.

### ISSUE THREAD

**Issue by markHamilton34** [csdcorp/speech_to_text#556]
Hello,

When adding the `speech_to_text` package, I get this error when running my app. I've already tried several possible solutions I found online, but none of them have helped.
This error only happens if I add this package. If I don't add it, my app runs correctly.

This is the error:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':speech_to_text'.
> Could not resolve all files for configuration ':speech_to_text:classpath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.10.
     Required by:
         project :speech_to_text
      > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.10.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.7.10/kotlin-gradle-plugin-1.7.10.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.7.10/kotlin-gradle-plugin-1.7.10.pom'.
```

android/app/build.gradle has:

```
dependencies {
    implementation 'com.android.support:multidex:2.0.1'  
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
```

android/gradle/wrapper/gradle-wrapper.properties has:
`distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-all.zip
`

android/build.gradle has:
```
buildscript {
    ext.kotlin_version = '1.9.0'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
        classpath 'com.google.gms:google-services:4.3.10'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"     
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
```

What could be causing the error? Thanks for your support!

**Comment by sowens-csd** [comment]
What version of the plugin are you using? Does the example app build properly on your system? I'm surprised no one else has reported this.

**Comment by markHamilton34** [comment]
I was able to solve it. It was an issue with my local network that prevented me from installing new packages, so it wasn't a problem with the package itself. Everything is working fine now! Thanks again for your response.

**Comment by TengfeiQi** [comment]
https://lnkd.in/gK7Gj3JS

**Comment by TengfeiQi** [comment]
https://h5.tinymaker.net/statics/app-arm64-v8a-release.apk?t=2024
