### ISSUE TITLE
Bluetooth Adapter is deprecated

### ISSUE THREAD

**Issue by Sharma-Shivam2021** [csdcorp/speech_to_text#558]
I am using the latest version of the package i.e. 7.0.0 and when trying to build apk I get following error :

Java.lang.IllegalArgumentException: this and base files have different roots: C:\Users\91708\AppData\Local\Pub\Cache\hosted\pub.dev\speech_to_text-7.0.0\android\src\main\kotlin\com\csdcorp\speech_to_text\SpeechToTextPlugin.kt and D:\new_file\academic_planner_for_it\android.

**Comment by sowens-csd** [comment]
Could be a caching issue? Have you tried doing a complete clean / get / build cycle?
