### ISSUE TITLE
2 bips

### ISSUE THREAD

**Issue by Mr-NYA** [csdcorp/speech_to_text#56]
I hear two beeps after speech detection, how can I fix that??

**Comment by sowens-csd** [comment]
It is built into the Android implementation of speech recognition and not part of the plugin. Currently there is no way to avoid that. I may add some work arounds in future versions if there is enough interest. The work arounds are fairly heavy handed though and would likely have other side effects.

**Comment by sowens-csd** [comment]
I think this may be related to #61 going to close this as either expected or duplicate.

**Comment by Fhyrel** [comment]
> It is built into the Android implementation of speech recognition and not part of the plugin. Currently there is no way to avoid that. I may add some work arounds in future versions if there is enough interest. The work arounds are fairly heavy handed though and would likely have other side effects.

Did you find a workaround to avoid the Android system "bips" while starting and ending to listen?

**Comment by Fhyrel** [comment]
> > It is built into the Android implementation of speech recognition and not part of the plugin. Currently there is no way to avoid that. I may add some work arounds in future versions if there is enough interest. The work arounds are fairly heavy handed though and would likely have other side effects.
> 
> Did you find a workaround to avoid the Android system "bips" while starting and ending to listen?

I found one myself. I used another library to set to 0 the NOTIFICATIONS volume while listening and putting again to the previous after finishing to listen the user.
