### ISSUE TITLE
Does the plugin support Traditional Chinese?

### ISSUE THREAD

**Issue by verisorry** [csdcorp/speech_to_text#567]
Hi, I can't seem to get it to work with zh_TW or zh-TW, I've tried both. When I print out the locales using speech.locales(), it gives me Locale Name: 中文 (繁體中文,台灣), Locale ID: zh_TW. However, when I actually set the speech.listen(localeID: 'zh_TW'), it still returns simplified chinese. Please help.

**Comment by zhukovaskychina** [comment]
If the author does not support this feature, you can add an adapter to the plugin's return results that converts Simplified Chinese to Traditional Chinese.

**Comment by sowens-csd** [comment]
Unfortunately that is down to recognition and transcription capability of the device, the plugin does not control this. I agree with @zhukovaskychina that their suggested mitigation may be the best way forward.
