### ISSUE TITLE
Detected words omitted in final result.

### ISSUE THREAD

**Issue by ParthaTezU** [csdcorp/speech_to_text#570]
I have been working on an app that requires certain non-dictionary words. When speaking them, the words are correctly transcribed initially, and I can see the output, but later after my speech is over, the words are omitted. 

Example: When I speak "Chira seven packets," I can see the output being correct initially, however the final result only gives "seven packets."

**Comment by sowens-csd** [comment]
Unfortunately that's down to the speech recognition of the device you are using, the plugin does not control the interpretation of speech. Did you check the alternate transcriptions that are provided in the result list? I'm curious if there are any versions with the non-dictionary words included. Also, you could try changing the `listenMode` to see if it performs any differently.
