### ISSUE TITLE
android.permission.MODIFY_PHONE_STATE [MissingPermission]

### ISSUE THREAD

**Issue by PHPJourney** [csdcorp/speech_to_text#571]
In issue #457 ,I am try install speech_to_text, from version ***6*** to ***latest***. get permission error by **MODIFY_PHONE_STATE**. but the permission is system permission. I can't use it

please fix it.

```
src/main/kotlin/com/csdcorp/speech_to_text/SpeechToTextPlugin.kt:320: Error: Missing permissions required by BluetoothHeadset.startVoiceRecognition: android.permission.BLUETOOTH_CONNECT and android.permission.MODIFY_PHONE_STATE [MissingPermission]
```

**Comment by higley** [comment]
I'm having the same experience. Been trying different versions of Gradle and this library but can't resolve. This is on a brand new Flutter app. iOS builds fine, just Android fails.

**Comment by sowens-csd** [comment]
Does the sample app work on your device? If so have you changed your manifest to match the permissions listed in the sample app?

**Comment by sowens-csd** [comment]
This permission was incorrectly in some versions of the plugin. Try the beta and see if it resolves it for you.
