### ISSUE TITLE
speech_to_text does not work well on some devices

### ISSUE THREAD

**Issue by huynhphu-pufu** [csdcorp/speech_to_text#62]
Hi admin, I have tested my project again and found that, when my application was installed on devices running Galaxy On5 2016 SM-G5510 (Android 6.0.1), Nokia 6 (Android 7.1), Redmi 6 Pro (MIUI 11.0.4 - Android 9), Galaxy A6+ (Android 10). The result is Nokia 6 and Galaxy A6+ working fine. But with Redmi 6 Pro, the initialized command can not be run. And with Galaxy On5 2016, the command can be initialized, I can choose language, but when I start listening, it's stop right away, and response status is "error_audio_error - true".

**Comment by sowens-csd** [comment]
Did you check the Troubleshooting section in the readme? There are a few linked threads that I think might be related to these issues. Speech recognition isn't always properly configured on Android devices by default and can require extra steps.

**Comment by huynhphu-pufu** [comment]
Ok, I got it, thank you so much.
