### ISSUE TITLE
Did somebody found a trick or workaround to continuosly get speech and don't stop while not listening a voice??

### ISSUE THREAD

**Issue by Fhyrel** [csdcorp/speech_to_text#63]
I need to continuosly listen the voice over the silences. When a "silence" comes i get "error_no_match". I tried to restart the listening every time I get "error_no_match", but it is not reliable. In the moment the service stops and restarts I have a void where I can't get the voice and I lose the meaning..

**PLS help if you have found something useful.**

_Ivan._

**Comment by rk21forever** [comment]
I am also looking for same solution.
I tried Future delay but it is not logically correct to use it after every interval.
Please help

**Comment by koyadovic** [comment]
Same here.

**Comment by sowens-csd** [comment]
I am experimenting with workarounds for this for some use cases, I don't know when I'll have something to share. However, if you are looking for more of a background command listener then I think it would be better to look at integration with either Siri or Google Assistant.

**Comment by notricks9** [comment]
can you do a loop and if returns error_no_match then run until it does not equal error_no_match?

**Comment by akk99** [comment]
Looking for the same trick. There is a google-made transcription device which does not stop at all.

**Comment by Fhyrel** [comment]
I've found a method for my use-case. I needed to listen to the voice while the user wasn't watching the phone. Better if it is in a pocket. So I used the wakelock to stay in foreground, then I made myself an Android plugin to catch the hearset's media button and with the plugin's method channel callback I start to listen the voice 🤙

Inviato da Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by akk99** [comment]
Would you be able to share the trick? BTW, was wakelock essential for cases when app remains in foreground with screen on?

**Comment by AlexHartford** [comment]
I've got something working, basically just listening to the stream from SpeechToTextProvider and whenever a FinalRecognitionEvent or ErrorEvent comes through, start listening again.
Example:
https://github.com/AlexHartford/voice_control_ui/blob/master/packages/voice_control_ui/lib/speech.dart

**Comment by EskAere** [comment]
@AlexHartford Is it working seamlessly for you ? I also the continuous listening, but on Android, i have some "dead" time periods where listening doesn't work... Seems to be because of the super short speech timeout

**Comment by Fhyrel** [comment]
> @AlexHartford Is it working seamlessly for you ? I also the continuous listening, but on Android, i have some "dead" time periods where listening doesn't work... Seems to be because of the super short speech timeout

Exactly. Doesn't work on Android, due to speech to text device's timeout. You can't control it.
So I used the wakelock to stay in foreground, then I made myself an Android plugin to catch the hearset's media button and with the plugin's method channel callback I start to listen the voice. I didn't found another method, but this one is fine form me.

**Comment by mahbubur-87** [comment]
Source-Ref: 'package:speech_to_text/speech_to_text.dart'
[listenFor] sets the maximum duration that it will listen for, after that it automatically stops the listen for you.
[pauseFor] sets the maximum duration of a pause in speech with no words detected, after that it automatically stops the listen for you.
`await _speechToText.listen(onResult: _speechResult, 
                                listenFor: Duration(minutes: 20),
                                pauseFor: Duration(minutes: 20));`

Please see the SpeechToText class file to get more information.
