### ISSUE TITLE
What is the 'Stress' logic used for?

### ISSUE THREAD

**Issue by cristianrablau** [csdcorp/speech_to_text#64]
What are the methods stressTest() and changeStatusForStress() used for in the example from [here](https://pub.dev/packages/speech_to_text#-example-tab-) ?

The logic seems to be a bit strange and not really necessary, but I'm pretty sure there is a good reason behind it.

**Comment by sowens-csd** [comment]
I use them to test that the plugin isn't leaking resources under repeated use. They're not really of interest for users of the plugin, I should probably remove them from the primary example and put them in a separate app.

**Comment by cristianrablau** [comment]
Yeah, probably it is better to remove them. It was a bit confusing not knowing if I have to make a stress test before actually starting the listener for real use. Anyway, it is really nice that you do this kind of tests 😄

**Comment by sowens-csd** [comment]
Stress moved out to a separate app.
