### ISSUE TITLE
Speech_recognition outputs the response after 20 seconds 

### ISSUE THREAD

**Issue by sagar2411** [csdcorp/speech_to_text#68]
I was going through the speech_to_text plugin and I found a wired issue that is when I start the recognition and speak some words like "hello world ", So it takes around 20 seconds to respond, saw this issue: https://github.com/csdcorp/speech_to_text/issues/55.
But I did not found any solution(Killing the application may not be the solution, as it occurs later after some time). Using the latest version of speech_to_text(speech_to_text: ^2.1.0) 

And onRecognitionResult is also getting called twice for the first time.

**Comment by sowens-csd** [comment]
Is this iOS, Android or both? Are you getting partial results or just final? See the `partialResults` parameter on the `listen` method. 

This is possibly expected behaviour if it is on iOS and you have asked only for final results. iOS will allow a long pause in speech before processing the final results.

**Comment by sagar2411** [comment]
This is for the final I have not checked for the partial results and this behavior is happening on the android device not checked on the ios though.
Maybe I have encountered the wired situation like when the internet connection has low speed this issue I get is  onRecognitionResult gets called twice. But when the internet connection with good speed is working fine. 
Thanks.

**Comment by sowens-csd** [comment]
That sounds like an expected result then. Let me know if you think there's an issue other than the Internet connection.

**Comment by sagar2411** [comment]
Can this issue happen because of the internet connection, like googled it and then I knew this can also be a issue. Have you faced this kind of issue

**Comment by sowens-csd** [comment]
Yes. Speech recognition may use the network and slow or unavailable connections can slow it down or cause errors.

**Comment by sagar2411** [comment]
Ok, got it, by the way, thanks for the Plugin and its really great.
