### ISSUE TITLE
Cannot start speech to text twice

### ISSUE THREAD

**Issue by Fhyrel** [csdcorp/speech_to_text#74]
Hi. I start explaining my needs:

I am developing a page to handle the click on a headphone button, then start using the speech to text , so I use the recognition to handle different commands and the text to speech to tell the user the command used.

If I follow this flow, at first time it goes veeery well. But if I close this page, then come back again, when I start the recognition again, I don't see the volume update (the circles around the mic icon) and it don't catch my voice.

Seems also like the "second" initialization of speech doesn't go or have some problems..
HERE is first initialization logs:
```
Starting input: tba=android.view.inputmethod.EditorInfo@a35a8a0 nm : com.plusadvance.hailmanagement.cattolica ic=null
I/InputMethodManager(21288): startInputInner - mService.startInputOrWindowGainedFocus
D/SpeechToTextPlugin(21288): completeInitialize
D/SpeechToTextPlugin(21288): Testing recognition availability
D/SpeechToTextPlugin(21288): Creating recognizer
D/SpeechToTextPlugin(21288): Setting listener
D/SpeechToTextPlugin(21288): before setup intent
D/SpeechToTextPlugin(21288): setupRecognizerIntent
D/SpeechToTextPlugin(21288): after setup intent
D/SpeechToTextPlugin(21288): sending result
D/SpeechToTextPlugin(21288): leaving complete
D/SpeechToTextPlugin(21288): In RecognizerIntent apply
D/SpeechToTextPlugin(21288): put model
D/SpeechToTextPlugin(21288): put package
D/SpeechToTextPlugin(21288): put partial
```

HERE is second initialization logs:
No logs...

Do you alredy know an issue like that or i have to provide you some code / log?

Extra:
To handle the click on headphone I use AudioService background service. Then I call an isolate to listen for an event between the AudioService and my UI (to handle the click on headphone that calls a function that start speech to text  listening)

**Comment by sowens-csd** [comment]
You only need to initialize the speech_to_text package once per application invocation. Any subsequent calls to initialize are ignored because they are not needed. After a successful initialized you should use the `listen`, `stop`, and `cancel` methods to start and stop listening sessions.

**Comment by Fhyrel** [comment]
> You only need to initialize the speech_to_text package once per application invocation. Any subsequent calls to initialize are ignored because they are not needed. After a successful initialized you should use the `listen`, `stop`, and `cancel` methods to start and stop listening sessions.

If it is my real problem it does more than just ignoring it, but I will test. So I can init it in my Splash for example and use it later in another page, right? I'm going to test

**Comment by sowens-csd** [comment]
I'm going to close this issue as expected. If you are still having problems just open another issue.
