### ISSUE TITLE
Is there any support for locale?

### ISSUE THREAD

**Issue by kevincmanning** [csdcorp/speech_to_text#8]
I'm writing an app that requires Japanese speech-to-text, but every speech to text lib (only 2 of them, this one included) doesn't seem to have Japanese

**Comment by alexnaldo** [comment]
I need it too, but for pt-BR

**Comment by sowens-csd** [comment]
So sorry, for some reason I haven't been getting notified on these issues. I'm just putting out a release that provides Locale support. This will support any languages that are supported by the device OS. It should be released in a couple of days. I do see Japanese as a supported language at least on some devices. If this is still a current need for you then please give it a try as soon as it is released.

**Comment by sowens-csd** [comment]
The 0.7.0 release is posted to pub.dev now. It supports changing the recognition language using the localeId parameter of the `listen` method. There's also functionality to discover the available locales through the `locales` method. 

I should have pointed out that the previous version already supported whatever language is selected on the device. This new functionality allows you to handle language recognition in a language other than the current device language. 

I'll leave this issue open until next week. If you have a chance maybe you could try out the new functionality and let me know if it covers your use case?

**Comment by sowens-csd** [comment]
Closing this now. Please open a new issue if you have any further questions.
