### ISSUE TITLE
Unexpected exception, Can only use lower 16 bits for requestCode

### ISSUE THREAD

**Issue by scalz** [csdcorp/speech_to_text#81]
Hello,

Thank you for sharing your work.

I tried your example and it works very well with my phone.
Now, I would like to add STT to my app but I'm getting 'Unexpected exception, Can only use lower 16 bits for requestCode'.

I feel (but not sure) this is related to the fact I'm using local_auth package, which requires the use of a FragmentActivity as opposed to Activity. So my MainActivity class extends FragmentActivity.

It seems related to this:
https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-master-dev/fragment/fragment/src/main/java/androidx/fragment/app/FragmentActivity.java?source=post_page&autodive=#768

Below is what I get in logs:
`I/flutter (27685): activateSpeechRecognizer... 
E/SpeechToTextPlugin(27685): Unexpected exception
E/SpeechToTextPlugin(27685): java.lang.IllegalArgumentException: Can only use lower 16 bits for requestCode
E/SpeechToTextPlugin(27685): 	at androidx.fragment.app.FragmentActivity.checkForValidRequestCode(FragmentActivity.java:715)
E/SpeechToTextPlugin(27685): 	at androidx.fragment.app.FragmentActivity.validateRequestPermissionsRequestCode(FragmentActivity.java:730)
E/SpeechToTextPlugin(27685): 	at androidx.core.app.ActivityCompat.requestPermissions(ActivityCompat.java:500)
E/SpeechToTextPlugin(27685): 	at com.csdcorp.speech_to_text.SpeechToTextPlugin.initializeIfPermitted(SpeechToTextPlugin.kt:353)
E/SpeechToTextPlugin(27685): 	at com.csdcorp.speech_to_text.SpeechToTextPlugin.initialize(SpeechToTextPlugin.kt:201)
E/SpeechToTextPlugin(27685): 	at com.csdcorp.speech_to_text.SpeechToTextPlugin.onMethodCall(SpeechToTextPlugin.kt:151)
E/SpeechToTextPlugin(27685): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/SpeechToTextPlugin(27685): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/SpeechToTextPlugin(27685): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/SpeechToTextPlugin(27685): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/SpeechToTextPlugin(27685): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/SpeechToTextPlugin(27685): 	at android.os.Looper.loop(Looper.java:182)
E/SpeechToTextPlugin(27685): 	at android.app.ActivityThread.main(ActivityThread.java:7782)
E/SpeechToTextPlugin(27685): 	at java.lang.reflect.Method.invoke(Native Method)
E/SpeechToTextPlugin(27685): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/SpeechToTextPlugin(27685): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
E/flutter (27685): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(unknown, Unexpected exception, Can only use lower 16 bits for requestCode)
E/flutter (27685): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (27685): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (27685): <asynchronous suspension>
E/flutter (27685): #2      SpeechToText.initialize (package:speech_to_text/speech_to_text.dart:174:10)
`

Do you have any idea how this could be fixed please?

**Comment by sowens-csd** [comment]
Wow, what an odd little corner case that is. I've just pushed a fix for this to the repo. I don't know if anyone has run the plugin in a fragment yet so I'm not sure it will work but at least this issue should be resolved. I'm still working on a few iOS bugs with sound playback then I'll do a release to pub.dev. If you want a version sooner you could patch an older release. The only change required is at line 70 in SpeechToTextPlugin.kt. I changed from 78521 -> 28521.

**Comment by scalz** [comment]
@sowens-csd 
rolala.. indeed, I applied your change and it's working, awesome!
So far, this seems ok in a fragment.

Thank you very much for your help 👍
