### ISSUE TITLE
In Android - ERROR_SPEECH_TIMEOUT is not thrown

### ISSUE THREAD

**Issue by psgainz** [csdcorp/speech_to_text#82]
After calling the listen method, if I don't speak anything, it just stays like that. It does not throw any error at all. I need that error to be thrown for showing an error message. Please look at it ASAP.
Tried on Android 10.0 & Android 6.0

**Comment by sowens-csd** [comment]
I'll need more details, do you have a reproducible case using the example app on a real device? If so please give the exact steps to reproduce.

**Comment by psgainz** [comment]
I just implemented it normally. Like I have a button & clicking on it will call the listen method.
I implemented the other callbacks & just a print statement in each
So if I press the button, beep sound comes in & it starts recognition & gives me the result.

Now to reproduce this, I press the button, beep sound comes & I don't speak anything.
It should throw an error right?
The status callback prints - Listening, not listening, not listening

**Comment by sowens-csd** [comment]
Yes, you should see an error timeout. Do you see this behaviour in the example app?

**Comment by psgainz** [comment]
No, I ran the example app too, however I'm not getting the timeout error

**Comment by sowens-csd** [comment]
This seems similar to #73 but I haven't been able to reproduce it. Could you have a look at that issue and see if you think yours is similar and if you have any more information to help reproduce?

**Comment by psgainz** [comment]
Okay, I didn't notice correctly. The example is running fine & throwing the timeout error. But doing it in the same way with additional code is giving me a weird output. 
As soon as I click a button (that calls the listen method), the statusListener prints listening and not listening together. So I understand now that since the status changes to notListening, I am not getting the error. However I do not understand why is it changing & despite that, it still recognises & provides text result. I tried with the listenFor duration at 10 seconds & even by not setting it

**Comment by psgainz** [comment]
I'm not sure what the issue was, but I solved it by rewriting most of the code from start. I am closing this. Thank you.
