### ISSUE TITLE
Change Locale

### ISSUE THREAD

**Issue by blomqvistandreas** [csdcorp/speech_to_text#83]
Hello! First off, awesome package. Implemented it to an app and its super cool. Thanks for this!
Im curious, does it work to change the language? In that case, how does it work? I see that you use ( _currentLocaleId ) which seems like the right variable but Im clueless of what I should type in this String. 

Appreciate your package and help!

**Comment by blomqvistandreas** [comment]
Closing, found this out myself.
`_currentLocaleId = Locale('en').toString();`
Did the trick :)

**Comment by sowens-csd** [comment]
Thanks for the feedback. 

Yes, you can change the language and the speech recognition will respect the setting. You can get the list of available locales for the device using the `locales` method of the `LocalImageProvider`. It's used in the example app so you can see the flow.

**Comment by blomqvistandreas** [comment]
> Thanks for the feedback.
> 
> Yes, you can change the language and the speech recognition will respect the setting. You can get the list of available locales for the device using the `locales` method of the `LocalImageProvider`. It's used in the example app so you can see the flow.

Thank you very much! Now I can see all the locales, yay! 😄 🎉
