### ISSUE TITLE
licence

### ISSUE THREAD

**Issue by tuanha2000vn** [csdcorp/speech_to_text#84]
Thank for the awesome package, everything work right with just a few easy install step.

What is the cost of using the speech to text engine? For example 10.000 request per day then who do I need to pay to?

**Comment by sowens-csd** [comment]
Glad you're having a good experience with the package. 

There is no cost. The services are either provided on the user's device or by the device manufacturer / service provider. They will sometimes limit the number of requests that you can make to the underlying library so some errors are possible in high usage situations.

**Comment by tuanha2000vn** [comment]
What the service provider it is? On Android it's Google's Speech to Text Server and iOS is Apple's Speech to Text Server?

**Comment by sowens-csd** [comment]
Some of it is done entirely on device. For the server side for Apple yes, it would be entirely Apple. For Android there may be some variance by manufacturer. It is possible they could fork and include their own speech services. That layer is invisible to the plugin though.
