### ISSUE TITLE
Can`t pub get in pubspec.yaml

### ISSUE THREAD

**Issue by loGTve** [csdcorp/speech_to_text#86]
> The plugin `speech_to_text` doesn't have a main class defined in C:\flutter\.pub-cache\hosted\pub.dartlang.org\speech_to_text-2.1.0\android\src\main\java\com\csdcorp\speech_to_text\SpeechToTextPlugin.java or C:\flutter\.pub-cache\hosted\pub.dartlang.org\speech_to_text-2.1.0\android\src\main\kotlin\com\csdcorp\speech_to_text\SpeechToTextPlugin.kt. This is likely to due to an incorrect `androidPackage: com.csdcorp.speech_to_text` or `mainClass` entry in the plugin's pubspec.yaml.
If you are the author of this plugin, fix the `androidPackage` entry or move the main class to any of locations used above. Otherwise, please contact the author of this plugin and consider using a different plugin in the meanwhile. 
exit code 1

^^^^^^^
issues
FIX It Please...

**Comment by sowens-csd** [comment]
What version of Flutter are you using?

**Comment by sowens-csd** [comment]
Have a look at this thread and see if it helps. https://github.com/flutter/flutter/issues/52739.

**Comment by loGTve** [comment]
> Have a look at this thread and see if it helps. [flutter/flutter#52739](https://github.com/flutter/flutter/issues/52739).

Ow.. wew...  ITS work...  i did Delete   `.pub-cache`  in Folder `Flutter`
and do `flutter pub get`... 

someone who get same issue... try it.
