### ISSUE TITLE
IOS - Using in pair with sound recrder. onResult is never call for 2nd and other attemps.

### ISSUE THREAD

**Issue by KirylKaralkou** [csdcorp/speech_to_text#87]
Hello. Great thanks for a very useful plugin. But unfortunately I faced some strange behaviour while using it. A need to create an app that can record a sound for about 4 seconds. After that it should listen for speech and record the text. I'm using your plugin in pair with flutter_sound_lite 4.0.4+1 (https://pub.dev/packages/flutter_sound_lite). Everything working as expected for the first attempt. I record sound for 4 second after that I'm using this plugin and recognize text. 

But when I close the screen and open it again and try to do the same  - onResult is never called for iOS. (There are no errors, just "listening" and "notListening" statuses).

If you have any ideas what can be wrong, please share. Thanks in advance

**Comment by sowens-csd** [comment]
Can you try it with the repo version? My handling of the audio session wasn't quite right previously and the version in the repo has some fixes for that. Please let me know if it changes / fixes the behaviour.

**Comment by KirylKaralkou** [comment]
Thanks for fast reply. With repo version I can't reproduce this issue. Thanks so much, you saved my life!
