### ISSUE TITLE
 - `speech_to_text` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set.

### ISSUE THREAD

**Issue by DilrukshiRajapakshe** [csdcorp/speech_to_text#88]
When I try to run a project in iso simulator given this error. How can I overcome it?

 Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update

    Comparing resolved specification to the sandbox manifest
      A Flutter
      A speech_to_text

    Downloading dependencies

    -> Installing Flutter (1.0.0)

    -> Installing speech_to_text (0.0.1)
      - Running pre install hooks
    [!] Unable to determine Swift version for the following pods:

    - `speech_to_text` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/xcode/target_validator.rb:125:in `verify_swift_pods_swift_version'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/xcode/target_validator.rb:39:in `validate!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:590:in `validate_targets'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:158:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error running pod install
Error launching application on iPhone SE (2nd generation).

**Comment by ichitaka** [comment]
Same problem here

**Comment by sowens-csd** [comment]
Looks like you're possibly using a very old Flutter version (1.0.0). Assuming that's true I'd suggest that you update Flutter and try again.

**Comment by DilrukshiRajapakshe** [comment]
The Flutter version is up to date.

Flutter 1.17.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f7a6a7906b (6 days ago) • 2020-05-12 18:39:00 -0700
Engine • revision 6bc433c6b6
Tools • Dart 2.8.2

**Comment by sowens-csd** [comment]
I think what's happening is that your project supports Objective-C but not Swift. Was the project created a while ago? Newer versions of Flutter use Swift by default so new projects work properly without tweaks. 

Can you see if any of these help resolve the issue and if they do let me know which helped?  

https://github.com/csdcorp/speech_to_text/issues/45
https://stackoverflow.com/questions/54912188/flutter-plugin-ios-build-fail/54919007https://github.com/flutter/flutter/issues/25676

**Comment by DilrukshiRajapakshe** [comment]
@sowens-csd are you right. Thank you so much.

**Comment by tedserdel** [comment]
@DilrukshiRajapakshe 

I am experiencing the same error in Android Studio when launching lib/main.dart on iPhone SE (2nd generation) in debug mode. I used the Example code from the 'speech_to_text' package.

How did you resolve the error? I checked [#45](https://github.com/csdcorp/speech_to_text/issues/45) but I may have missed some parts. I am relatively new to Flutter and Dart.

**Comment by DilrukshiRajapakshe** [comment]
Because, when  a creating project you didn't provide a swift suport. tick the cheak box button of swift suport when your are creating in your flutter project.

**Comment by tedserdel** [comment]
I couldn’t find where to turn on Swift Compiler - Language. Instead, I just created a new project using the Terminal App.

1. On terminal app, I typed “Flutter create myapp”
2. Checked the project by opening “Runner.xcodeproj” file is under USER/myapp/ios
3. Tap Runner then find the Build Setting tab and look for Swift Compiler - Language, it should be set to Swift 5
4. On Android Studio open a file and browse for the “myapp” folder and open it.
5. Follow the “speech_to_text” installation instructions and permissions required for speech recognition.
6. Swap the code with the Example from the “speech_to_text” package.
7. Add onPressed and setState in the IconButton (error)

Just wanted to add it as a comment and hope I helps someone like myself that is just starting out.

Good luck!

**Comment by FDavidse20** [comment]
I'm experiencing the same problem. However I'm not working on a Flutter application, but a Flutter Module. That module will eventually be integrated in a native iOS app and a native Android app. 
One of the packages I need to use depends on speech_to_text. And that is causing me these issues.

I tried the suggestions above, but for a module I can't edit the Runner.xcodeproj or Android manifest in the same way, and it wouldn't make sense. Because the module will be integrated in native projects where the xcodeproj file (for iOS) and Gradle settings (for the android one) will be leading. 

Any suggestions on this specific case? Thank you.
