### ISSUE TITLE
How to get multiple ResultListeners working for the same speechController?

### ISSUE THREAD

**Issue by awarmfastbear** [csdcorp/speech_to_text#89]
Hi,

I am trying to set up two different voice inputs, one for inputting text, and one for getting voice input to verify and comparing the text from the first voice input. 

I thought it would be as simple as creating two StartListening functions that took a Function as argument that is passed to the 'onResult:' property. This results in the second listener starting successfully, but I don't get any  results from the 2nd resultListener, not even partial results get printed to the screen.

Any ideas?

I also tried using two SpeechControllers but I kept running into recognizer busy error messages so I thought it would be cleaner to pass a specific result listener :(, neither way seems to work..

This is a sample of the code I am using:

```dart
  // First Listener

  void startListeningForCardInput(Function resultListener) {
    lastWords = "";
    lastError = "";
    speechController.listen(
        onResult: resultListener,
        listenFor: speechTimeoutDuration,
        localeId: _currentLocaleId,
        onSoundLevelChange: soundLevelListener,
        cancelOnError: true,
        partialResults: true);
    setState(() {
      lastStatus = "Listening...";
    });
  }

  void myFirstResultListener(SpeechRecognitionResult result) {
    print("${result.recognizedWords} - ${result.finalResult}");
    // print(result.confidence);
    print(result);
    setState(() {
      lastWords = "${result.recognizedWords} - ${result.finalResult}";
      _textInputcontroller.text = "${result.recognizedWords}";
      lastStatus = "Words found from your voice, please review them. Ready.";
    });
  }

  // Second Listener
  void compareVoiceInput(Function resultListener) {
    speechController.listen(
        onResult: resultListener,
        listenFor: speechTimeoutDuration,
        localeId: _currentLocaleId,
        onSoundLevelChange: soundLevelListener,
        cancelOnError: true,
        partialResults: true);
    setState(() {
      lastStatus = "2nd listener...";
    });
    print("Test");
  }

  // No results are provided from this
  void mySecondResultListener(SpeechRecognitionResult result) {
    print(result.confidence); // Nothing printed
    print("${result.recognizedWords} - ${result.finalResult}");
    setState(() {
      secondVoiceInputTest = "${result.recognizedWords} - ${result.finalResult}";
    });
  }
```

**Comment by awarmfastbear** [comment]
Update, got it working! I didn't realize I was marking the argument as optional and the 2nd input trigger didn't have the 2nd listener specified.

If this is an inefficient way to do this I'd like to know a better way :)

**Comment by sowens-csd** [comment]
I'm not sure what you mean by 'comparing'? Are you starting both of the listeners at the same time? If so I don't think that will work. Or do you just want two separate listeners notified from the same listen session? Typically in my apps I create a Provider using a ChangeNotifier and handle the listen callbacks inside the provider. UI code just listen for changes broadcast by the Provider. I'm not sure what your goal is so I'm not sure if that would be useful for your use case.

**Comment by awarmfastbear** [comment]
My goal is to compare voice inputs. E.g. User triggers one voice listener, speaks, and it gets translated into 1 input field. Then they can tap a voice verification field by that input field to verify that the text / wording is the same from the 1st voice sample.

**Comment by sowens-csd** [comment]
Interesting, thanks for the update. Good luck with the project, I hope it works well and let me know if you have any issues with the plugin.
