### ISSUE TITLE
SpeechRecognitionError msg: error_audio_error on the Android emulator when used with a ChangeNotifier

### ISSUE THREAD

**Issue by awarmfastbear** [csdcorp/speech_to_text#90]
Hi,

I am new to Flutter and I am still trying to master state management. I am trying to build a global state in my app so I can modularization it better. With that I am trying to use the Provider package with the speech_to_text package.

I've learned that you should not set state on objects in provider classes. When I tried moving the speech controller initialize function into my provider class everything seems fine however when I try and trigger my speech listener method from the provider class to get text from a voice, I see the listener start and then stop with an error on my android emulator. This doesn't happen on my physical phone when testing which is super weird to me.

Code for my provider class: https://gist.github.com/awarmfastbear/3d3b10ef60c5bb994ae0d9bbcf09050d
I am testing on an Android emulator (Pixel 3a) using Android 10. It has been working fine before starting to refactor and use providers. If I test the app on my physical android phone (Pixel 3) this code works fine.

This is from a fresh start of the app on the emulator and triggering the `startFirstVoiceListener` method to start the voice to text action.
```dart
I/flutter ( 7118): getting locales..
I/flutter ( 7118): Speech engine initialized!
I/flutter ( 7118): listening
I/flutter ( 7118): error: SpeechRecognitionError msg: error_audio_error, permanent: true
I/flutter ( 7118): error: SpeechRecognitionError msg: error_audio_error, permanent: true
I/flutter ( 7118): notListening
I/flutter ( 7118): stopping..
```

I've double checked [permissions](https://i.imgur.com/HXgT5K1.png), made sure permissions are set in the manifest settings, etc. The app works fine on a physical phone like I mentioned.

I am triggering the startFirstVoiceListener method from a separate file in a widget like below.

```dart
...snippet

  final myvoiceFunctions = new VoiceFunctions();

...snippet

                    IconButton(
                        icon: Icon(Icons.mic),
                        onPressed: () {
                          myvoiceFunctions.startFirstVoiceListener();
                        }),
```

If I try loading the start listener function using a Provider method I get the same error behavior in the emulator:

```dart
                    IconButton(
                        icon: Icon(Icons.mic),
                        onPressed: () {
                          Provider.of<VoiceFunctions>(context, listen: false).startFirstVoiceListener();
                          // myvoiceFunctions.startFirstVoiceListener();
                        }),
```

Any ideas on how to debug this better? I am stuck :( 

**Update**: To add to the confusion, I created a new Android emulator using Android 8.1 and this code works :(, but it won't work on my Android 10 emulator.

**Comment by sowens-csd** [comment]
Speech recognition doesn't work on Android emulators. You need to use either a physical device for Android or the iOS emulator or a physical device.

**Comment by awarmfastbear** [comment]
> Speech recognition doesn't work on Android emulators. You need to use either a physical device for Android or the iOS emulator or a physical device.

What makes you say this?

I am saying it does work and has worked, in the Android emulator settings you can see microphone settings. Host audio for the emulator has been around for over a year year: https://androidstudio.googleblog.com/2019/01/emulator-28023-stable.html

It works fine for me on the emulator's Google assistant 'okay Google'. If I create a new Android emulator I can get the app to use it fine. It's just a specific VM of the Android emulator that I've been using which has stopped working with it..

**Comment by awarmfastbear** [comment]
Any way, this problem seemed to sort it self out :S. I ran Google Play updates, and made sure the voice input was working with the Google Assistant and my App / code started working like normal.

I'll close this out for ya. Thanks for all the great work you do!

**Comment by sowens-csd** [comment]
Thanks for letting me know. I've never gotten it to work on an emulator myself but I see now that it can work depending on the emulator and various Play Store apps that can be installed. I'll play around with it and update the docs accordingly.

**Comment by awarmfastbear** [comment]
They key tip is making sure the 'Google' app is fully up to date. It's best
to sign into Google on the phone with a burner account and update all the
apps on it.
