### ISSUE TITLE
status listener doesn't get called when coming 2nd time in android

### ISSUE THREAD

**Issue by prtrigno** [csdcorp/speech_to_text#91]
Here are the two scenarios. The first time it is working fine.
1. There are two screens A and B. Navigating from A to B > Initialize speech to text > press mic button and speak nothing > It works fine and Automatically stopped after a few seconds. Below are the logs:
D/SpeechToTextPlugin(13757): Start initialize
D/SpeechToTextPlugin(13757): Checked permission
D/SpeechToTextPlugin(13757): Requesting permission
D/SpeechToTextPlugin(13757): leaving initializeIfPermitted
D/SpeechToTextPlugin(13757): completeInitialize
D/SpeechToTextPlugin(13757): Testing recognition availability
D/SpeechToTextPlugin(13757): Creating recognizer
D/SpeechToTextPlugin(13757): Setting listener
D/SpeechToTextPlugin(13757): before setup intent
D/SpeechToTextPlugin(13757): setupRecognizerIntent
D/SpeechToTextPlugin(13757): after setup intent
D/SpeechToTextPlugin(13757): sending result
/SpeechToTextPlugin(13757): leaving complete
D/SpeechToTextPlugin(13757): In RecognizerIntent apply
D/SpeechToTextPlugin(13757): put model
D/SpeechToTextPlugin(13757): put package
D/SpeechToTextPlugin(13757): put partial
D/SpeechToTextPlugin(13757): Start listening
D/SpeechToTextPlugin(13757): setupRecognizerIntent
D/SpeechToTextPlugin(13757): Notify listening
D/SpeechToTextPlugin(13757): Notify listening done
D/SpeechToTextPlugin(13757): Start listening done
D/SpeechToTextPlugin(13757): In RecognizerIntent apply
D/SpeechToTextPlugin(13757): put model
D/SpeechToTextPlugin(13757): put package
D/SpeechToTextPlugin(13757): put partial
D/SpeechToTextPlugin(13757): put languageTag
I/flutter (13757): listening
I/flutter (13757): Received error status: SpeechRecognitionError msg: error_speech_timeout, permanent: true, listening: true
I/flutter (13757): error_speech_timeout - true
D/SpeechToTextPlugin(13757): Cancel listening
D/SpeechToTextPlugin(13757): Notify listening
D/SpeechToTextPlugin(13757): Notify listening done
D/SpeechToTextPlugin(13757): Cancel listening done
I/flutter (13757): notListening

2. After step 1, navigate back to screen A > Repeat step 1 but status listener doesn't get called. Below are the logs for 2 step:
D/SpeechToTextPlugin(13757): Start listening
D/SpeechToTextPlugin(13757): setupRecognizerIntent
D/SpeechToTextPlugin(13757): Notify listening
D/SpeechToTextPlugin(13757): Notify listening done
D/SpeechToTextPlugin(13757): Start listening done
I/flutter (13757): Received error status: SpeechRecognitionError msg: error_speech_timeout, permanent: true, listening: true
D/SpeechToTextPlugin(13757): Cancel listening
D/SpeechToTextPlugin(13757): Notify listening
D/SpeechToTextPlugin(13757): Notify listening done
D/SpeechToTextPlugin(13757): Cancel listening done

Do I need to call any function while going back or any other changes are needed? 
Below is the code for both classes:
```
class A extends StatefulWidget {
  @override
  _AState createState() => _AState();
}

class _AState extends State<A> {
@override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        child: Center(
          child: RaisedButton(
            child: Text("Next Page"),
            onPressed: () {
              Navigator.pushNamed(context, bRoute);
            },
          ),
        ),
      ),
    );
}
```

````
class B extends StatefulWidget {

  B({Key key}) : super(key: key);

  @override
  _BState createState() => _BState();
}

class _BState extends State<B> {
  final SpeechToText speech = SpeechToText();
  String lastWords = "";
  String lastError = "";
  String lastStatus = "";
  String _currentLocaleId = "";

  @override
  void initState() {
    super.initState();
    initSpeechState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("Home"),),
      body: Container(
       child: Center(
         child: IconButton(
              icon: Icon(speech.isListening ? Icons.stop : Icons.mic),
              onPressed:
                  speech.isListening ? stopListening : startListening,
            ),
        ),
      ),
    );
  }

   //Initializing Speech to text
  Future<void> initSpeechState() async {
    bool hasSpeech = await speech.initialize(
        onError: errorListener, onStatus: statusListener, debugLogging: true);
        if (hasSpeech) {
          _currentLocaleId = AppTranslations.of(context).locale.languageCode;
        }
  }

   //Speech to text methods
  Future<void> errorListener(SpeechRecognitionError error) async {
    print("Received error status: $error, listening: ${speech.isListening}");
    if (mounted) {
      setState(() {
        lastError = "${error.errorMsg} - ${error.permanent}";
        print(lastError);
      });
    }
  }

  void cancelListening() {
    speech.cancel();
    setState(() {});
  }

   Future<void> startListening() async {
    lastWords = "";
        lastError = "";
        speech.listen(
            onResult: resultListener,
            listenFor: Duration(minutes: 1),
            localeId: _currentLocaleId,
            cancelOnError: true,
            partialResults: false);
        setState(() {
        });
  }

   void stopListening() {
    speech.stop();
    if (mounted) {
      setState(() {
    });
    }
  }

   void statusListener(String status) {
    setState(() {
      print(status);
      lastStatus = "$status";
    });
  }

  void resultListener(SpeechRecognitionResult result) {
    setState(() {
      lastWords = " ${result.recognizedWords}";
    });
  }
}
```

**Comment by sowens-csd** [comment]
You should initialize speech_to_text once per application invocation. I usually do this in a Provider with a ChangeNotifier but you could make it a static instance or some other mechanism depending on how your app is laid out. In a particular widget then you just need to call the listen/stop/cancel methods. So the code you have in `initSpeechState` should be global and executed only once. 

Let me know if you're still having issues.

**Comment by prtrigno** [comment]
@sowens-csd I am new to flutter. Can you provide any sample code in reference to my given code? It will be very helpful. Thanks in advance.

**Comment by IliaMiasoedov** [comment]
@sowens-csd Could you write this in `readme` please? IMO It would be helpful for other developers.

**Comment by sowens-csd** [comment]
Agree, I'll add it to the readme and to the documentation for the Initialize and Listen method. Thanks for the suggestion.

**Comment by sowens-csd** [comment]
@prtrigno did you get your issue resolved? I think I'll add a provider implementation to a future version of the plugin so I'll try to get an early version of that posted by this weekend so you can have a look.

**Comment by prtrigno** [comment]
Thanks @sowens-csd . I am able to fix the issue.

**Comment by sowens-csd** [comment]
I'm going to close this now. There's a draft implementation of the SpeechToTextProvider in the repo, should be out in the next version of the plugin.
