### ISSUE TITLE
`SpeechSoundLevelChange` is not called on iOS devices.

### ISSUE THREAD

**Issue by IliaMiasoedov** [csdcorp/speech_to_text#93]
Hi! There is an issue on iOS devices. `SpeechSoundLevelChange` is not called and that's why I cannot dynamically display the voice sound level. On Android devices this callback works correctly.
Checked on iOS emulator iPhone 11 Pro Max (13.5 version).

```
Future listen(SpeechResultListener onResult,
      SpeechSoundLevelChange onSoundLevelChange) async {
    await _speechToText.listen(
        onResult: onResult,
        listenFor: Duration(seconds: 5),
        onSoundLevelChange: onSoundLevelChange);
  }
```
Flutter version - 1.17.1-stable

Thanks!

**Comment by sowens-csd** [comment]
Yes, that's true and is a known issue. It is documented on the listen method. I'm tracking this on #12. I have an implementation for iOS done but the result is very different from the Android result. On iOS it's reporting in decibels, I think correctly, but I haven't decided yet how to normalize the values between iOS and Android and whether it is important to do so. There's a lack of documentation about what the Android value means although they seem to suggest it is probably decibels.

**Comment by IliaMiasoedov** [comment]
@sowens-csd Is it possible to add this functionality in the near future? About normalization - we can check the host platform from code and do the normalization on our own.

**Comment by sowens-csd** [comment]
There's a version in the repo now that has an experimental implementation of the iOS sound level functionality. Please try it out and let me know if you have any issues.

**Comment by IliaMiasoedov** [comment]
@sowens-csd Thanks!
