### ISSUE TITLE
Listener auto stops in 2 seconds in the Android phone

### ISSUE THREAD

**Issue by abdulcader** [csdcorp/speech_to_text#94]
Hello,

I am using the Speech to Text app for Android. Once I click the listen button it listen only for 2 seconds and if there is no voice in 2 seconds it stop automatically. How to increase this limit to atleast 7 seconds so that I can speak a long sentence with some gap.

Thanks for your help.

**Comment by sowens-csd** [comment]
This is currently expected behaviour as this is the way the underlying Android speech recognizer works. I'm tracking possible ways to improve this in a future release under #52.
