### ISSUE TITLE
attr error!

### ISSUE THREAD

**Issue by loGTve** [csdcorp/speech_to_text#95]
`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':speech_recognition:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\JunYoung\.gradle\caches\transforms-2\files-2.1\a528b13ac93e64cafa3d0480e2c93207\core-1.1.0\res\values\values.xml:142:5-173:25: AAPT: error: resource android:attr/fontStyle not found.

     C:\Users\JunYoung\.gradle\caches\transforms-2\files-2.1\a528b13ac93e64cafa3d0480e2c93207\core-1.1.0\res\values\values.xml:142:5-173:25: AAPT: error: resource android:attr/font not found.

     C:\Users\JunYoung\.gradle\caches\transforms-2\files-2.1\a528b13ac93e64cafa3d0480e2c93207\core-1.1.0\res\values\values.xml:142:5-173:25: AAPT: error: resource android:attr/fontWeight not found.

     C:\Users\JunYoung\.gradle\caches\transforms-2\files-2.1\a528b13ac93e64cafa3d0480e2c93207\core-1.1.0\res\values\values.xml:142:5-173:25: AAPT: error: resource android:attr/fontVariationSettings not found.

     C:\Users\JunYoung\.gradle\caches\transforms-2\files-2.1\a528b13ac93e64cafa3d0480e2c93207\core-1.1.0\res\values\values.xml:142:5-173:25: AAPT: error: resource android:attr/ttcIndex not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 7s`

Its My Error

And no Errors when im run `Flutter Doctor`

i tried `flutter clean` `flutter pub cache repair`
and remove `.dart.tool` Folder and repair it again, Reboot Windows and more...

`compileSdkVersion 29` `minSdkVersion 23` `targetSdkVersion 29`

Help me this issue

**Comment by sowens-csd** [comment]
From the trace you sent this doesn't look like the issue is related to the speech_to_text plugin. Why do you think it might be? A search turned up this possibly related thread for Android build problems. https://github.com/OneSignal/OneSignal-Android-SDK/issues/400
