### ISSUE TITLE
How can i stop the beep sounds on start and stop

### ISSUE THREAD

**Issue by ProtoManGG** [csdcorp/speech_to_text#96]
The title says it all

**Comment by sowens-csd** [comment]
On Android they're part of the Android OS and can't be easily overridden. They're optional on iOS, if you don't include the sound files in assets it won't beep.

**Comment by ProtoManGG** [comment]
Can you link me to way to override the android ones please

**Comment by sowens-csd** [comment]
I haven't seen anything I'd consider to be a reliable method so I don't have a reference for you.
