### ISSUE TITLE
I want to ask about language

### ISSUE THREAD

**Issue by dinhan1192** [csdcorp/speech_to_text#97]
Sorry, I just wonder that can this plugin be used by other languages rather than only English?

Thank you a lot for your effort !

**Comment by sowens-csd** [comment]
Definitely. There's a `locales` property on the `SpeechToText` instance that provides the list of locales installed on the device as `LocaleName` instances. Then the `listen` method takes an optional `localeId` named param which would be the `localeId` property of any of the values returned in `locales`. Let me know if any of that is unclear. I should add it to the readme.

**Comment by dinhan1192** [comment]
Yup! I looked into other issues and found out one that is concerned with
languages! Tomorrow I will test with Vietnamese, hope it will run smoothly !
Thank you again, bro !
