### ISSUE TITLE
How can I limit the Locales in the Dropdown menu?

### ISSUE THREAD

**Issue by tedserdel** [csdcorp/speech_to_text#99]
The example code uses the device's locales, how can I limit it to a selected languages? An example is to only have English and Spanish as the options.

**Comment by sowens-csd** [comment]
Definitely, you'd probably want to either construct a list yourself or filter the returned on the language codes you want. That would look something like: 
```
  List<String> _preferredLocaleIds = [ 'en', 'en-us', 'es', 'es-ve',];

// ...
_localeNames
                    .where((locale) => _preferredLocaleIds.contains( locale.localeId ))
                    .map(
                      (localeName) => DropdownMenuItem(
                        value: localeName.localeId,
                        child: Text(localeName.name),
                      )
```

Note that this is just a sketch. I didn't actually check if the Android / iOS language codes are upper or lowercase, both follow the same ISO standard, etc. But with a little research you could make this robust I think.

**Comment by tedserdel** [comment]
Thank you Mr. Owens!

The system Locale IDs  used underscore and/or hyphen.

I used this two:
- English (United States) 'en_US'
- Spanish (Spain) 'es-ES'
